### ISSUE TITLE
Palette and Properties tabs improvements

### ISSUE THREAD

**Issue by metincansiper** [iVis-at-Bilkent/newt#1]
- change Style to Properties
- when a node is selected, Properties tab should be displayed
- title of every stackable list (except for the first one!) should be preceeded and succeeded by a line
- the area where the title of a stackable list is should be gray
- in Properties tab
    o "... Visual Properties" should be the title of a stackable list of properties just like "Properties from EntrezGene". However, it should not be stacked by default
- in Palette tab
    o both lists should be not stacked by default
    o tooltips should just contain node and interaction types: "Macromolecule" instead of "Create a new macromolecule" (tooltips in the toolbar however should stay the same; longer version)
    o borders and background of currently selected node/interaction should be consistent with those in the toolbar (one click blue borders, two clicks blue borders + gray background)
    o I like using dashed lines for node/interaction selections that aren't currently active. however, I think the dashes should be shorter (almost dot dot dot...)
- in toolbar
    o node/interaction icons should be smaller or the region allocated for these should be bigger so that the borders and the icons do not intervene with each other (let's discuss)
    o interaction icon in the toolbar is not middle aligned (left aligned)

**Comment by royludo** [comment]
I would add this: if I click to select a node, I would expect to see its properties tab displayed automatically, instead of the more general tool palette staying in place.

**Comment by ugurdogrusoz** [comment]
you're right @royludo, this is already in the above list. so, remaining to-do:
- display Properties when a node(s) is(are) selected
- use lighter gray for background of stackable list titles (e.g. 195,195,195)
- stacked/not-stacked icons (up and down arrows) are not within the bounds of the gray title background
- looks like the color for the sustain mode was changed to be lighter but it's hardly visible and needs to be a little darker than the fill color for association process
- can we decrease the thickness of dashed borders around selected node/edge? to de-emphasize it a little
- if it's possible to put an icon before tab titles (Properties and Palettes) please let me know so I can provide icons for them

**Comment by ugurdogrusoz** [comment]
Well done!
