### ISSUE TITLE
Huge bend points for thick edges

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#110]
When edge thickness/width is increased, so is the edge bend points (squares displayed when edge is selected) but they are huge:
![image](https://user-images.githubusercontent.com/3874988/28028426-279f7e30-65a5-11e7-913b-6e9c261a477e.png)
We should ease down the calculation so that those squares do not get very big as edge thickness/width increases.

**Comment by leonarddrv** [comment]
I reduced the thickness of bend points from 6 to 3. I guess it looks good like it is now.

**Comment by ugurdogrusoz** [comment]
The flag is not respected on hide. When the flag is on, and a hide is performed, an incremental layout should take place.
