### ISSUE TITLE
Weird bug on transfer in AF map

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#119]
Open up the attached AF map. Transfer Nucleus into Cytosol. You'll see that things are all messed up!
[epidermal_growth_factor_receptor_pathway.sbgn.txt](https://github.com/iVis-at-Bilkent/newt/files/1141742/epidermal_growth_factor_receptor_pathway.sbgn.txt)

**Comment by kinimesi** [comment]
@ugurdogrusoz looks like this is not specific to AF maps. It is somehow related to edge bend points: after removing bend point from the incoming edge of `c-Jun` in nucleus, everything works as expected.

Reproduce in any map type: first add edge bend point to an outgoing edge of a compound. Then try to change the parent of that compound.

**Comment by ugurdogrusoz** [comment]
@kinimesi Good catch

**Comment by ugurdogrusoz** [comment]
Looks like this is redundant: see https://github.com/iVis-at-Bilkent/newt/issues/31
