### ISSUE TITLE
Undo/redo operation works in two steps while transferring a node

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#120]
![peek 2017-07-12 14-10](https://user-images.githubusercontent.com/22586369/28115180-950b6282-670c-11e7-9519-1fd8d2bb7295.gif)

**Comment by hasanbalci** [comment]
I noticed that "Quick Help" menu recommends to use "Ctrl/Cmd + drag on a node" in order to transfer a node inside a complex/compartment. If that is the case, undo/redo works correctly. 

However, if a node is transferred into compound without dragging, but with "Ctrl + click on compound", then issue is valid.

**Comment by kaansancak** [comment]
@ugurdogrusoz via https://github.com/iVis-at-Bilkent/newt/commit/43592678f5de92d34ca4b7eb4f6ccd5769a3df4 , nodes only can be transferred by "Ctrl/Cmd + drag on a node".

**Comment by ugurdogrusoz** [comment]
I confirm this. @hasanbalci please check as well.

**Comment by hasanbalci** [comment]
@kaansancak It seems that everything returned to the beginning with the last commit. We can currently transfer a node with Ctrl + click and undo/redo operates in two steps again.

**Comment by hasanbalci** [comment]
Thanks! It is ok now.
