### ISSUE TITLE
Incorrect gene symbols in Query

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#121]
If gene symbols entered in a query are somehow not clean, we need to detect and act accordingly:
- If there are no symbols (just a bunch of invalid characters like "%^&" or blank spaces "   " ), server returns an error (like bad request). We should detect such situations, and simply return focus to Gene Symbols text box (same behavior as when you don't enter anything and just click "OK")
- If there are symbols but they contain undesired characters (e.g. "TP53_?"), we should clean up the symbols from all characters but letters and numbers, and then issue the query
- If a symbol entered is invalid (e.g. "UGUR"), we get an exception. We should simply detect such situations, and simply return focus to Gene Symbols text box.
- We should not allow any value more than 3 in Length limit. When a larger value is entered, we should simply return focus to this text box

**Comment by leonarddrv** [comment]
There is a problem regarding detecting blank spaces and returning focus to Gene Symbols text box in the case. Maybe the user wants to use space for separating 2 gene symbols from each other. Should this option be removed and make the user put gene symbols in different lines or separated with tab?

**Comment by ugurdogrusoz** [comment]
I think separating with blank spaces should stay. I guess the only problem is when the entire thing is blank spaces not things like "  BRCA1   BRCA2        ".

**Comment by leonarddrv** [comment]
@ugurdogrusoz  For the length limit, should we add something in parenthesis to show that 3 is max.[Stop Distance (max is 3)]. The reason is that the dialog focuses on length limit when it is over 3 but the user may not understand it.
Also, should we detect similar situations for Paths by URI?

**Comment by ugurdogrusoz** [comment]
@leonarddrv Good idea to warn about length limit

**Comment by ugurdogrusoz** [comment]
When I enter genes on separate lines like this:
BRCA1
BRCA2
It says "Invalid query!". I should be able to do this.

**Comment by ugurdogrusoz** [comment]
When the URI consists of no letters but special symbols we get an error (keeps spinning):
www.pathwaycommons.org/pc2/get?uri=%*&^%^&&format=SBGN
Failed to load resource: the server responded with a status of 400 (Bad Request)

**Comment by ugurdogrusoz** [comment]
@leonarddrv please transfer these changes to master asap
