### ISSUE TITLE
Context menu of AF nodes not to include Highlight Processes

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#122]
If the associated node on a right click is an AF node, we shouldn't display Highlight Processes

**Comment by kinimesi** [comment]
@ugurdogrusoz For this we need to be able to differentiate PD and AF nodes. One way is to use node classes. But it is not always possible to differentiate AF nodes from PD nodes by using classes (logical operators _can connect to processes_ and they have the same class in both map types). Another way is to use the `language` attribute of nodes. But when loading a file this attribute is not set and cannot be set properly always (apparently language field in SBGN files is optional).

**Comment by kinimesi** [comment]
@ugurdogrusoz Now `Highlight Processes` is displayed only for unspecified entity, simple chemical, macromolecule, nucleic acid feature, complex and multimers.
