### ISSUE TITLE
Error on loading a file with unsupported content

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#125]
If user tries to load a file with a wrong content, independent from file extension, the tool gives error. However, if the content is ok, but the file extension is something unrelated such as .txt or .graphml, it works correctly. 

Maybe some parts of the content can be checked and a warning message can be displayed if the file content is not in the correct format to work in the tool.

**Comment by ugurdogrusoz** [comment]
@royludo please make sure your library somehow detects and returns an appropriate error, so the application can handle it. when done pass it back to me.

**Comment by royludo** [comment]
Now if there are errors on load (mostly from wrong file format), they are logged cleanly on the console and we avoid application crash. But nothing happens, from a user perspective. Should we maybe show some error popup message ?

**Comment by ugurdogrusoz** [comment]
I suppose we should pop up an error dialog in such cases and do not do anything. The dialog content:
- Title: Error
- Content: Incorrect file format!
- Button(s): single button with label "OK"
