### ISSUE TITLE
Parts of layout not undoable

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#126]
The two new heuristic (swapping substrates and products and re-orienting ports) performed as a post-processing step to layout don't look undoable. In addition, edge bends are destroyed by layout. They should all be part of the batch of operations that are undone.

**Comment by ugurdogrusoz** [comment]
@hasanbalci Works nicely in general. I see two problems though:
- Undo is problematic with topology grouped SIF maps
- Undo is problematic on layout called within Expand-Collapse operations (for instance edge bends are lost on undo)

**Comment by ugurdogrusoz** [comment]
@nasimsaleh Please test undo/redo for especially the following operation, paying special attention to compound node sizes (nodes with non-zero bias) and ports:
- layout
- expand/collapse (with incremental layout performed during these operations)
- hide/show (with incremental layout performed during these operations)

**Comment by nasimsaleh** [comment]
@hasanbalci  Performing layout doesn't work. it throws exception in the console.
![layout error](https://user-images.githubusercontent.com/16354894/76313597-4fdb6580-62e6-11ea-8e0d-67d9a5de18a1.JPG)

**Comment by hasanbalci** [comment]
@nasimsaleh It should be working now. Can you please try again?

**Comment by nasimsaleh** [comment]
@ugurdogrusoz @hasanbalci  It seems to work fine.

**Comment by ugurdogrusoz** [comment]
@hasanbalci I wonder if we can save and restore (on undo) the current zoom and pan levels on layout?

**Comment by hasanbalci** [comment]
During expand/collapse and hide/show operations, even though layout is disabled, bend points and compund bias values were being lost. https://github.com/iVis-at-Bilkent/sbgnviz.js/commit/328027ffa0b69348c1716d9aef711b613823b18b solves this problem together with #573.
