### ISSUE TITLE
Ordering of nodes in Palette and Legend is not consistent

### ISSUE THREAD

**Issue by leonarddrv** [iVis-at-Bilkent/newt#127]
The ordering of nodes in Legend menu is different from the ordering of them in Palette.
-Their order should be consistent
-Most frequently used nodes should be placed before the others

**Comment by hasanbalci** [comment]
Newly added submap node is also missing in the Legend Menu.

**Comment by ugurdogrusoz** [comment]
@leonarddrv Please use the new, updated legends to order nodes/edges in the palette

**Comment by leonarddrv** [comment]
@ugurdogrusoz I'm a little bit confused in the ordering of edge types in Process Description. 
Because for the other nodes I have considered their vertical order, and I think it is not the case for these edges.

**Comment by ugurdogrusoz** [comment]
PD: consumption, production, modulation, stimulation, catalysis, inhibition, necessary stimulation, equivalence arc, logic arc
AF: vertical order

**Comment by hasanbalci** [comment]
@leonarddrv @ugurdogrusoz I think the order of equivalence and logic arcs should be consistent between map types in terms of user-friendly interface. Currectly, it is equivalence arc - logic arc in PD and vice versa in AF palette.

**Comment by ugurdogrusoz** [comment]
@leonarddrv please change the order of the two in PD part of the palette (I did it for the PD Legend)
