### ISSUE TITLE
Adding tooltips for Layout Properties

### ISSUE THREAD

**Issue by leonarddrv** [iVis-at-Bilkent/newt#130]
Tooltips with a short description for each layout property should be added to the "Layout Properties" dialog.

**Comment by ugurdogrusoz** [comment]
I made the following changes in the explanations (see README.md filen cose-bilkent master branch).
- Ideal (intra-graph) edge length
- Whether to tile disconnected nodes
- Nesting factor ... for inter-graph edges
- Whether to perform animation during layout
- Amount of vertical space to put between degree zero nodes during tiling (can also be a function)
- Amount of horizontal space to put between degree zero nodes during tiling (can also be a function)
Please update tooltips accordingly.

**Comment by leonarddrv** [comment]
@ugurdogrusoz  I updated the tooltips accordingly, but for the last ones I left out (can also be a function) part since it's related with the programming part. Should it be included?

**Comment by ugurdogrusoz** [comment]
makes sense, thanks!
