### ISSUE TITLE
Width and height limits should be set for different type of nodes

### ISSUE THREAD

**Issue by leonarddrv** [iVis-at-Bilkent/newt#132]
When a complex is added from palette, and set width to a number less than 25 the node gets a weird shape.
Here is an example with width set to 15
![screenshot from 2017-07-20 16 01 50](https://user-images.githubusercontent.com/22965866/28418557-c94488e0-6d64-11e7-8dbb-16e60e8d164a.png)

**Comment by ugurdogrusoz** [comment]
We have similar problems with barrel. Interestingly drawing problems disappear at lower zoom levels (maybe Cytoscape.js core approximates shapes at low zoom levels to increase performance?). Same barrel node with varying widths:
![epidermal_growth_factor_receptor_pathway sbgn 1 1](https://user-images.githubusercontent.com/3874988/28498517-e9dee2c2-6fa7-11e7-93e2-bed260aa5880.png)
Associated model (zoom in and out to see what I mean):
[epidermal_growth_factor_receptor_pathway.sbgn (1) (1).txt](https://github.com/iVis-at-Bilkent/newt/files/1168003/epidermal_growth_factor_receptor_pathway.sbgn.1.1.txt)

When we fix the barrel shape we should let Cytoscape.js guys know about it.
