### ISSUE TITLE
Parent changes to submap after save and load

### ISSUE THREAD

**Issue by kinimesi** [iVis-at-Bilkent/newt#134]
Add submap to a compartment. After save and load, the parent of nodes inside compartment changes to submap (the label of submap changes too). Screenshots are given below.
**Original Map**
![screenshot_20170720_161306](https://user-images.githubusercontent.com/7281872/28419534-ea11cf30-6d67-11e7-9c9a-224d56eae280.png)
**After save and load**
<img src="https://user-images.githubusercontent.com/7281872/28419551-f9e20cea-6d67-11e7-9acb-004138dfd9bb.png" width="300" height="250">

Also when submap is added to a complex, after save and load the label of submap changes.

**Comment by ugurdogrusoz** [comment]
https://github.com/iVis-at-Bilkent/chise.js/issues/75
