### ISSUE TITLE
Edge arrows are always filled black on save as JPG

### ISSUE THREAD

**Issue by metincansiper** [iVis-at-Bilkent/newt#136]
When I export the default map as JPG the attached file is downloaded (Realize that all edge arrows are filled black while this is not the case for the original map)
![neuronal_muscle_signalling](https://user-images.githubusercontent.com/6534865/28453746-3fd3aecc-6e01-11e7-821a-f942810a7f13.jpg)

**Comment by kinimesi** [comment]
Ported from https://github.com/cytoscape/cytoscape.js/issues/1907
