### ISSUE TITLE
Is there a default color scheme by default

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#139]
When you start Newt, and go to Map Properties and check the Color Scheme, none of the color schemes is chosen as the current scheme. But when you select a particular Color Scheme and then undo, you notice that the first (b&w) color scheme is selected. So, is this the default color scheme? If so, shouldn't it be selected by default on start up?

**Comment by ugurdogrusoz** [comment]
Another related problem:
- Start Newt
- Click on the Reverse icon for the last Color Scheme in Map Properties
- Undo
Now you'll see that color scheme was changed to b&w but the last color scheme is still reversed and selected:
![image](https://user-images.githubusercontent.com/3874988/28498877-0cb53022-6fb1-11e7-862e-4bbeeb61877e.png)

**Comment by ugurdogrusoz** [comment]
Were we not supposed to *select* the default b&w scheme on new document?

**Comment by kinimesi** [comment]
@ugurdogrusoz yesterday you said that user may want to continue with the same color scheme. So let's do not change color scheme when a new file is created.

**Comment by ugurdogrusoz** [comment]
OK, let's leave it as is. I was confused since there is no way to see the default color scheme (since a default pathway with a certain color scheme is loaded by default)
