### ISSUE TITLE
Expand/collapse visual cue difficult to hit on Firefox

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#141]
On Firefox (Windows, latest Firefox), when you're at low zoom levels (zoomed out), it's very difficult / impossible to hit the cue to expand/collapse cues. You can achieve the operation by hitting outside the cue (near lower right corner) though I think. Example (mouse is where red dot is, and nothing happens on click):
![image](https://user-images.githubusercontent.com/3874988/28498967-4986252c-6fb3-11e7-88b8-310f0745cd1d.png)

**Comment by kinimesi** [comment]
This issue will be solved automatically when https://github.com/iVis-at-Bilkent/newt/issues/52#issuecomment-317456338 is solved.
