### ISSUE TITLE
Unit of information boxes on collapsed compound nodes

### ISSUE THREAD

**Issue by istemi-bahceci** [iVis-at-Bilkent/newt#142]
As it can be seen from the image below, when a compound is collapsed with too many unit of information boxes, unit of information boxes are rendered. 

<img width="863" alt="screen shot 2017-07-23 at 16 04 07" src="https://user-images.githubusercontent.com/8645080/28499533-dd606840-6fc0-11e7-853e-3271f1719dc8.png">

**Comment by ugurdogrusoz** [comment]
I think same problem as this: https://github.com/iVis-at-Bilkent/newt/issues/104
