### ISSUE TITLE
Copy-paste issue

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#145]
- Create a complex with a node in it
- Collapse the complex
- Copy and paste to clone it
- Now expand the clone
You'll see that it's empty and the original which was supposed to stay collapsed is expanded!
Hint: Turn arrangement on complexity management off to better track what's going on

**Comment by kinimesi** [comment]
As we discussed, collapsed compounds are shallow copied: during copy operation, they are converted to simple nodes. Meta edges and all the data related to expand-collapse are removed.
