### ISSUE TITLE
Add SVG export

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#147]
Let's add this under Save as Image (at the end of the current list).
If this is to go to library level, I suppose it should go to SBGNViz.js; if to the app level then we need to add it to both apps.

**Comment by ugurdogrusoz** [comment]
Great! The only problem I can see is that catalysis arrow isn't rendered properly (see default map)

**Comment by kinimesi** [comment]
This is most ptobably due to a bug in Inkscape: https://bugs.launchpad.net/inkscape/+bug/1284409 

Fixed in Inkscape >= 0.92

**Comment by ugurdogrusoz** [comment]
Correct; looks fixed in 0.92
