### ISSUE TITLE
Expose edge arrow sizes to user

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#148]
I don't see why we shouldn't expose arrow scale (arrow head sizes) to users under General Map Properites as "Edge arrow size" to be a slider or a percentage where arrows are sized minimally at 0 and maximally at 100.

**Comment by ugurdogrusoz** [comment]
1) we need this at map level (not per edge). 
2) please change the values of slider such that 0.5 is the default arrow-scale (1.25) but 0 and 1.0 map to smaller and larger values, resp. (say 0.5 and 2.0)
3) make sure the change is at library (ChiSE) level. in other words, there is an API for changing this value and the sample app (Newt) uses this.

**Comment by leonarddrv** [comment]
@ugurdogrusoz  For the 3. point, I don't think it is necessary to add a particular API,  since  changeCss function can be used from Chise level by just giving as parameter 'arrow-scale'.

**Comment by ugurdogrusoz** [comment]
@leonarddrv You're right about the API. Some improvements:
1) "Arrow Size" -> "Edge Arrow Size"
2) A bigger issue is can we make sure the newly added edges (any edge added after the slider value has been changed) gets the updated arrow size?

**Comment by hasanbalci** [comment]
I don't know maybe this is related with cytoscape.js, but when we decrease the edge arrow size, after some point, the line before triangle-shape arrow in the necessary stimulation edges disappear.

**Comment by ugurdogrusoz** [comment]
@kinimesi Could you please make sure Edge Arrow Size is also stored on Export and restored on Load?
Also, could you verify that issue @hasanbalci reported is a Cytoscape.js issue? If so, ticket an issue with them please.

**Comment by kinimesi** [comment]
See https://github.com/cytoscape/cytoscape.js/issues/1921
