### ISSUE TITLE
Default port orientation for processes and logical operators

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#151]
Default port orientation for all processes and logical operators should be left-to-right but currently only for generic processes that seems to be the case!

**Comment by leonarddrv** [comment]
It seems like I had misunderstood it from instructions in #106. 
What about the case when the user creates a process and its consumption and production edges simultaneously, should it display the best orientation for other types of processes as well? (Currently it works only for generic processes)

**Comment by ugurdogrusoz** [comment]
Yes, process means all types of processes. It is unfortunate that SBGN calls one type of process just "process", which causes misunderstandings.

**Comment by leonarddrv** [comment]
I also changed the optimal port orientation for all types of processes
