### ISSUE TITLE
Move logo to right

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#152]
Let's move the logo to the right and display the file / model name in the middle as shown here:
![image](https://user-images.githubusercontent.com/3874988/28823137-cdb92b88-76c4-11e7-997b-8c4aa02cd2fa.png)

**Comment by hasanbalci** [comment]
Doesn't this seem better?
![newtmain](https://user-images.githubusercontent.com/22586369/28847017-535ffc34-7716-11e7-93cb-051b8121baeb.png)

**Comment by ugurdogrusoz** [comment]
This looks better on a big screen but when the window isn't as wide:
- toolbar might not fit (longer than menubar)
- filename isn't as visible
So, I am not sure, let's talk face to face.

**Comment by ugurdogrusoz** [comment]
Let's try it like this for a while
