### ISSUE TITLE
Layout animation broken

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#156]
Animation at the end of layout (animation=end; animation flag in Layout Properties disabled) doesn't seem to be working properly.

**Comment by hasanbalci** [comment]
I think this commit https://github.com/cytoscape/cytoscape.js-cose-bilkent/commit/2f1a29891128f8293f6fce74c269f4d6aaf8a12a resolves the issue.

**Comment by ugurdogrusoz** [comment]
See the result of calling non-incremental layout on this one:
[Activation of caspases through apoptosome-mediated cleavage.sbgn.txt](https://github.com/iVis-at-Bilkent/newt/files/1209389/Activation.of.caspases.through.apoptosome-mediated.cleavage.sbgn.txt)

1) I am not sure animation (end) is performed
2) See what happens at the end very frequently and some nodes move and as a result compartments overlap (could this be somehow related to the post-processing for improving flow of processes?)

**Comment by hasanbalci** [comment]
Yes, it may be related with improving flow, because when we disable that feature, nodes do not move unexpectedly and compounds do not overlap.

**Comment by ugurdogrusoz** [comment]
@leonarddrv looks like this is related to layout post-processing (improve flow flag makes the difference)

**Comment by leonarddrv** [comment]
Yeah, I investigated that issue and I came to the conclusion that a swapping of two free nodes is occurring, but the problem is that they belong to different compartments so the compartments overlap.
@ugurdogrusoz  As a possible solution, for the swapping of free nodes it should be taken in consideration if they belong to the same compound (or not to any). Should I implement it?

**Comment by ugurdogrusoz** [comment]
@leonarddrv You're right; I think we should allow swapping only if they belong to the same component
Also, we only allow swapping of simple nodes right? If not, I think we should do so since compounds can be rather large creating overlaps after swaps

**Comment by leonarddrv** [comment]
Yeah, we only allow swapping of simple nodes currently. So only the checking if they belong to the same component will be added.

**Comment by leonarddrv** [comment]
This commit https://github.com/iVis-at-Bilkent/sbgnviz.js/commit/a368c72b14a25e347eefa11754d5ec56f6f00fd5 should have solved the problem.
