### ISSUE TITLE
Undo (expand all?) taking forever

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#159]
- Load 2nd PD sample (CaM-CaMK one)
- Collapse Complexes
- Collapse Nucleus
- Undo
- Undo
Second undo takes a very long time!

**Comment by hasanbalci** [comment]
I think it is because of the expand-collapse extension. Expanding too many nodes takes a long time. You can see that by clicking to "expand all" before undoing.

**Comment by ugurdogrusoz** [comment]
Great!
