### ISSUE TITLE
Drag and drop nodes

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#16]
I think current functionality is great but ability to drag and drop of nodes from the palette into the canvas might be useful for people who are used to this kind of behavior.

**Comment by royludo** [comment]
Implemented in 259310779c58bcbcfac7bf2d524f6cb82303b232

**Comment by ugurdogrusoz** [comment]
Nice! I should have specified this earlier but can we actually create the node "earlier" and show it as the user drags? See how it's done here: [pathwaymapper.org](http://pathwaymapper.org).

**Comment by royludo** [comment]
I added the image, not exactly like pathwaymapper though. It appears in the bottom right side of the cursor. I find that it gives a little "projection", or "drop" effect when you release it, I thought you might want to test it. Tell me what you think, I can always put the image at the center of the cursor.

**Comment by ugurdogrusoz** [comment]
I think this is good (except edge creation and other things seem to be broken for some reason)
