### ISSUE TITLE
Improve initial placement on showing hidden neighbors

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#160]
Upon "Show Hidden Neighbors", we now try to find a good quadrant for the neighbors. However, often times the node itself gets tangled with neighbors of a neighbor (e.g. modulator of a neighboring process). Let's please do the following if the map type is PD: expand the neighbors selection before deciding which quadrant(s) are empty.

**Comment by ugurdogrusoz** [comment]
Maybe we can add one additional heuristic here: if only one of the 4 quadrants is occupied, we should use the "opposite" one for initial placement, rather than any one of the available 3. For instance, if only the upper right quadrant is occupied, we should use the lower left one for initial placement.

**Comment by leonarddrv** [comment]
This commit: https://github.com/iVis-at-Bilkent/chise.js/commit/5a53dd18f9acf3b81a30e210af0ffba0e920487c should address the issues mentioned.
