### ISSUE TITLE
Incorrect marking of nodes with hidden neighbors

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#162]
- Open the sample Glycolysis
- Hide everything in this process *after* fructose 1,6p
- Show hidden neighbors of fructose 1,6p
- Show hidden neighbors of DHA-P
Notice that there is nothing marked as "has hidden neighbors"; yet GA-3P has further neighbors that are hidded! I think we are marking all nodes with some shown neighbor as "no longer has hidden neighbors" but we need to make sure all neighbors were shown before we do that.

**Comment by hasanbalci** [comment]
Now I noticed that "Rearrange on Complexity Management" flag is disabled, it works correctly. I think some changes are made after my implementation, i will have a look at that.
