### ISSUE TITLE
Invalid parent on node creation

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#17]
The new feature to directly add a node into an existing compartment does not check whether or not the parent is valid one for the current node type (e.g. add a process into a complex).

**Comment by royludo** [comment]
Also, adding a node that way into a empty compound doesn't work. But if the compound has already 1 or more elements, it works.

**Comment by metincansiper** [comment]
The problems here seems to be solved now.
