### ISSUE TITLE
Pubmed id validation problem

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#181]
From Marek:
I’ve noticed that there is a small problem with pubmed identifiers in the custom annotations. See attached screenshot. It is most likely caused by the different handling of pubmed in [indetifiers.org](http://identifiers.org/).

Providing an identifier formatted like this:
http://identifiers.org/pubmed/1234567
works for Newt.

![image](https://user-images.githubusercontent.com/3874988/31115447-aed4e268-a822-11e7-9458-1ba933fa2b69.png)

**Comment by kinimesi** [comment]
There was a problem with [identifiers.org](identifiers.org) API. It has been resolved recently.
