### ISSUE TITLE
Quick UI help

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#183]
Use of intro.js for quick introduction of our UI is a good idea brought up by @hasanbalci.

**Comment by ugurdogrusoz** [comment]
Can we embed short videos within these introduction pages?

**Comment by ugurdogrusoz** [comment]
We decided to go with intro.js. They graciously agreed to license it to us under LGPL.

**Comment by hasanbalci** [comment]
I will also add cookie warning.

**Comment by ugurdogrusoz** [comment]
Quick Tutorial:
- newt image missing (incorrect URL)
UI Guide (location specified as page number):
(4) "on one of the following forms at any time" -> "in one of the following modes at any given time"
(4) "Remaining Edit Operations:" -> "Remaining edit operations:"
(4) "neighbors leaving" -> "neighbors, leaving"
(4) "wrt." -> "w.r.t."
(6) "Search: ..." -> "Search" (please see #345 )
(-3) "object(s)" -> "object" (since we specify multiple selection separately now)
(-1) "returns to selection mode" -> "returns to selection (Select / Edit) mode"
(-1) "select/edit mode" -> "Select / Edit mode"

**Comment by ugurdogrusoz** [comment]
Perfect!
