### ISSUE TITLE
Arranging annotations select list according to most used

### ISSUE THREAD

**Issue by royludo** [iVis-at-Bilkent/newt#184]
Someone took the time to analyse how frequently the annotations are used (I think for SBML mostly but it's the same for us):

https://www.ebi.ac.uk/biomodels/COMBINE-annot/BioModels-data-collections-qualifiers-20170608.pdf

We could put the most frequent descriptors and databases on the top of the selectlists.

**Comment by ugurdogrusoz** [comment]
Cadillac feature
