### ISSUE TITLE
Launch with a model from file

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#187]
Support of start Newt with a local file would be great, such as:
    http://web.newteditor.org/?filename=<filename.sbgn>

**Comment by ugurdogrusoz** [comment]
@ahmetcandiroglu let's have a quick talk before you start with this issue

**Comment by ugurdogrusoz** [comment]
Here the file name could be 1) locally on disk (file:///C:/Users/ugur/Documents/sbgn1.sbgn) 2) remote (specified with a URL: http://example.com/maps/sbgn1.sbgn)

**Comment by jvwong** [comment]
Related: URI parameter (e.g. pathway commons / apps)

**Comment by ugurdogrusoz** [comment]
Yes, good idea, let's add support for a URI instead of a URI.

**Comment by ahmetcandiroglu** [comment]
I implemented loading a file from a URL however it seems it is not possible loading from local machine due to security issues. (The user must select a file in order it to be loaded) @ugurdogrusoz

**Comment by ugurdogrusoz** [comment]
@ahmetcandiroglu Load from a URL works, thanks! Here is a sample: http://www.cs.bilkent.edu.tr/~ivis/Newt_daily/?filename=http://www.cs.bilkent.edu.tr/~ivis/temp/polyq_proteins_interference.sbgn. Some minor problems and work left to do:
- Looks like the file extension is required to be .sbgn or .sbgnml. Sometimes people use .xml, .txt, etc. Let's not limit the extension at all, instead look at content (similar to Load).
- A strange behavior is the following. Suppose newt is open in a tab. Now go and paste newt URL with a filename. It loads the file fine but after load, it prompts for "All unsaved changes will be lost..."!
- Left to do: load by URI. it doesn't make sense to be using "filename" for this. Maybe we can use "URL" for files and "URI" for PC query by ID?

**Comment by kinimesi** [comment]
@ahmetcandiroglu another minor problem: it looks like you always set filename to `remote-file.xml`. You need to get it from the URL - filename is the string after last slash in the URL.

**Comment by ahmetcandiroglu** [comment]
Used ?url=<URL> and ?uri=<URI> as desired queen format but they can be changed. Fixed bugs mentioned earlier.

**Comment by ugurdogrusoz** [comment]
I was able to confirm these working in daily build, thanks. Further improvements:
- When URL is incorrect (file doesn't exist or content not correct), it says "Invalid URI!", should say "Invalid URL!"
- Upon load of a URI (not URL), we should perform an automatic (non-incremental) layout (like we now -
 lately changed - do with PC queries from the Query dialog).

**Comment by ugurdogrusoz** [comment]
@ahmetcandiroglu Also need to make sure "Infer Nesting on Load" flag is temporarily ignored and nesting is not inferred when loading by URI (same as PC queries). @hasanbalci can tell you how to do this.

**Comment by hasanbalci** [comment]
@ahmetcandiroglu You can see my [commit](https://github.com/iVis-at-Bilkent/newt/commit/dee36284cd744f28324a796d5dae0d4d7c20e9fe) while handling this in PC queries.

**Comment by ahmetcandiroglu** [comment]
@ugurdogrusoz I did ignore "Infer Nesting on Load" flag when loading by URI as it is in PC query. However, I could not see how to perform auto layout in PC query function.

**Comment by hasanbalci** [comment]
@ahmetcandiroglu I saw your pull request now, I think you did both of them. The third parameter "true" in updateGraph function does the auto-layout.

**Comment by ugurdogrusoz** [comment]
@ahmetcandiroglu Just tried these:

- With 3 't's in htttp (URI), it hangs with spinner displayed:
http://www.cs.bilkent.edu.tr/~ivis/Newt_daily/?Uri=htttp://identifiers.org/reactome/R-HSA-6803211#

- With 3 't's in htttp (URL), it comes back empty without any errors:
http://www.cs.bilkent.edu.tr/~ivis/Newt_daily/?URL=htttp://www.cs.bilkent.edu.tr/~ivis/temp/polyq_proteins_interference.sbgn

**Comment by ugurdogrusoz** [comment]
Layout and inference are working fine!

**Comment by ahmetcandiroglu** [comment]
@ugurdogrusoz 

- URI bug appears in load from PC query dialog as well.
- URL bug is fixed.

**Comment by kinimesi** [comment]
@ugurdogrusoz @ahmetcandiroglu this due to a problem on Pathway Commons. Try to open this http://www.pathwaycommons.org/pc2/get?uri=htttp://identifiers.org/reactome/R-HSA-6803211&format=SBGN in browser, it hangs and does not load anything - no error message is returned. Because of that the spinner keeps turning.

Same problem occurs when the protocol part of the URI is replaced with anything other than `http` and `https`.

**Comment by ugurdogrusoz** [comment]
I think this feature is now complete! Great job @ahmetcandiroglu
