### ISSUE TITLE
Load model from text file

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#189]
We should provide support for uploading tab-delimited text files. Initially we can do this for AF models only. The format could be as follows:

\<Format version\> (initially 1.0)
\<Pathway title\>
\<Pathway description\>
--NODE_NAME NODE_ID NODE_TYPE PARENT_ID POS_X POS_Y WIDTH HEIGHT--
NUCLEUS 1 COMPARTMENT -1 100 100 250 250
RB1 2 BIOLOGICAL_ACTIVITY 1 120 120 40 40
CDK4 3 BIOLOGICAL_ACTIVITY 1 170 170 40 40
...
--EDGE_ID SOURCE TARGET EDGE_TYPE--
10 2 3 POSITIVE_INFLUENCE
...

**Comment by ugurdogrusoz** [comment]
@kaansancak let's have a quick talk before you get started

**Comment by ugurdogrusoz** [comment]
We have a similar format for persisting models in PathwayMapper (https://github.com/iVis-at-Bilkent/pathway-mapper). Please take a look to see if you can reuse some of the code.

**Comment by ugurdogrusoz** [comment]
Here is a sample file (manually edited, watch out for potential formatting problems!)
[Newt_AF_sample_input.txt](https://github.com/iVis-at-Bilkent/newt/files/1512785/Newt_AF_sample_input.txt)

**Comment by kaansancak** [comment]
I have implemented the feature however since we are not currently have the interface for loading text files, I couldn't push it. Here is the loaded image for Newt_AF_sample_input.txt
![newt_af_sample_loaded_img](https://user-images.githubusercontent.com/18530085/33529650-db02d646-d884-11e7-923b-2e0a07781223.jpg)
-11e7-9bba-50d7777b8a80.jpg)

**Comment by ugurdogrusoz** [comment]
Great! Please do a PR (at SBGNViz level?) for this.  It will be exposed after the changes in [this issue](https://github.com/iVis-at-Bilkent/newt/issues/207)

**Comment by ugurdogrusoz** [comment]
Some remaining issues:
- Change the line with version to include map type as well: "1.0" -\> "SBGNViz AF 1.0"
- Make sure \<Pathway title\> goes to Map Properties \> Name, \<Pathway description\> goes to Map Properties \> Description.
- Make edge coordinates and dimensions (POS_X POS_Y WIDTH HEIGHT) optional. If not provided, use (0,0) for position, and default dimensions for the associated node type.
- Make node and edge types case insensitive (e.g. BIOLOGICAL_ACTIVITY = Biological_Activity = biological_activity, etc.)

**Comment by kinimesi** [comment]
@kaansancak One more thing related to invalid files:
- while reading from file, if any error occurs (required fields are not provided, or node/edge type is not valid and etc.) abort the operation and return false (we can use the return value to warn user about incorrect file format)
- if the file format is not correct (i.e. first line does not match `SBGNViz AF`, stop and return false)

**Comment by ugurdogrusoz** [comment]
I tried to confirm this with this morning's build but the load failed, with this error in Console:
Uncaught TypeError: chiseInstance.loadTDFile is not a function
    at HTMLInputElement.<anonymous> (bundle.js:1762)
    at HTMLInputElement.dispatch (bundle.js:75537)
    at HTMLInputElement.elemData.handle (bundle.js:75349)

**Comment by kaansancak** [comment]
@ugurdogrusoz additions done in sbgnviz level haven't approved yet. After merge in sbgnviz it should work.

**Comment by kinimesi** [comment]
I fixed a few problems and merged the PR.

@ugurdogrusoz Right now, it is not possible to add labels to glyphs from the file. Will there be support for that in tab-delimited file format?

**Comment by ugurdogrusoz** [comment]
Thanks @kinimesi. Node names (NODE_NAME) are the labels for nodes, right? There is no need to associate labels with other types of glyphs in this simple format.

**Comment by ugurdogrusoz** [comment]
@kaansancak I tried testing this with the following text file (same as earlier except a blank line was removed and double dashes were included both before and after node and edge headings) but I get "incorrect file format". Can you tell me what's wrong with the format of this file?
[Newt_AF_sample_input (1).txt](https://github.com/iVis-at-Bilkent/newt/files/1561684/Newt_AF_sample_input.1.txt)

**Comment by kaansancak** [comment]
@ugurdogrusoz format line should start with SBNGVIZ AF, probabaly that’s the reason.

**Comment by ugurdogrusoz** [comment]
@kaansancak How about now?
[Newt_AF_sample_input (2).txt](https://github.com/iVis-at-Bilkent/newt/files/1562047/Newt_AF_sample_input.2.txt)

**Comment by kaansancak** [comment]
Currently format line is case sensetive, if you want I can change it and one more is issue is there must be one blank space between the last node and edge start point. 
[Newt_AF_sample_input (2) (2).txt](https://github.com/iVis-at-Bilkent/newt/files/1562075/Newt_AF_sample_input.2.2.txt)

**Comment by ugurdogrusoz** [comment]
I see. Let's try being a bit more flexible in the format by doing the following:
- Make version number, node and edge headers case insensitive
- Do not require a blank line between nodes and edges

**Comment by kaansancak** [comment]
@ugurdogrusoz I have implemented requested changes.

- Format version, node and edge headers are now incase sensetive

- Blank space between edges and nodes are optional
