### ISSUE TITLE
Change color of disabled resize grapple icon

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#19]
When a node is not supposed to be resized in a certain direction, we draw the grapple unfilled and when mouse is over that grapple we also display an (no entrance kind of) icon in red. Can we change the color of this icon to black (from red)?

**Comment by royludo** [comment]
@ugurdogrusoz  The mouse cursor for that is set in the node-resize extension, through the ocanvas library. I tried to use a custom image, but this library doesn't seem to have support for that. Only for the defaults cursors. I emailed the developer to ask him. If nothing is done on this library's part, I think it may be overly difficult to do that.

**Comment by kinimesi** [comment]
@ugurdogrusoz @royludo Setting a custom image in PNG format works (I could not get an SVG image to work). @royludo try: `canvas.mouse.cursor("url('http://image.flaticon.com/icons/png/128/70/70358.png')");`

**Comment by kinimesi** [comment]
@royludo SVG images are scalable, that is why we prefer them. 

I think that is a good one: http://www.flaticon.com/free-icon/cancel_97603

In order to make SVG files work we need to add width and height values into it.

**Comment by ugurdogrusoz** [comment]
Let's please decrease the size of this icon by 1/4 or 1/3 to be compatible with other grapple icons.

**Comment by ugurdogrusoz** [comment]
I think grapples for resize are even smaller on Mac, you might want to make disable icon even smaller

**Comment by ugurdogrusoz** [comment]
OK I checked with Windows as well. The situation is (using Chrome on both):
- inactive cursor is smaller than others on Windows
- inactive cursor is larger than others on Mac
So I don't know what to suggest. How come different cursors are used on Windows and Mac?

**Comment by kinimesi** [comment]
There is no way to get current cursor size and set disabled grapple icon size accordingly. I set it to 15x15, which looks reasonable on Windows and Mac. See https://github.com/iVis-at-Bilkent/newt/commit/66ee87d760ed6c4bf2d3a35bea1559a86719fa6d

**Comment by kinimesi** [comment]
Should we fill inside of current icon? It is transparent right now.

**Comment by ugurdogrusoz** [comment]
yes let's make it non-transparent.
i think what we have is fine regarding icon dimensions.
