### ISSUE TITLE
Inferring owner compound on load

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#190]
Currently we infer the owner/parent compound of a node on load. In other words, when no compartmentRef is specified but the node is within the bounds of a compound node, we assign that node as a child to that compound node. This inference results in incorrect nesting when the map is not nicely laid out. So we should make this optional (and false by default). This option should be at SBGNViz level and should be exposed at Newt application under General Properties with name "Infer Parent Node on Load" (default false).

**Comment by hasanbalci** [comment]
Now there is an option with name "Infer Parent Node on Load" under General Properties with default value "false". Its effect can be seen in PC queries clearly.
