### ISSUE TITLE
```selectedLanguage``` in ```modeHandler```

### ISSUE THREAD

**Issue by metincansiper** [iVis-at-Bilkent/newt#193]
Hi,

There is a ```selectedLanguage``` property that is maintained in ```modeHandler```. If I understand correctly this property is maintained to figure out from which palette the selected element type comes from. It is used while creating new elements by being passed to ```chise.addNode()``` and ```chise.addEdge()```. However, I think that maintaining just one property may yield unexpected behaviors and separate properties should be maintained for nodes and edges. 

For example, what is the expected value of this property when the current status of the palette tab is as the following?

<img width="280" alt="palette" src="https://user-images.githubusercontent.com/6534865/32340951-48f1861e-bfb9-11e7-85e7-17d12e90c102.png">

Am I right or missing something?

**Comment by ugurdogrusoz** [comment]
@metincansiper For the screenshot provided, neither the equivalence arc in PD palette nor the complex in AF palette is currently active (dashed borders).  So, selected language could be "none". What is the actual value of ```selectedLanguage``` in this case?

**Comment by metincansiper** [comment]
@ugurdogrusoz as far as I experimented it would be either "PD" or "AF". If the inactive element in "AF" tab was active before the selection mode is chosen then it is "AF", otherwise it is "PD".

I think that if add node mode (just as an example the same is true for edges as well) is selected from the palette then the following line is executed (https://github.com/iVis-at-Bilkent/newt/blob/71db0886a1a348da4e9339b034763bc271f9ea1f/app/js/app-menu.js#L606) and selected language in mode handler is set according to the type of palette ("PD" or "AF") and that would prevent the problem. However, if it is selected from the toolbar then the following code line is executed (https://github.com/iVis-at-Bilkent/newt/blob/71db0886a1a348da4e9339b034763bc271f9ea1f/app/js/app-menu.js#L644) and the language is not specified. In that case while the pallets looks like the attached the selected language would be "AF" (to reproduce it select an edge from the "AF" palette then choose add node mode from the toolbar, I think that the selected language in mode handler is supposed to be "PD" in this case but it ends up with being "AF") and that would be something problematic.
<img width="279" alt="palette" src="https://user-images.githubusercontent.com/6534865/32973885-266d9266-cbaf-11e7-8e90-b2306b7527f0.png">

I am not sure if it will cause a buggy behavior but it seems highly suspicious. Maybe the one who implemented this feature would better predict if there is any problem or not here.

**Comment by metincansiper** [comment]
I think that anyways keeping selected language for nodes and edges separately would be safer. Also, I need to know the latest state of PD and AF palettes for multiple tabs feature. I can add this fix/improvement (not sure which one it is) to the PR that I will create for multiple tabs support.

**Comment by ugurdogrusoz** [comment]
@kinimesi please comment

**Comment by kinimesi** [comment]
Auto-closed due to keyword. @metincansiper please close if resolved.
