### ISSUE TITLE
Cannot add interaction

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#198]
- Open the first sample
- Try to create a stimulation edge from ca2+ in the middle of muscle cytosol to the association in the upper right of the muscle cytosol. It won't work.
- I can add a stimulation edge from the same simple chemical to the process in the lower right though.

**Comment by kinimesi** [comment]
@ugurdogrusoz according to SBGN specification, stimulation edge cannot be connected to association neither as a source nor as a target. See the first table on page 42: http://co.mbine.org/specifications/sbgn.pd.level-1.version-1.3.pdf

**Comment by ugurdogrusoz** [comment]
Makes sense actually :)
