### ISSUE TITLE
No save confirmation on load

### ISSUE THREAD

**Issue by royludo** [iVis-at-Bilkent/newt#2]
The same modal box as the New menu button should appear when loading another file or when loading a sample.

**Comment by royludo** [comment]
I added a confirmation prompt when loading samples, nothing when loading a file (as there is already the cancelable file picker, in fact). I added a prompt when clicking on File->Save... asking for the filename, and replaced the prompt when clicking on File->New as the behavior was becoming inconsistent (see comments, need to think about that in the future maybe).

**Comment by ugurdogrusoz** [comment]
When to prompt for confirmation (new and change of sample) and when not (load) makes perfect sense. However, I think the warning text is too long. Let's rename it as follows (in both cases):

Old:
You are about to close the map. All unsaved changes will be lost. Do you want to continue ?

New:
All unsaved changes will be lost. Do you want to continue? (notice the delete blank space before "?")

**Comment by royludo** [comment]
Changes done. (the space before the ? is a french typographic convention. Hard to get rid of this kind of habits sometimes)

**Comment by ugurdogrusoz** [comment]
Great. Can we please (slightly) increase the width of the dialog so the whole text fits in one line? This is what I see with Chrome on Windows 10.
![save-confirmation-dialog](https://cloud.githubusercontent.com/assets/3874988/23655300/1dcf2920-033d-11e7-83c7-2cfeaddfa54a.png)
