### ISSUE TITLE
Invalid URI from Pathway Commons

### ISSUE THREAD

**Issue by jvwong** [iVis-at-Bilkent/newt#200]
Query --> Pathway Commons --> By URI  throwing an 'invalid URI' error.

Breaking case: http://identifiers.org/reactome/R-HSA-6803211
'TP53 Regulates Transcription of Death Receptors and Ligands'

**Comment by ugurdogrusoz** [comment]
Expected result: http://www.pathwaycommons.org/pathways/#/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-6803211

**Comment by ugurdogrusoz** [comment]
@jvwong Fix can be confirmed in this daily link: http://www.cs.bilkent.edu.tr/~ivis/Newt_daily/. Please re-open if not fixed.
