### ISSUE TITLE
Perform client-side layout on PC query

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#202]
Since PC service no longer performs layout on query results, we need to perform non-incremental layout on client side.

**Comment by hasanbalci** [comment]
Now performs non-incremental layout on query results.

**Comment by ugurdogrusoz** [comment]
Thanks for adding "Infer Nesting on Load" option to General Map Properties. But I think this option/flag should be considered only upon file load. On PC query, however, we should not infer nesting at all since PC results are complete in regards to nesting anyway (complex members know their complexes and children of a compartment have their compartment refs).
