### ISSUE TITLE
Inconsistency in node-resize grapples in auto-resize mode

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#206]
When "Auto Resize Nodes" is enabled from Grid and Guidelines menu, even though nodes are not resizable anymore, the grapples are drawn as if they are resizable.

**Comment by ugurdogrusoz** [comment]
@kinimesi would fixing this require resize extension depend on grid-guide extension? I am not sure we want to introduce such a dependency just for this. we might prefer to live with this instead...
