### ISSUE TITLE
Zoom to selected and marquee zoom

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#215]
It'd be great to be able to have following zoom functionality as well:

- Add a facility to calculate smallest bounding rectangle of currently selected nodes. Put this in two places:
    o "Zoom > Selected Nodes" under View menu (right after Select submenu)
    o Root context menu with name "Zoom to Selected Nodes" (after "Highlight Selected")

- Add a facility to do marquee zoom (zoom to selected area by left mouse click and drag). We can probably implement this by adding a new tool (in addition to Select / Edit, Add Node, Add Edge tools). When the user is in this mode (clicks on this tool in the toolbar located right after create an interaction tool), a new canvas layer is used to make a selection (similar to marquee selection using Shift/Control/Alt) and upon mouse release zooming to defined area. Could use this as icon in toolbar: https://www.freepik.com/free-icon/zoom_881027.htm

**Comment by hasanbalci** [comment]
In the second option, it is better to switch to the Select/Edit mode automatically after selection is done.

**Comment by hasanbalci** [comment]
I think that it will be better if this functionality is added via cytoscape.js-view-utilities extension.

**Comment by hasanbalci** [comment]
For the first option, naming will be

- "Zoom > Zoom to Selected" instead of "Zoom > Selected Nodes" under the View Menu and
- "Zoom to Selected" instead of "Zoom to Selected Nodes" in the root context menu

**Comment by ugurdogrusoz** [comment]
Great, this looks done! Thanks
