### ISSUE TITLE
Labels not centered on SVG export

### ISSUE THREAD

**Issue by matthiaskoenig** [iVis-at-Bilkent/newt#225]
Hi all,
I just tried to create a small pathway figure for a publication (see attached)

[limax.zip](https://github.com/iVis-at-Bilkent/newt/files/1671173/limax.zip)

When looking at the SVG export all the labels are not centered in the boxes (the png works fine, but I need a vector graphics). So I basically have to reorient all the labels and map in Inkscape/Illustrator. 

The labels must be centered in the boxes on SVG export.
Best Matthias

**Comment by ugurdogrusoz** [comment]
@matthiaskoenig This is what shows on my screen; .png and .svg images look pretty much identical. Am I missing something?
<img width="1280" alt="screen shot 2018-01-28 at 22 23 27" src="https://user-images.githubusercontent.com/3874988/35486103-16fe4df8-047a-11e8-85dc-42fb6d0cf260.png">

**Comment by ugurdogrusoz** [comment]
@matthiaskoenig Closing this. Let me know if I misunderstood your issue.
