### ISSUE TITLE
Updating version of parallelshell

### ISSUE THREAD

**Issue by metincansiper** [iVis-at-Bilkent/newt#226]
After I updated my Node.js version to ```8.2.1``` (and I am using npm version ```5.6.0```)  running ```npm run debug-build``` to run Newt started to throw an error like ```TypeError: "cwd" must be a string```. Then I searched for the reason of the error and saw the following issue (https://github.com/darkguy2008/parallelshell/issues/57). Seems like the version of ```parallelshell``` that is used in Newt is buggy for Node versions later than 8 and the problem is solved in ```parallelshell 3.0.2```. Therefore, upgrading version of ```parallelshell``` to ```3.0.2``` must solve the problem.

**Comment by ugurdogrusoz** [comment]
@metincansiper could you do this please?

**Comment by metincansiper** [comment]
@ugurdogrusoz I updated the version it seems like working now on my computer where the ```node ```version is ```8.2.1```
