### ISSUE TITLE
Reversible reactions

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#229]
Currently reversible reactions are impossible to draw in Newt interactively since a consumption (production) edge can be connected to input (output) port only.
Sometimes we want 2 consumption edges attached to the same process (1 to the input, 1 to the output) in the case of reversible reactions though: http://sbgn.github.io/sbgn/faq/pd#should-i-always-represent-reversible-reactions-as-two-separate-processes (see top drawing here).
We should add support for this to the template under the Edit menu:
  Association
  Dissociation
  Reversible <===
When this is selected. The default # of inputs should be 1 and should be allowed to increase. Same with outputs (both >= 1). The result should be laid out similar to the association / dissociation processes.
Let's discuss when you get a chance.

**Comment by kaansancak** [comment]
Reversible reactions template added. It can be used from edit => add from template => reversible

**Comment by ugurdogrusoz** [comment]
Looks great! I will report some minor issues separately.
