### ISSUE TITLE
Save as image bug

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#235]
Attached model cannot be saved as image (throws an exception)
[o2.sbgnml.txt](https://github.com/iVis-at-Bilkent/newt/files/1774018/o2.sbgnml.txt)

**Comment by ugurdogrusoz** [comment]
bundle.js:264 Xsd validation failed. Errors: Array(26)
success @ bundle.js:264
bundle.js:1550 Uncaught TypeError: Cannot read property '0' of undefined
    at k.drawEdge (bundle.js:1550)
    at k.drawElement (bundle.js:1557)
    at k.drawElements (bundle.js:1557)
    at k.bufferCanvasImage (bundle.js:1609)
    at k.png (bundle.js:1610)
    at f.png (bundle.js:1325)
    at Object.b.saveAsPng (bundle.js:3173)
    at HTMLAnchorElement.<anonymous> (bundle.js:286)
    at HTMLAnchorElement.dispatch (bundle.js:1897)
    at HTMLAnchorElement.g.handle (bundle.js:1894)

**Comment by ahmetcandiroglu** [comment]
I investigated the problem and found out that if an edge (logic arc) has hidden property (given below) it is not recognized by draw-edge function of cytoscape and throws an exception.

 ```
<extension>
    <sbgnviz>
        <hidden/>
    </sbgnviz>
</extension>
```

**Comment by ugurdogrusoz** [comment]
I created the attached model with only two nodes, where one is hidden. I don't have the same problem here?
[save-bug-hidden-node.sbgnml.txt](https://github.com/iVis-at-Bilkent/newt/files/2048061/save-bug-hidden-node.sbgnml.txt)

**Comment by ahmetcandiroglu** [comment]
I did not have a problem either when a node is hidden. It seems only edges cause an exception when hidden.

**Comment by ugurdogrusoz** [comment]
Right, only when edges are hidden, it does cause this exception. Maybe @hasanbalci can help you out with this. If it's a Cytoscape.js bug, we should create an issue under that repo.

**Comment by ahmetcandiroglu** [comment]
It seems to be a Cytoscape.js bug and it is already mentioned here:

https://github.com/cytoscape/cytoscape.js/issues/2096

**Comment by ugurdogrusoz** [comment]
Let's fix this manually without a Cytoscape.js upgrade.

**Comment by ahmetcandiroglu** [comment]
Fixed: https://github.com/iVis-at-Bilkent/cytoscape.js/commit/8c6e6a4d407be9b26f496afc23501e122e08fbaa
