### ISSUE TITLE
Drag and drop into Newt window

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#238]
Drag a file onto the Newt window/tab to load

**Comment by kinimesi** [comment]
Here is an animated GIF of the feature:
![peek 2018-03-08 18-33](https://user-images.githubusercontent.com/7281872/37160250-d67287b8-2300-11e8-8c01-accc253df08a.gif)

**Comment by ugurdogrusoz** [comment]
This is great! Thanks @kinimesi @hasanbalci . Can we perhaps make the border color blue (that we use for highlighting etc.) and make the borders rounded a bit (like the actual borders of the drawing canvas)?
