### ISSUE TITLE
Make simple nodes non-transparent by default

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#239]
Currently all nodes are transparent to a certain degree by default. Let's make only compound nodes (complexes, compartments, and sub-maps) transparent by default; others (simple nodes) non-transparent.

**Comment by amazein** [comment]
Thank you, this is useful. I think this rule should be for all shapes including complexes, compartments and submaps. The motivation is simple: users expect to see diagrams exactly as they draw them, not modified via introducing transparency by default.

**Comment by ugurdogrusoz** [comment]
@amazein Currently we don't expose depth (z-order) of map elements to the user. if we make compounds non-transparent the users might expect to see a particular one on top of the other but they have no way of controlling that. In addition, sometimes certain operations result in overlap of especially compound structures (with other compounds or simple nodes); imposing an arbitrary order of draw in such cases might be annoying tousers. I think we can safely make all non-transparent when we expose drawing order to the user.

**Comment by ugurdogrusoz** [comment]
Needs to be done for the AF nodes as well!
