### ISSUE TITLE
Increase max info box count

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#24]
Currently we only allow 4 info boxes (state variables or units of information), we should allow more (say 8 or 12).

**Comment by ugurdogrusoz** [comment]
May be we could use sides of nodes as well for info boxes, not just top and bottom. Please check if this is ok with SBGN notation.

**Comment by royludo** [comment]
Solved by iVis-at-Bilkent/sbgnviz.js#182
4 infoboxes allowed by side (top and bottom). There is now the possibility to have side-specific limits, just in case. The infoboxes are not relocated anymore when one is added/removed. They stay on their side.

As we discussed, SBGN says infoboxes should be rotated to stay parallel to the side, in case we want to put them on the left or right. Alexander find it as absurd as you and me. For now, if we ever want to use the left/right side the infoboxes will stay horizontal.
