### ISSUE TITLE
Missing state variables

### ISSUE THREAD

**Issue by ozgunbabur** [iVis-at-Bilkent/newt#240]
I am using the public version of Newt, starting with a PC query via the link below.

http://web.newteditor.org/?URI=http://pathwaycommons.org/pc2/BiochemicalReaction_8ed713cfef9205cf25fa4288ad7ba919,http://pathwaycommons.org/pc2/Catalysis_8954d93dd41d0cf1cdb6a4108f5fefe6,http://pathwaycommons.org/pc2/BiochemicalReaction_d56553a610257aa53d2ad19f465be9c5,http://pathwaycommons.org/pc2/Catalysis_daabc522f879ccd3f960ea7d5f918221,http://pathwaycommons.org/pc2/BiochemicalReaction_8e4ecb6c3a0dcd3292a43858e6a3f9df,http://pathwaycommons.org/pc2/Catalysis_304d7af7be11ec67f7c434adca010939,http://pathwaycommons.org/pc2/Catalysis_ed47a2fea6253d66bafd377717d733fc,http://pathwaycommons.org/pc2/BiochemicalReaction_ca2ccb6f52d9816e8aad0c481808d58e,http://pathwaycommons.org/pc2/Catalysis_aa03cbdab3ea63994af055dc8cf8aff3,http://pathwaycommons.org/pc2/BiochemicalReaction_8e4ecb6c3a0dcd3292a43858e6a3f9df,http://pathwaycommons.org/pc2/Catalysis_9389056fc7ccb10d747ef09972433578

The graph shows some of the state variables but not all. If you click on these SRC nodes, you will see that the output SRC molecules are actually phosphorylated. This is displayed among object properties, but not on the graph itself.

Using Chrome on Ubuntu.

**Comment by kinimesi** [comment]
@ozgunbabur state variables are arranged dynamically according to the size of nodes. In this map since the size of node is small, the state variables are not shown. If you increase its size. the state variables will be shown.

**Comment by ozgunbabur** [comment]
I see. I wonder what is the best method to solve this issue. 

We cannot expect users to enlarge the nodes every time to see if there is a modification. It would be nice if there was a graphical sign indicating that there are hidden modifications on the protein.

The node sizes are indicated in the SBGN file coming from PC, right? We can make nodes bigger by modifying BioPAX --> SBGN converter, but then larger graphs will suffer.

Independent from that, I feel the state variables are hidden way too early. As I make the node smaller, the variable gets hidden while there is still more than enough room to draw it.

**Comment by ugurdogrusoz** [comment]
@ozgunbabur Thanks for pointing this out. Correct, the current implementation is far from ideal and will be revised in upcoming releases. We should have at least an indication of hidden infoboxes.

**Comment by kaansancak** [comment]
All state variables can be seen now.
