### ISSUE TITLE
IDs starting with a number on save

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#241]
Pointed out by Tobias:

https://github.com/sbgn/sbgn/wiki/SBGN_ML

The xsd:ID type is an alphanumeric identifier, starting with a letter.

This is probably an issue of associated library but files saved with Newt seems to violate this.

**Comment by ahmetcandiroglu** [comment]
It seems that associated library accepts ids starting with underscore but not with a number. Even though this violates SBGNML constraints it is not mandatory as quoted below so it should not be a problem in my opinion.

> However, this style convention is not mandatory, and IDs should never be interpreted as carrying any meaning.

**Comment by ugurdogrusoz** [comment]
Where is this quote from?

**Comment by ahmetcandiroglu** [comment]
Here at the end of _id of a port_ section:

https://github.com/sbgn/sbgn/wiki/SBGN_ML#port-elements-of-an-arc

**Comment by ugurdogrusoz** [comment]
It says "The xsd:ID type is an alphanumeric identifier, starting with a letter." What's not mandatory is the style of naming "arch4.1", "arch4.2", etc.
Let's change the IDs to be in line with the specification.

**Comment by ugurdogrusoz** [comment]
Cannot reproduce, not sure if this file was actually created strictly by Newt.
