### ISSUE TITLE
Save as image bug 2

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#244]
Another save as image bug. Other is here: https://github.com/iVis-at-Bilkent/newt/issues/235.
Attached model cannot be saved as .png or .jpg (empty file, no exceptions) but it's fine when saved as .svg.
[central_plant_metabolism.sbgn.txt](https://github.com/iVis-at-Bilkent/newt/files/1974334/central_plant_metabolism.sbgn.txt)

**Comment by hasanbalci** [comment]
I think this works but since the image size is too big (~17000*11000 pixels) some image editors cannot open it. If you try to open it with a browser, it works.

**Comment by ahmetcandiroglu** [comment]
I observed that if Google Chrome or Firefox is used, it exports an empty file. However, when Microsoft Edge is used, it exports a big image file of the graph as it should. So, I think this issue is related to the browser.

**Comment by ugurdogrusoz** [comment]
Let's investigate why the empty file

**Comment by ahmetcandiroglu** [comment]
It seems that maximum size of a file that can be exported is different for different browsers/OS. If scale or size of the viewport is too large, then exported png/jpg files may exceed the limit in some browsers causing empty response. This is mentioned in a Cytoscape.js issue as well:

https://github.com/cytoscape/cytoscape.js/issues/1943

**Comment by ahmetcandiroglu** [comment]
This commit should resolve the issue: https://github.com/iVis-at-Bilkent/sbgnviz.js/commit/37813b1e48525d4e05509e8685bef602fdb738d3
