### ISSUE TITLE
Sbgnml to json conversion error

### ISSUE THREAD

**Issue by leonarddrv** [iVis-at-Bilkent/newt#245]
In the menu option Query -> Neighborhood, when the user enters TSC1 an error occurs in sbgnml to json conversion.

**Comment by ugurdogrusoz** [comment]
Awaiting fix with PC service

**Comment by ugurdogrusoz** [comment]
We should consider using this library for conversion: https://github.com/PathwayCommons/sbgnml-to-cytoscape

**Comment by ugurdogrusoz** [comment]
@hasanbalci Can we please verify that this was fixed by PC?

**Comment by hasanbalci** [comment]
@ugurdogrusoz It seems it is working now. I think we can close this issue.
