### ISSUE TITLE
AF support

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#25]
AF support requires new palettes, new node and edge glyphs along with a map "type" that we might let the user to explicitly set or the tool might try to maintain it implicitly.

**Comment by kinimesi** [comment]
Implemented in the following pull requests: https://github.com/iVis-at-Bilkent/newt/pull/88, https://github.com/iVis-at-Bilkent/chise.js/pull/111 and https://github.com/iVis-at-Bilkent/sbgnviz.js/pull/184.
