### ISSUE TITLE
Reconnect an existing edge

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#251]
As most editing tools would allow, we should allow users to re-connect an existing edge (source or target). This should probably be part of edge-bend-editing extension (need to rename the extension I suppose) since it would be something enabled when an edge is selected (similar to bend point markers). Need to discuss and design.

**Comment by ugurdogrusoz** [comment]
Great! Some problems discovered during testing:
- Reconnection diamonds should be transparent so as to not block the edge arrows
- Reconnected consumption and production edges do not attach to process ports (but to the center)

**Comment by ugurdogrusoz** [comment]
Problems noticed:
- in the attached map, the green edge cannot be reconnected to the other / uncertain process to affect it instead. It says invalid but it should be able to affect all types of processes.
[reconnect1.sbgnml.txt](https://github.com/iVis-at-Bilkent/newt/files/2165401/reconnect1.sbgnml.txt)

- if you try to reconnect certain types of edges to a compartment, sometimes reconnection is not performed (as it should be) but no warning is displayed either. For instance, in the above map, try reconnecting either of the consumption edges from their process to the compartment.

**Comment by ahmetcandiroglu** [comment]
We are using a given function (from chise.js) to test validation of edge reconnection. If we add a new edge which also uses the same validator function we get the same invalid edge message. So, it is related to the edge validator function.

The other bug is fixed.

**Comment by ahmetcandiroglu** [comment]
We are using cytoscape.js tap event to get which node to connect the edge. This event may return wrong node (borders may be a bit different than it seems) which leads to inconsistency on edge reconnection.
