### ISSUE TITLE
Resize node to content interactively

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#252]
On a per node basis, probably as part of the node resize facility, we should allow the user to interactively resize a node to fit is content perfectly. The content not only includes label but info boxes as well. We should discuss how we handle compounds.

**Comment by ugurdogrusoz** [comment]
Could use a visual cue like this: https://www.flaticon.com/free-icon/width_764625#term=fit%20size&page=1&position=4

**Comment by ugurdogrusoz** [comment]
When this is available, it makes sense to add this to the menu (Edit > Resize Nodes to Content, in between Delete Selected Smart and Undo, under a new section with separators) so that the user can perform this operation for all nodes. Nodes like process nodes and logical operators do not have any info boxes and user defined labels; so nothing to do with them.

**Comment by ugurdogrusoz** [comment]
Some problems I noticed:
- "Fit Content to Node" -> "Resize Node to Content"
- Missing "Resize Nodes to Content" in the Edit menu as specified originally (which calls this functionality for all nodes in the map)
- Do we not take the left and right info boxes (and their specific widths) into account? For instance, in the below example, the middle node is unnecessarily wide (it doesn't have any left or right info boxes, it should be as wide as the top one). The bottom node, on the other hand, should be wider since the right info box seems to overlap with the label.
![fit-to-content-problems](https://user-images.githubusercontent.com/3874988/41339114-bafa4834-6efc-11e8-8225-475a744334a8.png)
- When infoboxes do not fit and we apply this operation, we have more margin on the right than needed (see bottom info boxes in this example):
![fit-to-content-problems2](https://user-images.githubusercontent.com/3874988/41339712-32ebf260-6efe-11e8-9dab-280533f3ea1a.png)

- Undo is missing
- [leave it for later] Doesn't work for compound nodes

**Comment by ugurdogrusoz** [comment]
@leonarddrv Can you please take care of the first 3 points in the above list and assign it back to me?

**Comment by ugurdogrusoz** [comment]
Thanks @leonarddrv

**Comment by ugurdogrusoz** [comment]
Let's revisit this issue:
- to make sure  it works properly
- to add a visual cue to perform it
Let's talk

**Comment by ugurdogrusoz** [comment]
- create a node
- select it
you get an error immediately

**Comment by ahmetcandiroglu** [comment]
The requested image which is `resizeCue.svg` cannot be reached because relative path converted incorrectly when we use subdomains. 

We want to reach the image at 
http://www.cs.bilkent.edu.tr/~ivis/Newt_daily/node_modules/cytoscape-node-resize/resizeCue.svg
but interpreter converts relative path to 
http://www.cs.bilkent.edu.tr/node_modules/cytoscape-node-resize/resizeCue.svg

(appends relative path `"/node_modules/cytoscape-node-resize/resizeCue.svg"` to domain `http://www.cs.bilkent.edu.tr`)

**Comment by ugurdogrusoz** [comment]
Overall, this function is nicely implemented now. Let's create new issues for remaining specific problems.
