### ISSUE TITLE
Warn user of any errors on CellDesigner export/import

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#259]
When we get an error from the CD2SBGNML conversion service, we should display a dialog signifying this and gracefully return. Title could say "Error" and the explanation could be "Import failed" or "Export failed".

**Comment by ugurdogrusoz** [comment]
Can we display a similar message when the conversion service is not reachable / server is down?

**Comment by gokberkkaraca** [comment]
This issue is solved by displaying "Conversion failed" and "Conversion webservice is not available" messages to the user. I also put a warning message to remind user saving the previous changes when a cell designer file is imported.
