### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#261]
Reported by Irina: Attached model throws an error on load (wheel keeps turning).
[F001-DendriticCell-SBGNv02.sbgn.txt](https://github.com/iVis-at-Bilkent/newt/files/2057955/F001-DendriticCell-SBGNv02.sbgn.txt)

**Comment by gokberkkaraca** [comment]
Resolved by [1fe46898](https://github.com/iVis-at-Bilkent/sbgnviz.js/commit/1fe468980f7af6bb0718149c5606160e87ba9655)
