### ISSUE TITLE
Converting existing processes into reversible ones

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#264]
Let's add a context menu item to process nodes to convert them into reversible reactions. This involves changing any consumption edges (not modulating edges) to production ones, while maintaining their styles (if the original consumption edge is thick, the new production edge should be as thick).

**Comment by ugurdogrusoz** [comment]
Looks great, thanks! I noticed some debugging print outs. Could you get rid of those and close this issue please.

**Comment by gokberkkaraca** [comment]
Debug logs are removed now

**Comment by ugurdogrusoz** [comment]
Let's make this undoable please

**Comment by hasanbalci** [comment]
There is a bug related bend points:

![peek 2018-06-06 11-37](https://user-images.githubusercontent.com/22586369/41026776-0c8be34e-697e-11e8-859b-e16e62bbbd3a.gif)

**Comment by gokberkkaraca** [comment]
This feature is undoable now

**Comment by hasanbalci** [comment]
Converting process nodes into reversible reactions should make the map type "Unknown" as in the case we add reversible templates.

**Comment by gokberkkaraca** [comment]
Map type is set to "Unknown" by 50c4de1.

**Comment by ugurdogrusoz** [comment]
If the Map properties are displayed at the time of this operation, the map type is set to Unknown but the properties won't be updated (stays PD). Can we please update the Map Properties? If not straightforward, one workaround is selecting the process that's converted along with its incident edges, so the focus changes to Object Properties tab.

**Comment by hasanbalci** [comment]
Another error:
- Create a reversible template
- Remove one of the production edges 
- Add a new consumption edge by dragging from process to simple chemical
- Select "Convert into Reversible Reaction"
- Production edge is connected in reverse way

![peek 2018-06-08 17-00](https://user-images.githubusercontent.com/22586369/41162944-06711c22-6b40-11e8-87f6-8e131d821c60.gif)

**Comment by hasanbalci** [comment]
@gokberkkaraca It seems ok now, thanks! 

But there is a minor problem with undo. If we select "Convert into Reversable Reaction", production edge switches to consumption edge. It is ok. However, when we undo, the consumption edge is not connected to the process port anymore, while it was connected to the port initially.

**Comment by gokberkkaraca** [comment]
@hasanbalci an if condition that is added to fix reversible template issue was causing this problem, it should be fixed now

**Comment by hasanbalci** [comment]
It is ok now, I'm closing the issue.
