### ISSUE TITLE
Interactive relocation of info boxes

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#265]
As discussed earlier, let's add a new feature (context menu of nodes that can have info boxes should have a new menu item titled "Relocate Information Boxes") for relocating information boxes. This should work in a separate canvas (not the Cytoscape.js one) and highlight all info boxes of the associated node. Then when the user hits (left-click) an area outside the node and its info boxes, it gets disabled. Otherwise, if the hit point is within the bounds of an info box, then we should consider that info box selected and draw its highlight dashed. If the user drags the mouse we should ghost this info box by drawing a clone of this info box (the same shape as the hit info box) in solid, and this ghost should follow the mouse (or dynamically adjusted to stay on the boundary of the associated node). Only when the mouse is released. we should actually change the location of that info box with the proper API call.

**Comment by kaansancak** [comment]
@ugurdogrusoz info-boxes are interactively relocatable now.

- Select a node. From it's context menu select  _relocate info boxes_ . 
- As long as you select a info box that belongs to selected node, you can change location of info boxes.

**Comment by ugurdogrusoz** [comment]
Looks pretty nice overall. I see several problems though:
- "Relocate Info Boxes" -> "Relocate Information Boxes"
- When in Relocation mode, can we paint the node and all infoboxes differently (only the moved one should be dashed though), so the user knows we're in a different mode?
- Currently we have an auto-adjust behavior on mouse release of the infobox move, which is nice. But can we apply auto-adjustment *only if* released infobox overlaps another one?
- For no particular reason, even though the node is not selected initially, when we are in the relocation mode, it sometimes becomes selected. I think when we enter relocation mode, we should un-select the mode (which is currently done) and also when the node gets selected somehow, we should make sure we disable the relocation mode.
- Sometimes I cannot relocate some infoboxes for no apparent reason (see attached).
- If the node is nested inside a compound, collapse cue gets messed up if you relocate an infobox so that the bounds of the node changes (see attached).
- It's not clear to me when the editing of the infoboxes gets enabled and when it gets disabled. It doesn't behave consistently.

**Comment by kaansancak** [comment]
@ugurdogrusoz 

- Naming fixed
- Color of the node in relocation mode is changed
- Auto-adjusment still remains will be fixed later.
- Some of the other bugs are fixed but some stilll remains. They will be fixed when we can understand how to reproduce them.

**Comment by ugurdogrusoz** [comment]
Moving remaining problems to separate, new issues.

**Comment by ugurdogrusoz** [comment]
Let's leave this major change as a post release improvement to consider please. Closing now.
