### ISSUE TITLE
Error on setting background image

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#266]
I get this each time I try to set the background image for a node. I tried this on Mac using Chrome.
Uncaught TypeError: node.width is not a function
    at Object.draw (bundle.js:138713)
    at Renderer.CRp.drawInscribedImage (bundle.js:58734)
    at Renderer.CRp.drawNode (bundle.js:59311)
    at Renderer.CRp.drawElement (bundle.js:58511)
    at ElementTextureCache.ETCp.getElement (bundle.js:60414)
    at ElementTextureCache.ETCp.dequeue (bundle.js:60638)
    at Object.deq (bundle.js:60657)
    at Object.dequeue [as fn] (bundle.js:61777)
    at beforeRenderCallbacks (bundle.js:58067)
    at renderFn (bundle.js:58084)

**Comment by hasanbalci** [comment]
There is another error when we first set a background image and then enter an invalid URL.

Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.

**Comment by ahmetcandiroglu** [comment]
Fixes : https://github.com/iVis-at-Bilkent/sbgnviz.js/commit/f76ccecf252901705149d8ed1f1899f2298f9719 & https://github.com/iVis-at-Bilkent/cytoscape.js/commit/ef484bf687c870790a7e634b7ee9830bcaecd7a3

**Comment by ugurdogrusoz** [comment]
Please verify the bug you reported is fixed

**Comment by hasanbalci** [comment]
It is not fixed yet.

**Comment by ugurdogrusoz** [comment]
Another error (performed off-campus; might make a difference?):
- Create a node
- Set its background to be http://www.cs.bilkent.edu.tr/ (which is obviously not an image file). You get:
Redirect from 'http://w3.cs.bilkent.edu.tr/' to 'http://w3.cs.bilkent.edu.tr/tr' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.cs.bilkent.edu.tr' is therefore not allowed access.

I also tried https://simgbb.com/images/logo.png, and I get the same (?) error:
Access to Image at 'https://simgbb.com/images/logo.png' from origin 'http://www.cs.bilkent.edu.tr' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.cs.bilkent.edu.tr' is therefore not allowed access.

**Comment by ahmetcandiroglu** [comment]
Invalid file and URL bugs are fixed.

> I also tried https://simgbb.com/images/logo.png, and I get the same (?) error:
Access to Image at 'https://simgbb.com/images/logo.png' from origin 'http://www.cs.bilkent.edu.tr' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.cs.bilkent.edu.tr' is therefore not allowed access.

This will be fixed when the application is deployed. Requesting from localhost causes this error. There is no error when we close Chrome CORS and access to https://simgbb.com/images/logo.png .

**Comment by ugurdogrusoz** [comment]
Let's test this when a RC is available on the server.

**Comment by hasanbalci** [comment]
@ahmetcandiroglu Currently we cannot save a graph that has a node with a background image. It throws error "Uncaught ReferenceError: heigth is not defined".

**Comment by ahmetcandiroglu** [comment]
@hasanbalci It should be fixed now.

**Comment by ugurdogrusoz** [comment]
Persistency problem seems fixed now.

**Comment by hasanbalci** [comment]
@ahmetcandiroglu Saving graph works now, thanks!
