### ISSUE TITLE
Properties UI improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#269]
1) Let's make the button heights(Choose..., Set as Default..., etc.) to be the same as input field height so that when the user clicks to enable image from URL for example, the inspector contents won't move.
2) Let's leave more gap between the button and the checkbox for Image
3) Lets leave a tiny space (not as much as the one in 2) between the checkbox and URL. Also align "URL" to be center (vertical alignment of the "Image", button, checkbox, and "URL" should be the same.
![inspector-impr](https://user-images.githubusercontent.com/3874988/41026899-5bc2105a-697e-11e8-9032-ecc04bbc2376.png)

**Comment by ugurdogrusoz** [comment]
A couple of things:
- Can we make the checkbox for URL a little lower (middle aligned)?
- Can we make the buttons taller (used to be like this actually; I guess we want a solution that works when buttons are still tall. the input file when URL isn't chosen is shorter, but maybe paddings above and below the field could be larger so that it matches the height of the button)?

**Comment by kinimesi** [comment]
auto-closed due to merge into master
