### ISSUE TITLE
Reversible template breaks consumption creation

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#270]
Pointed by @gokberkkaraca. 

After adding a reversible template, if we try to connect a macromolecule to a process by dragging the consumption edge from process to macromolecule, consumption edge is not connected to the input port of the process. Probably, introduced after #260 or #264. 

![peek 2018-06-06 12-12](https://user-images.githubusercontent.com/22586369/41028854-f88cac8e-6982-11e8-9229-f8fb8f184994.gif)

**Comment by kaansancak** [comment]
After #229 we set the map type to unkown, it seems it is not a bug.

**Comment by ugurdogrusoz** [comment]
@kaansancak is right; this is because the map type is unknown. Let's look into and discuss why we don't connect consumption and production edges to the process ports when the map type is unknown.

**Comment by ugurdogrusoz** [comment]
We'll try to fix this through https://github.com/iVis-at-Bilkent/newt/issues/275
