### ISSUE TITLE
Missing points on setting background image

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#277]
- This feature must also support undo-redo operation as other object properties.
- When we clone(copy-paste) a node with a background image, clone operation must include the background image as well (currently background image is missing in the newly created node).

**Comment by hasanbalci** [comment]
Clone feature is still not working if we try to clone from Edit -> Clone Selected.

**Comment by ugurdogrusoz** [comment]
@ahmetcandiroglu isn't clone using the same code basis as copy-paste? if not, can we make them so?

**Comment by ahmetcandiroglu** [comment]
@ugurdogrusoz They seem to use the same code. However, should not clone function paste elements near the selected elements not at the cursor location?

**Comment by ugurdogrusoz** [comment]
Sure, that is the only difference though

**Comment by ugurdogrusoz** [comment]
Clone works nicely with background images but what happened to the recent feature to paste at mouse location (when you copy and then paste, it used to paste at the current mouse location)?

**Comment by ahmetcandiroglu** [comment]
Are you sure it is broken because I did not change copy-paste functionality and it seems to work?
