### ISSUE TITLE
Prepare test plan for 1.1

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#279]
Need to prepare a test plan for version 1.1 (update the one for 1.0, making sure post 1.0 features get more attention). New features in 1.1 can be identified from milestone 1.1 description and issues marked as 1.1.

**Comment by ugurdogrusoz** [comment]
Update this tutorial as well (make sure it's compatible with 1.1): https://docs.google.com/document/d/106H-kbqftnnlYVNum16u-_3FL937BV5X0MqgQ7iPG1U/edit?usp=sharing

**Comment by leonarddrv** [comment]
[Netw 1.1 Test Coverage](https://docs.google.com/document/d/1JP80Sld7oQISFcdEdI79u5sfoLLqeq5fVRv4GOZIJlQ/edit#heading=h.9z18mkdayxfk)
[Netw 1.1 Test Plan](https://docs.google.com/spreadsheets/d/1OsAcZpvBPfxzY57oA73U1jUx0kAcOd5G1-OQsfc3tnw/edit#gid=0)
