### ISSUE TITLE
Inspectors of different tabs must be independent from each other

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#286]
For example, if object properties of a node in a pathway is displayed in the inspector and we switch to a different tab(pathway), the object properties of the node we previously displayed continue to appear in the inspector. 
I think current view of the inspector must change according to the tab(pathway) that we are currently on and must display the state where we left on that tab(pathway).

**Comment by metincansiper** [comment]
Please see #294

**Comment by hasanbalci** [comment]
Thanks Metin!
