### ISSUE TITLE
Set as default should also include background image 

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#287]
Currently when we add a background image to a node and click on "Set as Default for ...", newly created nodes do not start with the background image.

**Comment by hasanbalci** [comment]
It seems working.

**Comment by ugurdogrusoz** [comment]
We have this problem:
- set background image of a node and set is as default for that type of node
- load a random sample. notice how nodes in this sample of that type all have this background image. this is not the case if you load a file from disk into this tab, however.
