### ISSUE TITLE
Error on undoing remove of an image

### ISSUE THREAD

**Issue by leonarddrv** [iVis-at-Bilkent/newt#288]
An error occurs when undoing change of the image.
- Create a macromolecule
- Add a background image
- Replace image with another one
- Delete background image
- Undo deletion
- Undo again

**Comment by ahmetcandiroglu** [comment]
These commits also resolved this issue https://github.com/iVis-at-Bilkent/newt/commit/4480bf77d8f3decbfe3ea149f56852ae30211a03, https://github.com/iVis-at-Bilkent/sbgnviz.js/commit/8fcad6b96b28673d12f8042540584914245afef1, https://github.com/iVis-at-Bilkent/chise.js/commit/cc449ebbd5e54baa36469f71b491c4ce551052b9

**Comment by ugurdogrusoz** [comment]
@leonarddrv please verify

**Comment by leonarddrv** [comment]
The bug seems to be resolved by those commits.
