### ISSUE TITLE
Infobox relocation problem on compound nodes

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#289]
If we set "Allow Compound Resize" from map properties and resize a compound node with infoboxes, then the relocation of the infoboxes does not work properly. An example result is:

![sample](https://user-images.githubusercontent.com/22586369/41298760-a1ac11c4-6e6a-11e8-873c-2f819db8fcb2.png)

**Comment by hasanbalci** [comment]
I noticed that relocation of infoboxes does not work properly on compound nodes independent from "Allow Compound Resize" if they have child node.

**Comment by ugurdogrusoz** [comment]
Looks like compound margins aren't taken into account at all.

**Comment by kaansancak** [comment]
It is fixed by https://github.com/iVis-at-Bilkent/newt/commit/a621a5f1b71e37a90cdee98973726c89651d4a85.
