### ISSUE TITLE
Error after infobox relocation

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#291]
If we relocate an infobox and then open a new sample file without clicking anywhere in between, the sample file cannot be loaded properly and when we click on somewhere it throws error. This does not happen if we click somewhere after relocation of the infobox.

I think this is because the relocation waits for another click to complete its operation for some reason.

**Comment by kaansancak** [comment]
It should be fixed now. Can you check it and verified that it is solved.

**Comment by hasanbalci** [comment]
It is fixed now but there is another minor problem. If we relocate an infobox and then try to move another node by dragging from its infobox, we cannot move it. I think we cannot quit from the relocation mode when we click on an infobox in another node.

**Comment by kaansancak** [comment]
@hasanbalci it should be fixed now. Can you verify and close?
