### ISSUE TITLE
Information boxes not loaded properly after save

### ISSUE THREAD

**Issue by kaansancak** [iVis-at-Bilkent/newt#296]
- Create a new node
- Add info boxes
- Resize the node, make it smaller until info boxes overlaps.
- Save the graph and load it again.
- Graph is not loaded properly.
To solve this bug, on file load, we should call functions in #240 for nodes which have info-boxes.

**Comment by ugurdogrusoz** [comment]
Why can't info boxes overlap? I think that shouldn't be a problem. However after certain operations we might prefer to tidy them and get rid of the overlaps but that is not to say they cannot overlap, especially when they are saved like that in a file.

**Comment by kaansancak** [comment]
@ugurdogrusoz it should be fixed now.
