### ISSUE TITLE
Ports messed up when a process with hidden ports becomes reversible

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#297]
Reported by @kaansancak :
- Open "polyq ..." from samples [process ports are not shown in this map]
- Make a process reversible
- Now turn ports on (Map > Enable Ports or select process and change its orientation to left-to-right)
Notice how all three edges connect to the same port. Originally two are connected to one, the third to the other port. This doesn't happen if you enable ports from the beginning.

**Comment by kaansancak** [comment]
This won't be fixed.
