### ISSUE TITLE
Change highlight color

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#30]
Current highlight color (dark gray) is confusing especially since default compartment borders are also gray and thick. I suggest we find a different color to highlight nodes-edges upon highlight (see Highlight menu) operations. A good candidate is the blue we use outside the canvas in menus, dialogs, etc. Notice that we should make sure to change the color of edge arrows as well.

**Comment by royludo** [comment]
I also slightly reduced the width (3->2) With the color, I found it a bit too much of a highlight.
