### ISSUE TITLE
Save images under map extension not glyph extensions

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#308]
Let's try to save images under map extension, rather than glyph extensions, so that common ones are not redundantly persisted. This will require checking for duplication during save.

**Comment by ahmetcandiroglu** [comment]
Changed libsbgn.js also https://github.com/sbgn/libsbgn.js/commit/cf757d4b8313e192224492bd13f2aa4a23117ae3

**Comment by hasanbalci** [comment]
I tested this feature and couldn't find any bug for now.

**Comment by ugurdogrusoz** [comment]
It looks fine to me as well.
