### ISSUE TITLE
Selected node border width independent of actual border width

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#309]
Can we make selection behave as follows. When a node is selected, its border is in selection color (orange) and the width is a constant value (say 3.0) independent of the node's actual border width? Especially with images now, if one uses a background image for a node, they will like to make the border width zero. Then, unfortunately the user cannot see the selection status of that node.

**Comment by ugurdogrusoz** [comment]
Yes this is done as intended. A minor improvement suggestion: how about when selected, the border of the node is min(selection width, node's current width)? If not straightforward, just ignore please.

**Comment by hasanbalci** [comment]
Do you mean max(selection width, node's current width)? Because if we use minimum, then if node's current width is 0, then border width will also be zero when selected, which we don't want it to be.

**Comment by ugurdogrusoz** [comment]
Yes I meant max :)

**Comment by kinimesi** [comment]
auto-closed due to merge into master
