### ISSUE TITLE
Edge bend point bugs

### ISSUE THREAD

**Issue by royludo** [iVis-at-Bilkent/newt#31]
When an edge with a bend point is involved, all the following actions generate a stacktrace:
 - copy/pasting that edge
 - adding a compound via Edit > Add Complex/Compartment menu around a node linked to this edge
 - changing parents for a node linked to this edge

**Comment by kinimesi** [comment]
@royludo should be fixed by https://github.com/iVis-at-Bilkent/cytoscape.js-edge-bend-editing/commit/d514a0030c46aed4cf4752fceb9f0b429965debe Can you verify and close?
