### ISSUE TITLE
Collapse cue messed up as infoboxes get relocated

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#310]
If the node is nested inside a compound, collapse cue gets messed up if you relocate an infobox so that the bounds of the node changes as below.
To reproduce:
- create a compartment with a single macromolecule in it
- create an infobox for the macromolecule with a long label like "abcde"
- move the macromolecule to left side, and then back to top side, and so on.
![collapse-cue-refresh-problem-on-infobox-relocation](https://user-images.githubusercontent.com/3874988/41277731-b3889c6c-6e30-11e8-9d77-f6864a1e58ee.png)

**Comment by kaansancak** [comment]
It is fixed by https://github.com/iVis-at-Bilkent/newt/commit/7e12bd30e52d2fb45f4d88c212972edd719325e2 . Also maximum information box size increased to 6 characters by https://github.com/iVis-at-Bilkent/chise.js/commit/bc20a5ad7727b43b85158fd4b8f77b228ce46d52 .
