### ISSUE TITLE
Infoboxes are mislocated on collapsed nodes

### ISSUE THREAD

**Issue by kinimesi** [iVis-at-Bilkent/newt#313]
See the images below:

## Before collapse:
![screenshot_20180615_182953](https://user-images.githubusercontent.com/7281872/41476570-9e31ba50-70ca-11e8-9cba-f8ab0483d71e.png)
## After collapse:
![screenshot_20180615_183030](https://user-images.githubusercontent.com/7281872/41476590-b16dfbd8-70ca-11e8-9f2f-a0f9b0f828ad.png)

**Comment by kaansancak** [comment]
This will be fixed after revert of https://github.com/iVis-at-Bilkent/sbgnviz.js/commit/d1863efd8387cbb6ea44af584e95d9062cbb570f .

**Comment by ugurdogrusoz** [comment]
Revert doesn't seem to have helped.

**Comment by ugurdogrusoz** [comment]
It is still there I think. Take the first sample and add 4-5 info boxes to the left-most compartment and collapse.

**Comment by kinimesi** [comment]
Still not fixed for the following case:
- Uncheck `Recalculate Layout on Complexity Management`
- Repeat the steps described in the issue above.

**Comment by kaansancak** [comment]
@kinimesi I tried to reproduce the bug as you described but I could not produce it. I also tried on daily newt. Can you check it again?
My steps:

- Create a compartment
- Add a child to compartment
- Add 5 info boxes to compartent
- Collapse and expand

**Comment by kinimesi** [comment]
@kaansancak the GIF below is from daily build which is up to date.
![8eivlcaxmv](https://user-images.githubusercontent.com/7281872/41566770-b2477762-7365-11e8-90ce-0e54160bf584.gif)
