### ISSUE TITLE
Style problems on infobox relocation

### ISSUE THREAD

**Issue by kinimesi** [iVis-at-Bilkent/newt#314]
Normally the border of collapsed nodes and their infoboxes are dashed. But in the daily build the borders of infoboxes are solid.

## on public release:
<img src="https://user-images.githubusercontent.com/7281872/41476988-bb8efbd4-70cb-11e8-980d-7baac38c7786.png" width="200px" height="200px">

## on daily build:

![screenshot_20180615_184047](https://user-images.githubusercontent.com/7281872/41477101-024feb96-70cc-11e8-9790-dd20d8e69137.png)

**Comment by ugurdogrusoz** [comment]
Another style problem is the following. When we're in relocation mode and the node border becomes orange, if you immediately save a map *before* ending the relocation mode, the node is persisted with orange borders (which you can verify by loading it back).

**Comment by ugurdogrusoz** [comment]
@kaansancak I confirm that color problem is gone.
