### ISSUE TITLE
PC beta vs PC public

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#315]
I changed the PC query URL to the beta version the other day. Please evaluate whether the beta behaves better (and has some of the issues we reported fixed as claimed) and decide whether to keep the beta or point back to the public PC service.

**Comment by leonarddrv** [comment]
@ugurdogrusoz  Common stream query seems to be working fine now, but Neighborhood querying takes forever to display its content. I think it is because of the info-box rendering.

**Comment by ugurdogrusoz** [comment]
@leonarddrv Can you elaborate how info-box rendering is a problem? Do we get an error? Can you please talk to @kaansancak about this tomorrow?

**Comment by leonarddrv** [comment]
We don't get an error but when I tried to load neighborhood of TSC1 without rendering info boxes it was displayed relatively in a short time. Anyway I will talk with Kaan and investigate it further.

**Comment by leonarddrv** [comment]
Common Stream is using PC beta version since PC public version was not displaying anything.
For all the others PC public version is used.
Note: Regarding Neighborhood query, in public version it had a bug (addition of infoboxes for 'OR' nodes) while in Beta version it was not displaying anything.

**Comment by ugurdogrusoz** [comment]
Let's reinvestigate this after 1.1 release.

**Comment by ugurdogrusoz** [comment]
@hasanbalci Could you please check where we point for PC queries currently in unstable branch? If I remember correctly, each query was specifying its own server, so some queries might be pointing to a different server than others.

**Comment by hasanbalci** [comment]
@ugurdogrusoz Currently, all five query types use the public PC service. I tried each of them with a few sample queries and they seem to work. I didn't get any error, but a more comprehensive test may be good.
