### ISSUE TITLE
Background image shown inside ports

### ISSUE THREAD

**Issue by kinimesi** [iVis-at-Bilkent/newt#316]
Reproduce: add a background image to any node which has a port.

![screen shot 2018-06-18 at 00 58 11](https://user-images.githubusercontent.com/7281872/41512567-3cfd4a04-7293-11e8-8c84-3a12ba4d2570.png)

**Comment by ugurdogrusoz** [comment]
There is no easy fix for this since processes with ports are implemented with polygons spanning ports, hence this behavior. Let a not do anything about this at the moment.
