### ISSUE TITLE
Error on menu operations after enabling infobox relocation

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#319]
After enabling relocation mode, some menu operations throw error. A sample case:
- Create a complex and add a macromolecule inside of it

- Add an infobox to macromolecule and activate relocation of infoboxes on macromolecule

- Then click on "View -> Collapse/Expand -> Collapse All" from the menubar

- When you click on anywhere, it throws error

Similarly, after the second step in the above sample (enabling relocation of infoboxes)

- Click on "View -> Select -> All Nodes" from the menubar

- Then click on "Edit -> Delete Selected Simple" from the menubar

- When you click on anywhere, it throws error

**Comment by ugurdogrusoz** [comment]
There was a related issue. We need to do a better job disabling relocation mode.

**Comment by hasanbalci** [comment]
It seems working now, thanks!
