### ISSUE TITLE
Problems with undo of compounds

### ISSUE THREAD

**Issue by royludo** [iVis-at-Bilkent/newt#32]
Bug works with both compartments and complexes.
Select a compound (let's call it C1) with subunits inside. Edit > Add a compound. This creates C2 with C1 inside.
Undo this action. C2 disappears as expected, but the subunits inside C1 disappear.
Redo it. C2 reappears with the subunits.
Undo it again. This time only C2 disappears and the subunits behave normally.

**Comment by leonarddrv** [comment]
@royludo Can you recheck if the bug is still present in ChiSE_daily?
