### ISSUE TITLE
Edge bend point reappears on editing after layout

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#320]
- Create a process with proper input/output.
- Create a bend point for one of the edges in this process.
- Perform layout (cannot handle and gets rid of any edge bends).
- Now try to edit this edge by first selecting it. Notice how the bend points before layout re-appear!

Was there in 1.0 as well.

**Comment by hasanbalci** [comment]
It seems ok, thanks!
