### ISSUE TITLE
Compound size export problem

### ISSUE THREAD

**Issue by Adrienrougny** [iVis-at-Bilkent/newt#328]
When drawn with the "Edit -> Add complex/compartment for selected" feature, the size of complexes/compartments are not well exported into SBGN-ML (bboxes).
It looks like the extraComplexPadding/extraCompartmentPadding properties are not taken into account for the export.

**Comment by Adrienrougny** [comment]
@ugurdogrusoz Attached is an SBGN-ML file example (I replaced the .sbgn extenstion to .txt so it can be attached) that was generated using newt. I just drew two subunits and added a complex around them using the "Edit->Add complex for Selected". It is nicely rendered with newt: there is space between the subunits and the complex. This space disappears when rendering it with SBGN-ED or SBGNTikZ, for example.
The problem seems to be in the export of the bbox of the complex (it is too small).
My two cents, it might be that the compoundPadding property (and not the other two properties as I said before, my mistake) is not taken into account when measuring the bbox of the complex for the SBGN-ML export (but the compoundPadding is correctly set in the mapProperties element in the extension, so the file would be correctly rendered in newt when re-loading it).
[complex.txt](https://github.com/iVis-at-Bilkent/newt/files/2135965/complex.txt)

**Comment by ugurdogrusoz** [comment]
@Adrienrougny Could you please test compound padding issues you reported with our [latest build](http://ivis.cs.bilkent.edu.tr/)?

**Comment by Adrienrougny** [comment]
The issue is solved with the latest build.
