### ISSUE TITLE
Expose label font color

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#330]
We currently do not expose label font colors to the user. We should do so under Font Properties dialog as follows:
- Rename fields to exclude "Font" redundantly. E.g. "Font Family" -> "Family".
- Add a new field named Color at the end (right after Type). Make sure it has the same style and dimensions as Border and Fill Color. Also make sure font color is part of the Default for new nodes.

**Comment by kaansancak** [comment]
@ugurdogrusoz Label font color is exposed now.
