### ISSUE TITLE
Infobox problems with AF maps

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#332]
- Unit of information problem with AF nodes (create a BA Simple Chemical and set the infobox string to "a"):
![new_file 14](https://user-images.githubusercontent.com/3874988/42025164-9790eed0-7acc-11e8-89c2-ade384c73cea.png)
- Changing the infobox label of a node in an AF map affects the size of the infobox labels of other nodes (create two nodes with infoboxes, set the string of one, and then the other to a different length).

**Comment by kaansancak** [comment]
@ugurdogrusoz Bugs should be fixed. Can you verify?
