### ISSUE TITLE
Feedback on incompatible edge creation

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#334]
Currently when the user tries to create an edge that doesn't belong with the selected source and target and the map type, we ignore the request but don't display any warnings. We should display a generic dialog with title "Error" that says "Invalid edge type!" with a single "OK" button.
This applies to those attempts when re-connecting an existing edge.

**Comment by ugurdogrusoz** [comment]
Can we please put both sentences on one line?

**Comment by ahmetcandiroglu** [comment]
It looks like below, should I change it anyway?

![image](https://user-images.githubusercontent.com/24222568/42043625-93a4a52c-7aff-11e8-8a2e-24ad807f6751.png)
