### ISSUE TITLE
Order of fields in dialogs using tabs

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#335]
Use of tabs to move from one field to the consecutive one is quite useful. Looks like we lost this ordering in some dialogs (was previously done by @leonarddrv), should restore it. Also make sure the last field in a dialog is followed by the first one forming a circle if possible (see Layout Properties as a non-working example). Includes:
- properties tabs and the palette
- settings dialogs

**Comment by nasimsaleh** [comment]
the tab key moves though "input" fields. It won't go back to the first input field after the last one.
