### ISSUE TITLE
Missing information boxes on load

### ISSUE THREAD

**Issue by kaansancak** [iVis-at-Bilkent/newt#339]
During load of compartments, information-boxes are not loaded properly. Probably, this is a conversion bug from sbgml to json.

**Comment by hasanbalci** [comment]
@kaansancak Currently, infoboxes are not loaded properly. For example, create a macromolecule with infoboxes. Then save and load the map again, infoboxes are not in correct positions.

**Comment by hasanbalci** [comment]
I think it still doesn't work correctly. For example, add a compartment and a macromolecule inside of it. Then add infobox to both nodes. Then save and load, the infobox positioning of the compartment is not correct.

**Comment by ugurdogrusoz** [comment]
I confirm this latest issue from @hasanbalci

**Comment by kaansancak** [comment]
@ugurdogrusoz @hasanbalci latest issue probably depended on #328, hopefully this issue is fixed now.

**Comment by ugurdogrusoz** [comment]
Created and saved this:
![new_file 18](https://user-images.githubusercontent.com/3874988/42376160-d114664a-8126-11e8-9d78-08b8e356f7b8.png)

[infobox-load-problem.sbgnml.txt](https://github.com/iVis-at-Bilkent/newt/files/2170250/infobox-load-problem.sbgnml.txt)

Got this on load:
![new_file 15 1](https://user-images.githubusercontent.com/3874988/42376179-e3d438aa-8126-11e8-9661-e789cadc9742.png)

See how one of the info boxes moved to an incorrect location.

**Comment by kaansancak** [comment]
@ugurdogrusoz @hasanbalci Apart from the query bug which is moved to #348, can you confirm that this issue is solved?

**Comment by ugurdogrusoz** [comment]
See the misfolded protein complex in the attached map. This loads properly with public Newt but not on daily.
[infobox-load-problem2.sbgnml.txt](https://github.com/iVis-at-Bilkent/newt/files/2175329/infobox-load-problem2.sbgnml.txt)
On daily we get:
![infobox-load-problem2](https://user-images.githubusercontent.com/3874988/42440047-29bd4b3e-836d-11e8-9c2d-f6f69160a537.png)
