### ISSUE TITLE
Language field of edges undefined when added from template

### ISSUE THREAD

**Issue by ahmetcandiroglu** [iVis-at-Bilkent/newt#341]
Edges have language data field and it may have 3 values: 'PD', 'AF' and 'Unknown'. However, when they are created by 'Add from Template' or convenient process edge creation feature, language type of created edges are set to _undefined_. 

`edge.data('language') = undefined`

**Comment by hasanbalci** [comment]
Not only edges but also nodes added from template and the compounds that are added from "Edit -> Add ... for Selected" had language field as _undefined_.  Now, both nodes and edges should have language fields set correctly with the above commits,

**Comment by ahmetcandiroglu** [comment]
It seems to work, thanks!
