### ISSUE TITLE
Update CellDesigner conversion service

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#343]
@royludo fixed a bug in the converter (regarding the compartment of processes), we should make sure the service has this fixed.

**Comment by ugurdogrusoz** [comment]
@canbax Can you please find out whether or not we're using the latest of [the associated library - this one?](https://github.com/royludo/cd2sbgnml) here?

**Comment by canbax** [comment]
I checked the path `/home/newtserver/cd2sbgnml-webservice` inside the machine **newtserver**. It seems like the library is not updated.

In the related google docs document about this machine it says. "After a reboot, both services shall start automatically without any user intervention." 

**but** when I checked crontab I see nothing. If this machine does not use anything other than crontab to update/restart the server, it is not updating for months. Also there is no any running server on http://web.newteditor.org:8080

**Comment by ugurdogrusoz** [comment]
@canbax I already know that our deployment on the public Newt server is *not* updated automatically. https://github.com/royludo/cd2sbgnml is not a repository that's being worked on though. So, the question is that is the current service running on this machine the latest of the associated library? Did you verify that it's not? If so, how behind (how many commits) are we behind?
After a reboot, this service *does* start automatically. In fact, we rebooted this machine today and it's working now.

**Comment by canbax** [comment]
It seems like the service on newtserver is running code of this repository https://github.com/gokberkkaraca/cd2sbgnml-webservice. This is fork of another repository
https://github.com/royludo/cd2sbgnml-webservice. These are different than the mentioned https://github.com/royludo/cd2sbgnml.

The latest commit of https://github.com/gokberkkaraca/cd2sbgnml-webservice dates back to **31 May 2018**.

The latest commit of https://github.com/royludo/cd2sbgnml dates back to **31 Oct 2018**. So our source code is not using latest version.

**Comment by ugurdogrusoz** [comment]
Let's try to update the service on Public Newt machine to use the latest. That probably includes the following steps:
- Create a jar with the latest in https://github.com/royludo/cd2sbgnml and update the one in the related directory of https://github.com/gokberkkaraca/cd2sbgnml-webservice.
- Rebuild CD2SBGNML service in public Newt machine as described in the associated document.

**Comment by canbax** [comment]
"Export>CellDesigner File" fails for some samples: "CaM-CaMK dependent signaling to nucleus", "Insulin-like growth factor (IGF) signaling", "PolyQ proteins interferencePolyQ proteins interference", "MAPK cascade". The rest of the samples in PD worked fine

**Comment by ugurdogrusoz** [comment]
Import?

**Comment by canbax** [comment]
I tried to import some example files inside google drive folder CD. The service is able to import all of them successfully. But when I try to export the imported file most of them failed. I map them to 0 if it failed 1 otherwise.

components44.xml		-> 0
database44.xml		-> 0
ex1.xml				-> 1
M_Phase.xml			-> 0
M_Phase2.xml			-> 0
Macros.xml			-> 0
MAPK.xml			-> 0
MAPK42.xml			-> 0
M-Phase.xml			-> 0
M-Phase2.xml			-> 0
SBGNRefCard.xml		-> 1
sim1.xml				-> 1
sim2.xml				-> 1
unitOfInformation.xml	-> 1

**Comment by ugurdogrusoz** [comment]
This repository is now under iVis-at-Bilkent. You should be able to push the updated jar to it.
Then, make sure latest code and jar are both *unstable* and *master* branches.

**Comment by ugurdogrusoz** [comment]
Why don't we remove the older version of the jar (in both branches)?

**Comment by canbax** [comment]
I deleted old jars with https://github.com/iVis-at-Bilkent/cd2sbgnml-webservice/commit/07dc8d6457b8390e37087b6783fb7b64c08685a9
