### ISSUE TITLE
ivis.bilkent.edu.tr as internal server

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#358]
Let's set up ilkin's old machine as an internal server for mainly hosting daily Newt builds.
We should reset the machine and start from scratch.
We should also set up necessary tasks for 3-4 times updating the daily Newt build.
Ask me for the IP address if needed.

**Comment by ahmetcandiroglu** [comment]
The server is all set and running on [ivis.cs.bilkent.edu.tr](url)

Now we can set up necessary build scripts.

**Comment by ugurdogrusoz** [comment]
https://www.howtogeek.com/101288/how-to-schedule-tasks-on-linux-an-introduction-to-crontab-files/

Using something like above, can we please schedule regular daily updates to the deployment here?
@ 4am, 12:35pm, 3:30pm, and 7pm (4 times a day) perhaps?

**Comment by ugurdogrusoz** [comment]
Can we change the URL as http://ivis.cs.bilkent.edu.tr/Newt_daily ?

**Comment by ahmetcandiroglu** [comment]
Regular daily updates are scheduled as you suggested @ugurdogrusoz

**Comment by ugurdogrusoz** [comment]
@ahmetcandiroglu Please complete the instructions in the document I shared with you earlier.
