### ISSUE TITLE
Resize node to content problems

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#362]
- ~~We should unselect the node upon completing the action~~
- ~~Location and size of the visual cue is a bit puzzling, it seems to be calculated differently at varying zoom levels. Let's discuss.~~
- ~~Let's make the arrows in the visual cue non-transparent (let me know if you need help with this).~~
- ~~As soon as we select a node, we get the following error:
jquery.js:9601 GET http://www.cs.bilkent.edu.tr/utilities/testURL?url=http%3A%2F%2Fwww.pathwaycommons.org%2Fbiogene%2Fretrieve.do&qs%5Borg%5D=human&qs%5Bformat%5D=json 404 (Not Found)
send @ jquery.js:9601
ajax @ jquery.js:9207
fillBioGeneContainer @ fill-biogene-container.js:42
inspectorUtilities.handleSBGNInspector @ inspector-utilities.js:498
(anonymous) @ app-cy.js:1102
(anonymous) @ underscore.js:805
(anonymous) @ app-cy.js:1109
triggerImpl @ define.js:533
triggerImpl @ define.js:557
(anonymous) @ switch-functions.js:52
mouseupHandler @ load-listeners.js:942
fill-biogene-container.js:63 Uncaught ReferenceError: error is not defined
    at Object.error (fill-biogene-container.js:63)
    at fire (jquery.js:3269)
    at Object.fireWith [as rejectWith] (jquery.js:3399)
    at done (jquery.js:9308)
    at XMLHttpRequest.<anonymous> (jquery.js:9549)~~

**Comment by ahmetcandiroglu** [comment]
The last one is not related with the resize cue, it is related with this issue #347

**Comment by ugurdogrusoz** [comment]
@kaansancak Can we unselect the node upon completion of the Resize node to content operation?

**Comment by kaansancak** [comment]
@ugurdogrusoz this is already handled by @ahmetcandiroglu  via https://github.com/iVis-at-Bilkent/chise.js/commit/4a266530a226b1388a66969025198bb208362a39

**Comment by ugurdogrusoz** [comment]
Remaining issues (@ahmetcandiroglu):
- Visual cue should appear only when applicable (see where we have "Resize node to content" as a node menu item)

Remaining issue (@kaansancak): 
- For simple nodes

**Comment by kaansancak** [comment]
@ugurdogrusoz since the remaining issue is also mentioned at #354, we can close this issue.
