### ISSUE TITLE
Inconsistent rendering problem

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#363]
The unit of information in the attached map is drawn a little above it normally is (shifted a bit up) when it is **selected**.
![relocate3 sbgnml](https://user-images.githubusercontent.com/3874988/42754434-27fdec64-88fd-11e8-8cc9-5526b7dbc83e.png)
[relocate3.sbgnml.txt](https://github.com/iVis-at-Bilkent/newt/files/2197282/relocate3.sbgnml.txt)

**Comment by kaansancak** [comment]
When a node is selected, we increase the border-width if node is not thick enough, this causes infoboxes to be drawn differently for a moment. This won't be fixed.
