### ISSUE TITLE
Should we bypass quick tutorials on launch with URL/URI?

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#364]

**Comment by hasanbalci** [comment]
@ugurdogrusoz Do we want the user to see the quick tutorial if he/she opens the app without URL/URI later. In other words, if the user launches the app with URL/URI for the first time, do we need to set the cookie to not show the quick tutorials in later launches?

**Comment by ugurdogrusoz** [comment]
Yes, I think the user should see the quick tutorial when Newt is launched without URL/URI.
