### ISSUE TITLE
Multimer background image problem

### ISSUE THREAD

**Issue by metincansiper** [iVis-at-Bilkent/newt#373]
The multimer layers of nodes does not have background image. The problem is visible in public unstable but not in master. Minimum steps to reproduce:

- Load neuronal_muscle_signaling
- Select a macromolecule and made it multimer

The following is the result:

<img width="58" alt="screen shot 2018-07-24 at 2 44 03 pm" src="https://user-images.githubusercontent.com/6534865/43167874-1e93463e-8f50-11e8-9dd1-eaf82d4c35f2.png">

**Comment by ugurdogrusoz** [comment]
@ahmetcandiroglu Could we perhaps render the same image twice? Just like the shape itself?

**Comment by ahmetcandiroglu** [comment]
Yes we can do that but if we don't want it for every background image we should specify a new data field (e.g. ´node.data('hasGradient') = true´ )

**Comment by ugurdogrusoz** [comment]
I suggest we paint the bottom copy *solid* using a an *average color* from the background image in the upper copy (only for nodes with background images). This should be done at sbgnviz level I suppose.

**Comment by metincansiper** [comment]
This feature works fine in http://web.newteditor.org/

**Comment by ugurdogrusoz** [comment]
@metincansiper that was before 3d and gradient color schemes were introduced. We can and do paint the bottom shape's background now as well (white).

**Comment by ugurdogrusoz** [comment]
I don't know why I said we do paint the bottom copy as well but it's clearly not painted and stays white.

**Comment by ugurdogrusoz** [comment]
Looks like this is related to 3D and gradient Color Schemes. These type of color schemes use background images which covers the fill color of a node but in case of multimers fill colors could be used for bottom copy. Color schemes should not set the fill color of a node in case of 3D and gradient color schemes.
