### ISSUE TITLE
New node background images not rendered until clicked

### ISSUE THREAD

**Issue by metincansiper** [iVis-at-Bilkent/newt#374]
This bug must be appeared after #372.  I will look into it but would be useful to hear if anyone has an idea of why this would be happening.

Min steps to reproduce:

- Load neuronal_muscle_signaling
- Add a new macromolecule then you will have a macromolecule with white background
- Click on the new macromolecule then its background will be updated as it should be

**Comment by ugurdogrusoz** [comment]
We have default style in sbgnviz level and also defaults (see Set as Default for ... in the Newt inspector). Are we perhaps bypassing the defaults in the Newt inspector on initial creation? @dorukcakmakci might be able to comment on this?

**Comment by metincansiper** [comment]
I believe that set as default in Newt is updating the defaults in sbgnviz if there is no specific bug or misbehavior. I think that this problem is not about about setting the defaults. The new node already have the expected background image upon creation. However, it must be a rendering issue. The background image is not rendered until the node is clicked.

**Comment by ugurdogrusoz** [comment]
@metincansiper please verify it's fixed. looks good to me.

**Comment by metincansiper** [comment]
Looks like fixed, closing the issue.
