### ISSUE TITLE
Reversible reaction from template not working properly

### ISSUE THREAD

**Issue by dorukcakmakci** [iVis-at-Bilkent/newt#376]
When a reversible reaction is added from template, nodes and edges except process node are not drawn. This feature used to work properly before merging iVis-at-Bilkent/sbgnviz.js#198.

**Comment by ugurdogrusoz** [comment]
@metincansiper Can you please have a look?

**Comment by metincansiper** [comment]
Looks like the checks for determining if default values exists in ``chise.elementUtilities.createTemplateReaction`` was not fully safe and that become visible after the PR iVis-at-Bilkent/sbgnviz.js#198 though the problem itself is not directly related to the PR.

Must be solved by https://github.com/iVis-at-Bilkent/chise.js/commit/38120cd6008c5bb65d30d9511aa7bf43452c64b5.

**Comment by ugurdogrusoz** [comment]
@metincansiper thanks
