### ISSUE TITLE
Loading polyline edges

### ISSUE THREAD

**Issue by yun-vis** [iVis-at-Bilkent/newt#378]
Hi,

I was reading a sbgn file using newt since it is a great tool to explore the data. 
I have encountered a problem that the system could not load polyline edges appropriately. The start or end elements appear to be empty, which lead to missing edges.

After several testing, I found that Newt has a function when a user drags an anchor point of on an edge to a node, it will automatically merge the anchor to the node. However, if the anchors were merged in a bad order, the entire edge will disappear. Please refer to the following video for an example.

https://www.dropbox.com/s/h3a1890v9zqp3ai/output.mov?dl=0
(This test file can be found here.
https://www.dropbox.com/s/7srujc00z347dqs/new_file.sbgnml?dl=0)

Due to this functionality, I assume that the sbgn file I have created cannot be well displayed on Newt. Note that the edges are there. One can see them after clicking on the force-directed layout.

One of my sample files is here.
https://www.dropbox.com/s/ayuol2yyba0ub4v/example.sbgnml?dl=0

To solve this issue should I confirm that all anchors of my polylines are outside the nodes? or is there any better way to solve this problem?

Thank you very much for your support.

Best regards,
Yun

**Comment by maxkfranz** [comment]
I don't know off hand.  You'd have to go through all the milestones between 3.1.1 and the current version to be sure.  This underscores the case for using an up-to-date, non-forked version of Cytoscape.js.  SBGN can be rendered just by specifying the stylesheet appropriately, e.g. with the cytoscape-sbgn-stylesheet module.

The only case where an edge should not be drawn is if the edge has an invalid specification --- i.e. the edge is impossible to draw as specified.

**Comment by hasanbalci** [comment]
The edge is not drawn for the same case in the edge-bend-editing extension [demo](https://rawgit.com/iVis-at-Bilkent/cytoscape.js-edge-bend-editing/master/demo.html) that uses the latest version of the Cytoscape.js. It seems that the problem only occurs when source-endpoint & target-endpoint of the edge are set to "outside-to-node". Edge is drawn when these attributes are set to other [options](http://js.cytoscape.org/#style/edge-endpoints).

**Comment by maxkfranz** [comment]
You may need to restrict the points to enforce that an intersection is possible for outside-to-node.

**Comment by yun-vis** [comment]
I agree. This seems to be a problem from Cytoscape.js. Thank you very much for pointing it out and I will do some workaround with it.

**Comment by hasanbalci** [comment]
I move the issue to iVis-at-Bilkent/cytoscape.js-edge-editing#21, since it's more related with the extension.
