### ISSUE TITLE
Cardinality boxes appear in other tools

### ISSUE THREAD

**Issue by amazein** [iVis-at-Bilkent/newt#379]
I downloaded the sample neuronal_muscle_signaling file, change the extension from xml to sbgn, opened it in SBGN-ED. There all the connection go with cardinality boxes with value "0" in all of them. Probably cardinality should not be by default in SBGN-ML at all, otherwise it is visualised?

**Comment by ugurdogrusoz** [comment]
Cardinality should not be written out when it's the default value of 0.

**Comment by amazein** [comment]
Wanted to remind about this one. I just tried a small file exported from Newt in 0.2 format, opened it in SBGN-ED, it shows value 0 as cardinality for all consumption/production arcs. The issue is very noticeable and probably comparatively easy to fix?

**Comment by nasimsaleh** [comment]
@ugurdogrusoz Works on the unstable branch

**Comment by ugurdogrusoz** [comment]
Not if you construct a map from scratch though.
