### ISSUE TITLE
Extension xml vs. sbgn

### ISSUE THREAD

**Issue by amazein** [iVis-at-Bilkent/newt#380]
Would not be better to have .sbgn when SBGN-ML files are exported from Newt? Personally I prefer .sbgn because it is recognised by SBGN-ED for example.

**Comment by ugurdogrusoz** [comment]
Let's change the default file name to have a ".sbgn" extension. It's shorter anyway. Let's also change all sample file names accordingly.

**Comment by ugurdogrusoz** [comment]
Can we go with ".sbgn" as opposed to ".sbgnml" please?
