### ISSUE TITLE
Problem with remote file launch

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#385]
On MacOs using Chrome, we cannot open models by URL; it gives an Invalid URL error. Example:
http://web.newteditor.org/?URL=http://sbgn.github.io/sbgn/images/learning/glucose.sbgn

**Comment by ugurdogrusoz** [comment]
This is what you get in the console:
bundle.js:2073 GET https://sbgn.github.io/sbgn/images/learning/glucose.sbgn net::ERR_BLOCKED_BY_CLIENT

**Comment by ugurdogrusoz** [comment]
Not sure if the problem is specific to MacOS

**Comment by ugurdogrusoz** [comment]
http vs https seems like an issue but some links will not work even with https:
http://web.newteditor.org/?URL=https://sbgnbricks.github.io/bricks/reaction/Reaction-PD01-IRR.sbgn

**Comment by ugurdogrusoz** [comment]
Might be fixed with this operation being moved to (?) the server side.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  disabling the adBlocker on chrome solves the issue. it seems adBlocker consider the link as suspicious I suppose, can you disable adblocker (if you use one) and try.

**Comment by ugurdogrusoz** [comment]
What matters is the unstable version. So long as it works there we should be fine.
