### ISSUE TITLE
Newer edgehandles destroy some clickable html components

### ISSUE THREAD

**Issue by metincansiper** [iVis-at-Bilkent/newt#39]
The problem is disscussed in https://github.com/cytoscape/cytoscape.js-edgehandles/issues/62.
Max says that "If you have position: static on the cy div, you can't use ui extensions, see also https://github.com/cytoscape/cytoscape.js/issues/1776" 
We use v2.10.2 of edgehandles extension for now. However, we need to handle this problem in long run.

**Comment by ugurdogrusoz** [comment]
@metincansiper Is this something we should handle before the release or is it some "future work"?

**Comment by metincansiper** [comment]
This problem seems to be fixed in Cytoscape.js by https://github.com/cytoscape/cytoscape.js/commit/3488968eff34603fb848d30a0adf9d0f578e2578

Now we can use cytoscape.js-edgehandles versions after v2.10.2. Therefore, I updated its semver as ```~2.13.1``` in Newt
