### ISSUE TITLE
In some conditions infoboxes are rendered at unexpected positions

### ISSUE THREAD

**Issue by metincansiper** [iVis-at-Bilkent/newt#390]
I tried to load attached sbgn graph in Newt
[graph.txt](https://github.com/iVis-at-Bilkent/newt/files/3020457/graph.txt)

The fallowing is how it is rendered by [sbgnviz.as] (after manually relocating nodes)(http://www.cs.bilkent.edu.tr/~ivis/SBGNViz.as/#)

The fallowing is how it looks in Newt master branch (after performing layout on it):

<img width="862" alt="Screen Shot 2019-03-28 at 4 21 22 PM" src="https://user-images.githubusercontent.com/6534865/55199010-9ab3aa00-5175-11e9-83d1-d31f408a22cc.png">

<img width="373" alt="Screen Shot 2019-03-28 at 3 56 07 PM" src="https://user-images.githubusercontent.com/6534865/55198344-e2850200-5172-11e9-9221-7e351497f2c0.png">

The fallowing is how it is rendered in Newt unstable branch (again after manually relocating nodes)

<img width="540" alt="Screen Shot 2019-03-28 at 3 35 48 PM" src="https://user-images.githubusercontent.com/6534865/55198371-f597d200-5172-11e9-89a0-ab0251f3c9ca.png">

And for some reason it looks like the fallowing after performing automated layout on the unstable branch graph

<img width="890" alt="Screen Shot 2019-03-28 at 3 35 57 PM" src="https://user-images.githubusercontent.com/6534865/55198360-eadd3d00-5172-11e9-8133-99b1c4d4b612.png">

I do not know the reason why relative infobox positions changes after automated layout. However, I have predictions on why the infoboxes maybe rendered on unexpected positions when the graph is just loaded. 

- Why it is different than master branch: In unstable branch it is rendered just like the master branch if [this if statement](https://github.com/metincansiper/sbgnviz.js/blob/unstable/src/sbgn-extensions/sbgn-cy-instance-factory.js#L215) is passed and ``else`` of it is executed instead. And if statement is like the fallowing ``if (isLayoutRequired === undefined || !isLayoutRequired)`` which looks very likely to include a bug (I suppose).

- Why it is different than sbgnviz.as (I suppose it renders the infoboxes at their exact positions from the file) when the ``if`` statement mentioned in above item is exeecuted : Looks like [setAnchorSide()](https://github.com/metincansiper/sbgnviz.js/blob/unstable/src/utilities/classes.js#L264) expects that middle of infobox is passing through one side of node and assigning anchorside to ``right`` if it does not hold for any of other 3 possible sides (See the if-else block in the function).

**Comment by metincansiper** [comment]
Also in [setAnchorSide()](https://github.com/metincansiper/sbgnviz.js/blob/master/src/utilities/classes.js#L264) of master branch code block is inside ``if(mainObj.coordType == "relativeToCenter")`` in unstable there is no such if check.

**Comment by ugurdogrusoz** [comment]
@metincansiper Positioning of info boxes have drastically changed after the release (over last summer). We'll have a chance to look into this over the summer.

**Comment by kinimesi** [comment]
@metincansiper I suspect that  `x` and `y` attributes of the bounding box of infoboxes (`node.data('statesandinfos')[0].bbox`) are calculated wrongly. The related code should be in [this](https://github.com/iVis-at-Bilkent/sbgnviz.js/blob/unstable/src/utilities/classes.js) file.

P.S: the undergrads have a great job on the infobox placement!

**Comment by ugurdogrusoz** [comment]
Could this be related to https://github.com/iVis-at-Bilkent/newt/issues/421?

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  This issue can be considered old after all the changes on infobox. Positions are now read from and written to files correctly

**Comment by ugurdogrusoz** [comment]
Obsolete, closing
