### ISSUE TITLE
Validation related issues

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#392]
- [x] Use [this](https://www.flaticon.com/free-icon/command-window_656) icon (SVG version) for Console tab
- [x] Center align (right now it's left aligned) in Console tab
- [x] Make sure to apply validation only when the map type is "PD" (see Map tab Type property value), not when it's "AF" or "Unknown" or anything else
- [x] "Validation Result" => "Validation Results"
- [x] "File is valid/invalid" => "Map is Valid/Invalid"
- [x] Use red *only* for invalid case to say "Map is Invalid". The explanations should not be in red! "Map is Valid" should not be in green (default black).
- [x] Move this functionality to the View menu: Highlight > Errors of Validation => View > Validate Map
- [x] Buttons are misplaced (Windows + Chrome) outside the tab contents as below:
![image](https://user-images.githubusercontent.com/3874988/57453436-13c31880-726f-11e9-90d6-0c2adee8548a.png)
Let's just place the buttons after error explanation text (not at the bottom of the area) and they should be center aligned.
- [x] When there are multiple errors and the user choose to go "Back", the previous error should be centered in the canvas (just like we center on Next)
- [x] Let's animate the centering of the node/edge with problem (similar to Navigate to other end; there should be an option for panning to achieve this).
- [x] Let's set the zoom level to 150% as we highlight and center the node/edge with problem.

**Comment by ucalis** [comment]
Merhaba hocam,
Issue ile ilgili değişiklikleri yapıp commitledim.

Umut Utku ÇALIŞ

ugurdogrusoz <notifications@github.com>, 9 May 2019 Per, 15:32 tarihinde
şunu yazdı:
