### ISSUE TITLE
libSGBN strokewith interoperability issue

### ISSUE THREAD

**Issue by fbergmann** [iVis-at-Bilkent/newt#393]
Hello, 

i've been working on updating libSBGN to write out render information based on the SBML render extension as proposed to long ago. That works great, but i found one issue. Where in the render extension the attribute is called `stroke-width`, new is using the `strokeWidth` spelling. 

For now i've committed a fix that while reading in we silently upgrade the attribute name. But it would be nice to not need that. 

Is there any way that attribute could be renamed?

**Comment by ugurdogrusoz** [comment]
Looks like it's not just strokeWidth but many others such as fontSize (vs font-size). Let's consistently use the dashed lower case notation on write but accept both forms on read.
