### ISSUE TITLE
Contributing - Submitting issues - Contact us - Help

### ISSUE THREAD

**Issue by amazein** [iVis-at-Bilkent/newt#394]
When someone wants to report an issue, it is not easy to find a way to do it. I knew I needed to find GitHub, so I found a link at http://newteditor.org/ searching Command + F on the webpage.
"Help" in the editor does not point to GitHub, also "Contact us" does not provide suggestions on how to contribute.

**Comment by ugurdogrusoz** [comment]
Let's do the following to at least partially address this issue:
- Increase the width of Help > Quick Help popup window by about 20 percent
- In Quick Help window, add to the very end the following text:

For any issues or bug reports, please [contact us](http://newteditor.org/contact.html).

**Comment by ugurdogrusoz** [comment]
Could you please leave some space before the new sentence? Also center it?

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  Could please check it?
