### ISSUE TITLE
Increase compartment default font size

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#40]
11 -> 14

**Comment by leonarddrv** [comment]
The default values for compartment are imported from chise. Should I change the default value of it?
The samples have their compartment value in their part of code while loading. Should I change them too?

**Comment by ugurdogrusoz** [comment]
Defeault font size should be bigger at the lowest possible layer (sbgnviz?) and upper layers should use this default by default :)
