### ISSUE TITLE
Faster, more convenient box zoom

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#400]
Currently if one wants to zoom into a certain area, they need to click on the Marquee Zoom tool and then start a box using Shift + drag. This is rather inconvenient. Can we perhaps try one of the following:
- Have a shortcut for box zoom such as Shift + Alt + drag. Currently this will perform box selection (same as Shift + drag)
- When in Marquee Zoom mode, use just "Shift" to determine the area to be zoomed to

**Comment by ugurdogrusoz** [comment]
This is great Shift + ctrl + drag works directly as marquee zoom. I noticed that using Cmd instead of Ctrl doesn't work on Mac though. Can we enable that as well?

**Comment by nasimsaleh** [comment]
@ugurdogrusoz could you please check it on Mac, (chrome, safari)

**Comment by ugurdogrusoz** [comment]
Looks good, thanks!
