### ISSUE TITLE
Latest version of node.js does not work

### ISSUE THREAD

**Issue by canbax** [iVis-at-Bilkent/newt#402]
npm install for the latest version of node.js does not work.

Currently both unstable and master branches uses **"libxmljs": "^0.18.4"** but this version of libxmljs does not support node.js versions like **"10.15.3", "10.16.0"** (currently latest version)

but current latest version of libxmljs which is "0.19.5" support both old versions of node.js (like 8.16.0) and the newer ones till "10.16.0".

shortly libxmljs should be upgraded to **0.19.5** for new versions of node.js

**Comment by ugurdogrusoz** [comment]
We also end up changing the version of parallelshell to 3.0.1 (from "^3.0.2") to get the build and deploy working properly. Perhaps this will be fixed when node.js is upgraded?

**Comment by nasimsaleh** [comment]
Tested on Node v10.16.0 which is the latest LTS version of node.

**Comment by ugurdogrusoz** [comment]
Load is broken now. Could it be related to this commit?

**Comment by nasimsaleh** [comment]
it was the commit on sbgnviz. It is fixed now

**Comment by ugurdogrusoz** [comment]
Now we seem to have lost the visual cues for expand/collapse

**Comment by nasimsaleh** [comment]
expand/collapse is working fine on my pc (windows 10, chrome)

**Comment by ugurdogrusoz** [comment]
It wasn't working on my mac but it's ok after cleaning my browser cache.

**Comment by ugurdogrusoz** [comment]
Only remaining issue seems to be validation. I wonder if changes in 3rd party versions broke this.

**Comment by nasimsaleh** [comment]
it should be Ok now, it was from sbgnviz commit

**Comment by ugurdogrusoz** [comment]
It's ok now, thanks!
