### ISSUE TITLE
Move "Map Properties" from "File" to "View" menu

### ISSUE THREAD

**Issue by nasimsaleh** [iVis-at-Bilkent/newt#409]
"Map Properties" in "File" menu doesn't include any file operations, it just to switch to the "Map" view.  it is more logical to move it to "View" menu.

**Comment by ugurdogrusoz** [comment]
Let's also move the related tool in the toolbar to be under View section in the toolbar

**Comment by ugurdogrusoz** [comment]
Looks like by latest commit by @ucalis, the order was mixed up again. Let's please move Validate Map to the end of the list before the separator. Similarly, let's move its icon to the respective place on the toolbar.
