### ISSUE TITLE
Replace cose-bilkent with fcose layout algorithm

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#417]
It might be better to use fcose layout algorithm instead of cose-bilkent for a faster layout.

- Let's make sure to modify the Layout Properties dialog. Luckily most options of the two layouts must be the same.

- Let's also change the way we apply layout in general (see updategraph function at SBGNViz.js level). If the graph size is too big (more than 3000 nodes or more than 3000 edges), let's apply a *draft* layout

**Comment by ugurdogrusoz** [comment]
Let's make sure to modify the Layout Properties dialog. Luckily most options of the two layouts must be the same.

**Comment by ugurdogrusoz** [comment]
Should we decrease this threshold from 3000 to say 1000? Let's discuss.

**Comment by ugurdogrusoz** [comment]
Packing related improvements:
- Can we set desired aspect ratio to be 16:9 or to be the actual value of the Cytoscape.js canvas if possible?
- Can we also increase the component spacing to leave more room around components.
