### ISSUE TITLE
Review z-index of various extensions and prioritize

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#420]
Looks like under some circumstances things aren't working as expected (collapse will not work if the related visual cue is on top of an edge).
This is probably related to the z-index of visual cues used in our extensions. We had similar problems in the past (e.g., https://github.com/iVis-at-Bilkent/newt/issues/396).
Let's review all extensions including below in regards to z-index and such conflicts and see what we can do to improve the current situation:
- node-resize
- edge-editing
- expand-collapse
- pan-zoom controls
- navigation (overview) window

**Comment by ugurdogrusoz** [comment]
@nasimsaleh Can I consider this done and close?

**Comment by nasimsaleh** [comment]
@ugurdogrusoz we can close this one for now.
