### ISSUE TITLE
EntrezGene properties service not working

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#425]
Looks like the [biogene service from PC](https://github.com/iVis-at-Bilkent/newt/blob/d0f1f7d92d2988a6fa0b60fd218a4146f8098972/app/js/fill-biogene-container.js#L32) for gene details is no longer working.
See this: http://www.pathwaycommons.org/biogene/retrieve.do
Emailed PC developers about the problem.

**Comment by hasanbalci** [comment]
I replaced the biogene service from PC with mycancergenome.org as required above.

**Comment by hasanbalci** [comment]
Adding multi-word gene names to the search link causes error in the console. These type of gene names should be modified by either combining words appropriately or just using the first word.

**Comment by nasimsaleh** [comment]
@hasanbalci maybe the space character in multi word gene names should be url encoded ?!

**Comment by ugurdogrusoz** [comment]
Turns out most of the times our gene symbols do not lead to exact match in mycancergenome. We should try to replace it with some other database.

**Comment by ugurdogrusoz** [comment]
Now that we have permission to do so, let's go with Gene Cards.
