### ISSUE TITLE
Color scheme for SIF maps

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#429]
Currently Color Schemes available under Map Properties only apply to PD and AF maps. They should also apply to the SIF drawings. Each color scheme uses a number of distinct colors between 2 and 4. With SIF we only have 2 types of nodes and edge colors are reserved for meaning. So all we have to do is to assign 1 of these main colors in a color scheme to macromolecules and the other to simple chemicals. Reversing a color scheme should reverse these two colors for these two node types.

**Comment by metincansiper** [comment]
@ugurdogrusoz added sif maps to color scheme
