### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#43]
When you load pretty much anything (at least all I tried), you get an error (uncaught TypeError).

**Comment by royludo** [comment]
It's fixed already. @metincansiper can you update the daily version ?

**Comment by metincansiper** [comment]
@ugurdogrusoz is daily build script still working?

**Comment by ugurdogrusoz** [comment]
Looks fixed with the new build in the afternoon
