### ISSUE TITLE
Preference persistence to consider infobox defaults

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#435]
Currently one can save all sorts of preferences to a .newtp file but infobox related ones are ignored (since they came later with SIF support). Changes to infobox style are done through this popup dialog:
![image](https://user-images.githubusercontent.com/3874988/64848602-42387200-d61a-11e9-9825-d5ce17d9ca12.png)

And "Set as Default ..." button in this pop-up can be used to use the current infoboxes style for new infoboxes of the same type (notice that defaults can be different for state variables and units of information).

If set such defaults should also be persisted in Preferences under Object Properties. Notice that these defaults are per node type. In other words, I could set the style of State Variables of Macromolecules different from the style of State Variables of Simple Chemicals. Let's assume if the user is interested in saving preferences for a specific object type, then any available style for infoboxes of that object are also saved in this file. So, the GUI of the preferences dialog need not change.

**Comment by ugurdogrusoz** [comment]
- change properties of state variables for macromolecules
- save preferences
- we notice two problems:
  - *Macromolecule* is not listed under Object Properties (probably since we never set default for macromolecule)
  - Uncaught TypeError: Cannot read property 'checked' of null
    at bundle.js:523
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.<anonymous> (bundle.js:523)
    at HTMLDocument.dispatch (bundle.js:2241)
    at HTMLDocument.h.handle (bundle.js:2237)

**Comment by nasimsaleh** [comment]
@ugurdogrusoz should we save prefrences for info boxes if they are set as default in the info boxes windows despite of 'Set Default' for that specific element class was clicked or not?

**Comment by ugurdogrusoz** [comment]
yes I think so
