### ISSUE TITLE
SIF export not working

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#437]
Load the attached .nwt file (map of type SIF) and export as SIF (File > Export > SIF). The generated SIF file is empty!
[sif-export-bug.nwt.txt](https://github.com/iVis-at-Bilkent/newt/files/3609996/sif-export-bug.nwt.txt)

**Comment by metincansiper** [comment]
@ugurdogrusoz it is because none of the nodes in network is labeled. SIF exporter omits the edges if source or target of it is not labeled as in SIF files nodes are represented by names (I mean there is no specific id etc.).
