### ISSUE TITLE
Add menu items only for specific map types

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#438]
Many add operations in the Edit menu do not apply to certain map types. So we should *ignore* them in incorrect map types:
-  "Add Compartment for Selected" and "Add Submap for Selected" do not apply to maps of type SIF (PD, AF or Unknown are OK)
- "Add From Template" does not apply to maps of type AF and SIF (PD or Unknown are OK)

**Comment by nasimsaleh** [comment]
@ugurdogrusoz Are there many places where map type could change (other than adding-deleting nodes and loading file)? I am asking because instead of checking map type every time a user clicked the edit menu, I would simply update the edit menu when the map type changes.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh what you're suggesting makes sense but in Newt we have been consistently handling situations like this by keeping the menus the same and simply ignoring operations that do not apply. Let's stick to that.
