### ISSUE TITLE
Navigate to other end of edge should also select source node

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#439]
When we click on an edge near the source (target) and choose Navigate to Other End from the edge menu, we focus to the other end of the edge via animated panning and then *select* the target (source) node.
Before we begin the animation we should also select the source (target) node so that when the operation finishes, the user sees both ends of the edge (as selected).

**Comment by ugurdogrusoz** [comment]
I don't see any difference. Besides no commit associated with this issue?

**Comment by nasimsaleh** [comment]
@ugurdogrusoz sorry I just saw this issue, i think I unassigned by mistake. By the way before navigate to other end is clicked if there are other selected elements they stay selected as well. Should other elements be unselected?

**Comment by ugurdogrusoz** [comment]
Let's keep whatever was selected before as selected and add source and target to selections on this operation.
