### ISSUE TITLE
Long file name push down the menu elements

### ISSUE THREAD

**Issue by ivanovaos** [iVis-at-Bilkent/newt#44]
See the screenshot attached.
![screen shot 2017-05-03 at 16 51 24](https://cloud.githubusercontent.com/assets/2984700/25663653/edf1b8b0-3020-11e7-853c-ba71b9a31bcd.png)

**Comment by ugurdogrusoz** [comment]
Let's not display the whole file name if it's above a certain length (say 40 including the extension), and use ellipses: "0123456789012345678901234567890123456789.xml" -> "0123456789012345678901234567890123...xml"

**Comment by ugurdogrusoz** [comment]
I wonder if we can have a tooltip displayed when the mouse is over file name?

**Comment by ugurdogrusoz** [comment]
It might be even better if the file name is editable (on double click), rather than displaying the whole name upon mouse hover.

**Comment by leonarddrv** [comment]
So when double clicked a textbox should appear with the previous "full name", and when clicking outside of it the changed name should be displayed as a text. 
What about the case when the changed name exceeds 40 characters, should it display all the name or first 40 chars?

**Comment by ugurdogrusoz** [comment]
Let's just leave this as is for now (since we already let the user change the file name upon Save)
