### ISSUE TITLE
Export as Cell Designer fails for multiple sample files

### ISSUE THREAD

**Issue by MobiZaman** [iVis-at-Bilkent/newt#441]
Multiple sample files can not be exported as cell designer files. It gives an error of "conversion failed". It works for some other randomly tested samples.

**Comment by ugurdogrusoz** [comment]
@MobiZaman Is this the same issue as [this one](https://github.com/royludo/cd2sbgnml/issues/8). Please provide an example otherwise.

**Comment by MobiZaman** [comment]
In the referenced issue, consecutive conversions are being done back and forth i.e. from cd to sbgn and then, from sbgn to cd. Whereas the issue I mention is that some sample files can not be converted to cell designer at all.

To reproduce the error:
-> open newt
-> go to Files->Samples->Cam-Camk Dependent Signaling to the nucleus
-> go to Export->Cell Designer
And it gives the error of "Conversion failed"

**Comment by ugurdogrusoz** [comment]
Ticketed in associated library: https://github.com/royludo/cd2sbgnml/issues/12, closing this one.
