### ISSUE TITLE
No option exists for Exporting SBGN file

### ISSUE THREAD

**Issue by MobiZaman** [iVis-at-Bilkent/newt#442]
SBGN file can be exported from the export button in File menu. But there is no option to import an SBGN file. Apparently, the load button can load both nwt and sbgn files. But if the save button only saves as nwt file, then the load button should also only load nwt file. So, a button should be added in Import for importing SBGN files.

**Comment by ugurdogrusoz** [comment]
@MobiZaman .nwt files are actually SBGN-ML files with additional style and annotation information. So in that sense you're right that we have an inconsistency here but most people using Newt will directly load a plain SBGN-ML file using the Load button. Thus we opt to combine plain SBGN-ML and styled SBGN-ML under the same File menu item (i.e. Load).
