### ISSUE TITLE
Error handling required if wrong file type is imported

### ISSUE THREAD

**Issue by MobiZaman** [iVis-at-Bilkent/newt#443]
If a wrong file type is selected after choosing to import a particular file type, error should be displayed. Currently, if a cell designer type file is being imported; and a user chooses an sbgn file type or some other one, no error is displayed. 
Sometimes, it shows a loader which doesn't stop loading but most of the times, it results in an empty screen. Furthermore, if a new process is dragged and dropped on the screen, nothing is displayed.

**Comment by ugurdogrusoz** [comment]
@MobiZaman Please provide an example where it doesn't stop loading and another example where the result is an empty screen.

**Comment by MobiZaman** [comment]
To reproduce the continuous loading error:
-> open newt
-> go to File -> Samples -> Neuronal muscle signaling
-> go to Export -> SBGN-ML plain
-> go to Import -> Simple AF -> select the sbgn file exported in the previous step
-> Say yes to the prompt
->The loader keeps being shown

**Comment by MobiZaman** [comment]
Importing sbgn as SIF shows an arrangement of boxes with coding text written inside them.
-> go to File->New
-> go to Import -> SIF
-> select the sbgn file exported before
-> shows a large number of boxes

**Comment by MobiZaman** [comment]
The third is the case where nothing new is displayed after importing a wrong file type:
-> go to File -> New
-> go to Import -> SIF style -> select the sbgnml file
->nothing is displayed on the screen

**Comment by hasanbalci** [comment]
Now a dialog is shown if an error occurs while importing simple AF file.
