### ISSUE TITLE
Import as Cell Designer file often produces an error message

### ISSUE THREAD

**Issue by MobiZaman** [iVis-at-Bilkent/newt#444]
Some of the samples files which could be exported as cell designer files, sometimes produce an error on trying to import them or just give a blank screen.

**Comment by ugurdogrusoz** [comment]
@MobiZaman how is this issue different from #443?

**Comment by MobiZaman** [comment]
Issue #443 is about problems that occur if the file type to be imported is suppose SIF, but the user chooses a file of a different file type e.g. sbgnml. Whereas this issue is that Cell Designer import fails even after a cell designer (xml) file is selected by the user.

To replicate:
-> go to File -> New
-> go to File -> Samples -> Neuronal muscle signalling
-> go to Export -> Cell Designer -> Export it
-> go to Import -> Cell Designer -> causes an error of "Conversion failed"

**Comment by ugurdogrusoz** [comment]
See https://github.com/royludo/cd2sbgnml/issues/12, closing this one.
