### ISSUE TITLE
Fill color change doesn't apply to compartment nodes

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#446]
If we change the fill color of a compartment, the change can be seen in the Object Properties tab, but it doesn't apply to the node. Node remains as it is.

**Comment by ugurdogrusoz** [comment]
I am guessing this is related to https://github.com/iVis-at-Bilkent/newt/issues/373.

**Comment by ugurdogrusoz** [comment]
Thanks @hasanbalci!
