### ISSUE TITLE
Adjust Node Label Font Size Automatically not correctly loaded from saved preference 

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#447]
Save the preferences with "Adjust Node Label Font Size Automatically" as checked. It's saved to the preferences file as true. But when we open a new tab and load the saved preferences file, "Adjust Node Label Font Size Automatically" option remains as unchecked.

**Comment by ugurdogrusoz** [comment]
@hasanbalci pls check and close if OK

**Comment by hasanbalci** [comment]
Apply the same scenario above, now "Adjust Node Label Font Size Automatically" option in the new tab is checked, but then switching to the old tab throws error in the console.

**Comment by nasimsaleh** [comment]
@hasanbalci  I am trying to recreate the error but it doesn't show any error.

**Comment by nasimsaleh** [comment]
@hasanbalci I found an error but it is not related to this issue, but to user preferences in general.

**Comment by ugurdogrusoz** [comment]
@hasanbalci pls list steps to reproduce the problem
@nasimsaleh pls create an issue for the problem you found

**Comment by nasimsaleh** [comment]
@ugurdogrusoz @hasanbalci The steps are as above in the first post, I just missed the sequence of clicks. No need to write them.

**Comment by nasimsaleh** [comment]
I created [this issue](https://github.com/iVis-at-Bilkent/newt/issues/463) which describes the problem above.
