### ISSUE TITLE
SIF accordion in palette shows wrong direction initially

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#448]
When the application is opened, the arrow of SIF accordion in the palette shows up direction even though it's not expanded (see the below image).

![image](https://user-images.githubusercontent.com/22586369/64925702-77e98080-d7fd-11e9-8259-c2545d9bfb4e.png)

**Comment by ugurdogrusoz** [comment]
Right, it's only wrong at first, once the user starts expanding, collapsing, it looks correct though.
