### ISSUE TITLE
Ctrl + drag on a node problem

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#449]
In the current public [release](http://web.newteditor.org/), ctrl + drag on a node feature only transfers a node in and out of a complex/compartment/submap. However, in the unstable version it also makes box selection which is confusing. 

Furthermore, I think ctrl + shift + drag is considered for marquee zoom. However, if user first presses ctrl and then shift and starts to drag on a node, this operation may make marquee zoom, node transfer and box selection at the same time. Please see the below gif: node A is transferred to the outside of the compound node, all nodes are selected and marquee zoom is applied. 

![ctrl-bug](https://user-images.githubusercontent.com/22586369/64926776-272c5480-d80a-11e9-9c56-ceec63be8a4a.gif)

**Comment by ugurdogrusoz** [comment]
@nasimsaleh Pls talk with @hasanbalci about the current behavior and see how it can be fixed.

**Comment by ugurdogrusoz** [comment]
Looks good to me. @hasanbalci pls check and close if OK.
