### ISSUE TITLE
Edge should stay selected when bend point added

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#450]
When a user right-clicks to a selected edge and selects "Add Bend Point", edge becomes unselected. A user needs to select the edge again to see the newly added bend point. In the current public [release](http://web.newteditor.org/#), edge stays selected and user can see the added bend point immediately.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh if we didn't agree on doing this intentionally, we should change it to act as described by @hasanbalci and as in the public release.
