### ISSUE TITLE
Edge with bend points removed while fixing invalid maps

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#451]
If an edge has bend point(s) and it needs to be reversed to be fixed, fix operation removes the edge from the graph.

**Comment by nasimsaleh** [comment]
@hasanbalci could you please give an example of specific error type, or provide an a file that I can test on. I tried with a fix that reverse the edge and bend points stayed.

**Comment by hasanbalci** [comment]
@nasimsaleh Load "Drosophila cell cycle" from samples and start the validation. In the third invalid case, there is a consumption edge with a bend point that connects complex MPF to a process node. When the fix is executed, edge disappears.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz @hasanbalci  it is fixed now, also when the edge is reversed bend points stay in the same position. "reverseEdge" function was added to chise element utilities.

**Comment by ugurdogrusoz** [comment]
@hasanbalci looks good to me. pls check and close if OK.

**Comment by hasanbalci** [comment]
@nasimsaleh I think there is a problem with the "reverseEdge" function. It is ok for the above case, however, in the third, fifth, sixth and seventh PD sample, if we start validation and execute the first fix which requires edge reversal, it throws error in that function.

**Comment by nasimsaleh** [comment]
@hasanbalci it was another issue, I think @ugurdogrusoz  created an issue for it. but for now, it should list the error but it won't offer a fix.
