### ISSUE TITLE
Query timeout

### ISSUE THREAD

**Issue by PermanAtayev** [iVis-at-Bilkent/newt#452]
If the data that is being fetched requires more than 5seconds newt gives an error that it's invalid query. Here we have 2 problems:
1. If the query is valid a user shouldn't get an invalid user error
2. 5 second span for fetching data is too small.

To reproduce the error try querying "Neighborhood" for "BRCA1"

**Comment by ugurdogrusoz** [comment]
Do we actually limit the query execution to a fix duration of 5 seconds in the code? That's too short.

**Comment by PermanAtayev** [comment]
Yes, you can test with the query example I provided. It will say that it's
invalid query, after 5 seconds

**Comment by ugurdogrusoz** [comment]
@hasanbalci Let's start by investigating why 1 neighborhood of BRCA1 doesn't return a valid result.

**Comment by hasanbalci** [comment]
I set the query timeout duration as 30 seconds. This will enable more successful queries.

**Comment by ugurdogrusoz** [comment]
Looks like the specified neighborhood results in too big of maps. We'll [apply draft layout](https://github.com/iVis-at-Bilkent/newt/issues/417) on such big maps. Let's re-check this issue when that's done.
