### ISSUE TITLE
Layout cancelling

### ISSUE THREAD

**Issue by PermanAtayev** [iVis-at-Bilkent/newt#453]
Some genes such as ATR return too much data for the query; therefore, it might be a good idea to let user somehow stop the layout.

To reproduce the problem query "Neighborhood" for "ATR"

**Comment by ugurdogrusoz** [comment]
@PermanAtayev are you suggesting that we should provide a way to the user to stop / cancel layout when it takes too long?

**Comment by PermanAtayev** [comment]
Yes

**Comment by ugurdogrusoz** [comment]
This would be nice but it's not straightforward unfortunately with our layout algorithms. It needs to be supported by the layout algorithm to start with. This will go into our product backlog and I am closing this issue since we're not going to address it in the near term.
