### ISSUE TITLE
Permanent unknown map type

### ISSUE THREAD

**Issue by alihanokka** [iVis-at-Bilkent/newt#454]
When I have an already established map type and I make it unknown by creating objects from different map types, then I am stuck with it forever. There is no way for me to change the map type from unknown ever again. Deleting everything from the graph or redoing my actions do not work as well.

**Comment by ugurdogrusoz** [comment]
We could check for empty maps and go back to the initial state but I am guessing it's not straightforward.

**Comment by nasimsaleh** [comment]
Now when the last element is removed the map type will be reset and adding a new node will change the map type to the desired one.

**Comment by ugurdogrusoz** [comment]
@alihanokka Pls check and close if it works as specified.

**Comment by ugurdogrusoz** [comment]
@alihanokka Never mind we decided to revert this change as it has complications.
