### ISSUE TITLE
Validation error 109 fix missing logical operators

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#455]
We should also be listing logical operators (as claimed) but we don't:
![image](https://user-images.githubusercontent.com/3874988/65037539-9ca53b80-d956-11e9-8958-4a70ae13314c.png)

**Comment by ucalis** [comment]
I think I missed logical operator type check in pd10109 error.  Changes in handleRadioButton function can be needed.

**Comment by nasimsaleh** [comment]
valid logical operators are listed now and ports are taken into consideration when moving the edge.
