### ISSUE TITLE
Named complexes

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#46]
Sometimes users would like to explicitly see the names of named complexes, not just relying on member information or the inspector. Let's have a general properties option (checkbox) named "Display Labels For Named Complexes" (File > Properties). When this option is enabled, we increase complex paddings and display their labels if available. We shouldn't change paddings when labels/names aren't available to save space. When the option is disabled, we shouldn't display labels regardless of availability.
We should have this as an option in the viewer library (SBGNViz) and use it in Chise and Newt.

**Comment by ugurdogrusoz** [comment]
Maybe this should be addressed together with this issue: https://github.com/iVis-at-Bilkent/chise.js/issues/61

**Comment by royludo** [comment]
The padding will now increase if a label is present. It will increase more to account for info boxes that would collide with the label.
Label is displayed inside like compartments, with tighter margins to save some space... tell me if it's ok like that. 
Option is on by default.

**Comment by ugurdogrusoz** [comment]
I just noticed that collapsed complexes have bigger dimensions than they used to have after this change. I think we should make them smaller again. We should match collapsed compartment dimensions.

**Comment by royludo** [comment]
Fixed with iVis-at-Bilkent/sbgnviz.js@0989be36d583b3dd769703b0061c5d204a694e2a
