### ISSUE TITLE
Switching to a tab with user preferences saved results in error

### ISSUE THREAD

**Issue by nasimsaleh** [iVis-at-Bilkent/newt#463]
To recreate:
1- Open a tab and save the user preferences
2- Switch to another tab
3- Switch back to the original tab again

An error "mapName is not defined" will be appear in the console.

**Comment by ugurdogrusoz** [comment]
@hasanbalci pls check and close if ok

**Comment by hasanbalci** [comment]
This problem is fixed, but another problem exists. Open a tab and save preferences, then layout gives error "A `name` must be specified to make a layout".

**Comment by nasimsaleh** [comment]
@hasanbalci  can you check and close if OK

**Comment by hasanbalci** [comment]
Open a tab, change one of the layout properties, then try to save preferences while layout properties is checked. It gives error in the console.

**Comment by hasanbalci** [comment]
Open a tab, change one of the layout properties, e.g. uncheck "Tile Disconnected" only. Save the preferences and open a new tab. In the new tab, uncheck only "Improve Flow". Then load the previously saved preferences and see "Improve Flow" is still unchecked even though it was checked while saving preferences.
