### ISSUE TITLE
Infobox related update after layout takes too long

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#464]
Calling infobox-related [fitUnits](https://github.com/iVis-at-Bilkent/sbgnviz.js/blob/a1852157f670056e91dc515600d157843c16604e/src/utilities/classes.js#L1035) function from Sbgnviz at the [end](https://github.com/iVis-at-Bilkent/newt/blob/744877e88af83c3dae4e6a94f093d38f4d670643/app/js/app-cy.js#L1210) of the layout takes too much time especially for large graphs. I tried with a graph >3000 nodes and this function took ~35 seconds. It may be slowing down some other operations as well.

**Comment by ugurdogrusoz** [comment]
Should we decrease this threshold from 3000 to say 1000? Let's discuss.
