### ISSUE TITLE
Improve flow flag ignored during layout

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#467]
Improve flag in Layout Properties decides whether or not ports should be re-oriented to improve the flow in layout. But looks like we currently ignore this flag and apply this heuristic anyhow.

**Comment by hasanbalci** [comment]
I think improve flow flag decides whether or not nodes should be swapped after port re-orientation. Even so, it was ignored by the application before (It can be seen in the public release). Now I fixed the issue. @ugurdogrusoz Can you please confirm?

**Comment by ugurdogrusoz** [comment]
Looks good, thanks.
