### ISSUE TITLE
Code is displayed instead of Uniprot ID

### ISSUE THREAD

**Issue by royludo** [iVis-at-Bilkent/newt#47]
In the default map, select myosin. In the Properties from EntrezGene section, Uniprot ID row displays this:

A1L2Z2 , function (data) { return render.call(this, data, _); }, function (data) { return render.call(this, data, _); }

**Comment by leonarddrv** [comment]
Is there anything else it should display after A1L2Z2 instead of the code?

**Comment by ugurdogrusoz** [comment]
No, just the ID with a hyperlink

**Comment by leonarddrv** [comment]
The problem was that it used to display 'geneUniprotLinks', I commented it for the moment so it doesn't show parts of code there. Or should I change something at the implementation of 'geneUniprotLinks'?

**Comment by ugurdogrusoz** [comment]
@royludo please verify
