### ISSUE TITLE
Layout not applied while launching by URL

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#471]
Layout is not applied while launching the application by URL, while launching by URI or loading a map from PC query applies layout.

**Comment by ugurdogrusoz** [comment]
Launching by URI should be performing a query to the PC as well (URIs are IDs of pathways in PC).

**Comment by ugurdogrusoz** [comment]
Let's add documentation on options available during the launch to the web pages though.

**Comment by ugurdogrusoz** [comment]
@hasanbalci Can you find related file/code and point me to it, where I can get a listing of such options?

**Comment by hasanbalci** [comment]
The options available during launch are the map properties whose list can be found [here](https://github.com/iVis-at-Bilkent/sbgnviz.js/blob/unstable/src/utilities/validMapProperties.js).

**Comment by ugurdogrusoz** [comment]
I added them to my local copy of the updated web pages. I noticed a couple of inconsistencies that I fixed: [1](https://github.com/iVis-at-Bilkent/newt/commit/2252f879600ada82b3b2b0d8cfabe6274599263c) and [2](https://github.com/iVis-at-Bilkent/sbgnviz.js/commit/ecade5293e1136c5671c6e3cfd517f9a17cbf365).
