### ISSUE TITLE
Reconnection handle residue problem

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#473]
- Select an edge
- Now drag one end of this edge
- Then undo
- Notice how reconnection handles stay in old positions:
![image](https://user-images.githubusercontent.com/3874988/65683571-37dc9600-e066-11e9-83ce-9e64a8ac59fb.png)

Should be evaluated in connection with https://github.com/iVis-at-Bilkent/newt/issues/450 and https://github.com/iVis-at-Bilkent/newt/issues/396.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz For now we can go with this fix, we can create an issue later in cytoscape about edge data not being updated while the node its connected to is being dragged.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh This results in strange things like only some of the edges getting unselected during drag, others staying. Should we unselect all edges if not all elements? Let's discuss.

**Comment by ugurdogrusoz** [comment]
Can we do this only if there is a *single* selected edge at the time of drag?

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  now only if one of the edges connected to the node being dragged is selected, then it gets unselected. as you mentioned we if there is more than one edges selected connection handles are not a problem.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh I don't see a change in behavior?
