### ISSUE TITLE
Unspecified entity default not set with Color Schemes

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#475]
Normally, when you set a color scheme to your map, the defaults for each object type are also set accordingly but that doesn't seem to be the case with *unspecified entities*.

Minimum steps to reproduce:
- Start with a blank map
- Create an unspecified entity
- Set color scheme to an arbitrary one
- Now create another unspecified entity. Notice how it doesn't take the appropriate style from the color scheme.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz apparently it is not only unspecified entity. other nodes types also, the difference is hard to detect. Even though back color and back image are set properly as defaults there is still a little difference in the look when creating a new node. There might a slight difference between the way the style is applied when creating a new node and when color scheme is applied

**Comment by ugurdogrusoz** [comment]
@nasimsaleh the top four were style by setting the color scheme (a 3D one). after that, the bottom four were created from the palette. See that Unspecified entity is not really 3D but others are.
![new_file (3)](https://user-images.githubusercontent.com/3874988/65887433-95464f00-e3a6-11e9-81b1-454392671748.png)

It's minor and probably not related but also notice how the two sides of the Unspecified entity (both top and bottom) is thick somehow.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  Yes I noticed the difference. Also the two Macromolecules look different. What I meant in previous comment is that it is not something specific to Unspecified entity but it appears the most their because of its very light back color.

**Comment by ugurdogrusoz** [comment]
Good catch. I hadn't noticed the different look of macromolecules.
