### ISSUE TITLE
Multimers not loaded

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#476]
From a file or from a sample file (e.g. Polyq proteins interference), multimers won't load properly and won't show.
I don't believe this is related to [this issue](https://github.com/iVis-at-Bilkent/newt/issues/373) as the problem was there before the fix of this issue.

**Comment by hasanbalci** [comment]
This issue is solved but Polyq proteins interference has lost its multimers sometime in the past. That sample needs to be fixed.
