### ISSUE TITLE
Move import/export functionality to SBGNViz.js

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#477]
A couple of the import / export functionality we have in Newt should actually go to the base library SBGNViz.js (similar to [other file formats](https://github.com/iVis-at-Bilkent/sbgnviz.js/blob/46df50200d4099e3500d685979780fb014032682/src/utilities/file-utilities-factory.js#L83)):
- [SBML import/export](https://github.com/iVis-at-Bilkent/newt/commit/005c6664c645bfde47589623dfa52598a3662e71)
- [CellDesigner import/export](https://github.com/iVis-at-Bilkent/newt/blob/005c6664c645bfde47589623dfa52598a3662e71/app/js/app-menu.js#L36)

Make sure to document the API in SBGNViz.js README.

**Comment by ugurdogrusoz** [comment]
@hasanbalci I checked the functionality at Newt level export/import behaves similarly (after refactoring). Could you please confirm that API changes were made at both SBGNViz and Newt levels?

**Comment by hasanbalci** [comment]
It seems that changes done in both Newt and SBGNViz are OK.
