### ISSUE TITLE
SBML export problems

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#480]
Most of our sample maps do not export to SBML:

glycolysis
two_gene_system_behavior
{"reason":"Given input is not a valid SBGN-ML file.","error":"Internal server error."}

polyq_proteins_interference
atm_mediated_phosphorylation_of_repair_proteins
{"reason":"org.sbgn.bindings.Glyph cannot be cast to org.sbgn.bindings.Port","error":"Internal server error."}

neuronal_muscle_signaling
{"reason":"lcsb.mapviewer.model.map.InconsistentModelException: [SquareCompartment _23d436e2-6633-42f2-98d0-00dbb962ac3d]\tProblem with exporting bioEntity","error":"Internal server error."}

**Comment by ugurdogrusoz** [comment]
@nasimsaleh Can you please confirm that these errors are coming from the service we use for conversion? If so, we should contact the providers of this service for help.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz I tried all the above mentioned samples and it works fine. It must have been a temporary server error on their side.

**Comment by ugurdogrusoz** [comment]
Great! Either that or perhaps they fixed the errors.
