### ISSUE TITLE
Review / update READMEs

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#487]
Review / update READMEs of SBGNViz.js and ChiSE.js libraries (unstable branches) especially in regards to build instructions, dependencies, API, options, etc.
When finished, please let @hasanbalci know so he can release them.

**Comment by nasimsaleh** [comment]
@hasanbalci I updated the README for sbgnviz. I listed all the functions except for the classes file as we talked. Coud you check the added functions that has questions marks in their explanation and see which ones should we keep in the public api. Also can you have a quick look at pure js build instructions. Let me know if I need to change anything. Thanks
