### ISSUE TITLE
Invalid values in fill opacity throws error in Firefox

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#488]
In Chrome, we cannot even enter an invalid character (such as alphabetical characters or comma) to the fields that accept numerical values. In Firefox, we can enter but I think those fields have protection against invalid characters and keep the previous values except the field "Fill Opacity" in Object Properties. If an invalid character is entered, then it throws error in the console.

**Comment by ugurdogrusoz** [comment]
@canbax Pls see other similar fields in Settings to fix this error.

**Comment by ugurdogrusoz** [comment]
@hasanbalci Pls verify
