### ISSUE TITLE
Saving collapsed/hidden map content

### ISSUE THREAD

**Issue by royludo** [iVis-at-Bilkent/newt#49]
Saving a file with collapsed nodes deletes its children and breaks the links.

**Comment by ugurdogrusoz** [comment]
Yes, this is a problem we have since SBGNML doesn't address the concept of "collapsed" nodes. What do you recommend we do? I don't think this is an urgent issue though.

**Comment by royludo** [comment]
it's not just the collapsed status, the problem is we lose information, as the children of the collapsed node are not written in the file. I will correct this. For the collapsed status itself, yes, I don't see what we can do.

**Comment by ugurdogrusoz** [comment]
But how do you propose to restore collapsed children? Do you mean to persist the map as if the collapsed node is expanded?

**Comment by royludo** [comment]
Yes, that's what I had in mind. Are you ok with that ?

**Comment by ugurdogrusoz** [comment]
Let s please discuss first

**Comment by ugurdogrusoz** [comment]
Also see https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/issues/38

**Comment by ugurdogrusoz** [comment]
In fact, if this is to be supported, we should also consider persisting hidden nodes/edges

**Comment by ugurdogrusoz** [comment]
As discussed in our regular meeting, we should persist both collapsed and hidden content in our SBGNML files using extension support (at map level). If the hidden, collapsed status is difficult to restore, we should leave this for later releases. In any case, this should be done after submaps are implemented (we have a 3rd compound node type).

**Comment by royludo** [comment]
Now if an element is hidden it can be saved properly with a `<hidden/>` tag attached. Same for collapsed element. Children aren't changed, but the collapsed element itself gets a `<collapsed/>` tag.

Both those tags are part of a `<newt>` extension. So results can look like this in sbgnml:
```xml
<extension>
  <newt>
    <hidden/>
    <collapsed/>
  </newt>
</extension>
```

I didn't want to immediately change the behavior of Newt, because the loading part isn't implemented yet. But when everything works, we'll need to remove `:visible ` from those lines https://github.com/iVis-at-Bilkent/sbgnviz.js/blob/unstable/src/utilities/json-to-sbgnml-converter.js#L73

These extension additions were quite simple so I didn't change libsbgn.js for this newt-specific thing.

**Comment by ugurdogrusoz** [comment]
Excellent
