### ISSUE TITLE
Expand-collapse cues missing in multiple tabs

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#490]
- Load the first PD sample
- Create a new tab and load the second PD sample in the new tab
- Notice how visual cues for expand-collapse are OK in the first tab but do not appear in the second one!

**Comment by hasanbalci** [comment]
I think this not a good fix. See how the operations (drag, layout etc.) slow down drastically.

**Comment by ugurdogrusoz** [comment]
Can you guys please discuss this? What the problem was and why it's not an inefficient way to fix?
