### ISSUE TITLE
CellDesigner import throws an error

### ISSUE THREAD

**Issue by nasimsaleh** [iVis-at-Bilkent/newt#498]
Importing CellDesginer file gives "Conversion Failed!" error. To reproduce:
1- Export any graph as CellDesigner
2- Import the saved file as CellDesigner

**Comment by hasanbalci** [comment]
One point about this issue: I get different error messages in public and internal Newt. It is "Conversion failed" in public and "Conversion service is not available" in internal.

**Comment by hasanbalci** [comment]
While trying to reproduce this issue, I also realized that second sample "CaM-CaMK dependent signaling to nucleus" cannot be exported as CD. It gives the same errors above.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh Before we investigate this, let's:
- Make sure the two repos cd2sbgnml & cd2sbgnml-webservice under *sbgn* organization are up-to-date (compare with the same repo versions under *royludo* and *ivis-at-bilkent*, and if there are any fixes not copied to the repos under sbgn, we should do so)
- Make sure sbgn/cd2sbgnml builds properly to construct a jar file
- Copy the jar file constructed to the appropriate directory in sbgn/cd2sbgnml-webservice repo
- Build and deploy sbgn/cd2sbgnml-webservice in our public server
- Check if Newt can properly access this service and works as intended

**Comment by nasimsaleh** [comment]
@ugurdogrusoz now the service is up-to-date and it is using sbgn repo.
Export worked with following samples:
- neuronal_muscle_signaling
- atm_mediated_phosphorylation_of_repair_proteins
- activated_stat1alpha_induction_of_the_irf1_gene
- vitamins_b6_activation_to_pyridoxal_phosphate
- glycolysis
- mammalian_cholesterol
- two_gene_system_behavior

Importing didn't work on any of the exported samples.

**Comment by ugurdogrusoz** [comment]
Obsolete
