### ISSUE TITLE
SBML import/export improvement

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#499]
As detailed below, let's see if we can report any internal server error problems back to people hosting this service so they can improve their support. This can be done by emailing the SBGN/SBML file causing this error to minerva@uni.lu.

From Piotr:
in some edge cases minerva might crash when trying to convert sbgnml-pd to sbml. I try to cover everything, but it might happen. In such situation the response status code from minerva would be something like: "500 Internal Server Error". Would it be possible for you to catch such situations and create a simple feedback form that would allow user to send bug report with more information. For me the most important thing is the source sbgn file, but contact email address is also nice to have. Having such bug reports would allow me to improve converter further.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  I created an email  "newtforminerva@gmail.com" and we send message from there to report server errors

**Comment by ugurdogrusoz** [comment]
Doesn't seem to work (email) on the server.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz It should be working now.

**Comment by ugurdogrusoz** [comment]
Let's get user's consent before we send the file with an error before we actually email. If they cancel (doesn't give consent), we could state in message body that the user didn't consent but we could still send the email (without attachment).

**Comment by ugurdogrusoz** [comment]
1:
- Make "Conversion failed!" bold
- Make the dialog a bit wider so the consent text fits into a single line!

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  now it sends email to me and cc to newteditor@gmail.com. When we merge to public Newt , we just need to comment and uncomment a line to send to Minerva reporter.

**Comment by ugurdogrusoz** [comment]
1: 
![image](https://user-images.githubusercontent.com/3874988/76498288-a0b99e00-644d-11ea-8cc1-55b749a6e287.png)

**Comment by ugurdogrusoz** [comment]
Looks good. I'll leave this open so we know to change the email back to the right one during release.
