### ISSUE TITLE
Icons for context-sensitive menu items

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#5]
- check if this is feasible (needs to be done at the associated extension) and provide icons for them
- make sure the background color for context menus is the same as the background color (gray) used in the tabs on the right side

**Comment by ugurdogrusoz** [comment]
if this is feasible we should discuss and decide what icons to use

**Comment by ugurdogrusoz** [comment]
@kinimesi is this feasible? does the related extension support icons in front of menu time text?

**Comment by kinimesi** [comment]
@ugurdogrusoz the extension does not support icons, but we can add it.

**Comment by kinimesi** [comment]
@ugurdogrusoz I added icon support to `context menus` extension and added a sample icon to `Perform Layout` context menu in Newt. We need to discuss which menus will have icons.

**Comment by ugurdogrusoz** [comment]
https://docs.google.com/document/d/1TQpLkiqB_Xqog8oxLiuPWx8HjYo0XQfRY3cTVEDTOSY/edit?usp=sharing

**Comment by ugurdogrusoz** [comment]
One minor problem:
- Highlight {Neighbors,Processes} menu items have "layout" icon; neither should have an icon

**Comment by kinimesi** [comment]
@ugurdogrusoz Right now `Highlight Neighbors`menu appears when clicked on a process. Should it appear when clicked on other type of processes (uncertain process, omitted process, association and dissociation)?

**Comment by ugurdogrusoz** [comment]
@kinimesi yes, in general, when we say "process" we mean any one of the "Process Nodes" in the reference card except phenotype. I think the naming is a bit unfortunate.
