### ISSUE TITLE
Infobox positions on creation

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#502]
I am confused about how we position infoboxes at initial creation:
![ScreenRecording2019-12-09at19364](https://user-images.githubusercontent.com/3874988/70455728-d7ce8b00-1abd-11ea-92c7-6780f705b5ed.gif)

Let's discuss.

**Comment by ugurdogrusoz** [comment]
Looks like this is happening since creation is being followed by infobox label text change, which is not supposed to change the infobox's percentange distance.
Let's change the requirements for label text change as follows: if the label whose text is changing is the **right most one** in the *top* or *bottom* side and there is enough room on the associated side, let's move this right most infobox to a location such that the space between the right most infobox and the previous one (if it's the first one the beginning of the side) is exactly the ideal padding.

**Comment by ugurdogrusoz** [comment]
It seems to work in general but as the label of the right-most infobox gets even longer, the center of the infobox starts falling outside the edge of the node:
![new_file (1)](https://user-images.githubusercontent.com/3874988/70537564-b3cc8180-1b71-11ea-9170-37e3ec3445a8.png)

Here the center of the infobox "eeee..." is greater than the right of the node.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz I couldn't reproduce the issue.

**Comment by ugurdogrusoz** [comment]
Use this exact sequence:
- Start with a macromolecule
- state variable "a@a"
- uoi "bbbb"
- state variable "c"
- uoi "dddd"
- state variable "e"
- now extend the text of the last state variable by two e's at a time: "e" -> "eee" -> "eeeee" -> "eeeeeee" -> "eeeeeeeeeee". now you'll see the problem:
![new_file (8)](https://user-images.githubusercontent.com/3874988/70617079-dc5f8480-1c20-11ea-9936-603584915064.png)

**Comment by ugurdogrusoz** [comment]
This is still there! I checked with daily build.

**Comment by nasimsaleh** [comment]
After manually rebuild the issue is resolved.
