### ISSUE TITLE
Infoboxes mislocated with non-empty compounds

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#503]
When a compound is empty, the locations of the infoboxes look fine. But when you put a child in a compound, they get messed up:
![ScreenRecording2019-12-09at19483](https://user-images.githubusercontent.com/3874988/70456215-bfab3b80-1abe-11ea-9172-fa97aafe93a8.gif)

Relocate also clearly shows that the edges of compounds are calculated incorrectly for moving infoboxes.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz Also resolved previous unreported issues with compound node tiling and fitting etc.

**Comment by ugurdogrusoz** [comment]
Looks good to me. @hasanbalci Please check as well.

**Comment by hasanbalci** [comment]
Yes, it seems ok.
