### ISSUE TITLE
Infoboxes not taken into bound calculation

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#507]
When I interactively create the following nodes with infoboxes and fit them in window using the pan-zoom controls, I get:
![image](https://user-images.githubusercontent.com/3874988/70615815-2a26bd80-1c1e-11ea-817b-3bf30b5dcb95.png)

However, when I save this file on disk and load back and then fit in window, I get:
![image](https://user-images.githubusercontent.com/3874988/70615733-0499b400-1c1e-11ea-8ef6-3d6b0d6dc71f.png)

Notice how infoboxes aren't taken into account in graph bounds!

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  I think the cause of this issue is same as [#423](https://github.com/iVis-at-Bilkent/newt/issues/423)

**Comment by ugurdogrusoz** [comment]
Looks like information boxes are now taken into account but I still see a minor discrepancy between the graph margins. When I load this file
[margin-problem.nwt.txt](https://github.com/iVis-at-Bilkent/newt/files/4190012/margin-problem.nwt.txt)

I get: 
![image](https://user-images.githubusercontent.com/3874988/74306050-7acbab80-4d72-11ea-8913-21bca059ecf4.png)

When I fit in window I get *narrower* margins:
![image](https://user-images.githubusercontent.com/3874988/74306010-64255480-4d72-11ea-90f0-a4bb6979d026.png)

**Comment by nasimsaleh** [comment]
@ugurdogrusoz Panzoom option for fit padding in Newt is 20 px and on file load it is 50 px. Now I made both of them 20 px. So after loading a file clicking pan zoom to fit should not have an effect.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh I just noticed that we have a similar problem with SIF views. Load one of the SIF samples. Notice how the compounds are cut off and not shown fully **on load** but will be ok if you fit in window.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  it should be ok after internal Newt is rebuilt.
