### ISSUE TITLE
Infobox load from file problem

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#508]
The attached file was saved when I created two macromolecules with some infoboxes and then I checked "Fit Labels to Information Boxes" in map settings.
Upon reload we get an error and we can't seem to recover from it.
[infobox_load_problem.nwt.txt](https://github.com/iVis-at-Bilkent/newt/files/3950069/infobox_load_problem.nwt.txt)

**Comment by ugurdogrusoz** [comment]
This is also still there. Please check if daily build was updated after your fixes.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz I build manually and it seems to work fine now.
