### ISSUE TITLE
Infobox drawn to the wrong side 

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#510]
The attached file includes a macromolecule and an infobox on its right side. (You can confirm from the bounding box values inside the file.) However, when we load this file, infobox is drawn on the left side of the macromolecule. 
[new_file.txt](https://github.com/iVis-at-Bilkent/newt/files/3968788/new_file.txt)

**Comment by ugurdogrusoz** [comment]
Looks good to me on unstable daily build. @hasanbalci Pls check and close if OK.
