### ISSUE TITLE
Sample files cannot be exported as SBML

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#516]
3rd, 5th, 6th, 7th and 10th sample files below the PD title cannot be exported as SBML. The resulting files have either
- {"reason":"org.sbgn.bindings.Glyph cannot be cast to org.sbgn.bindings.Port","error":"Internal server error."} or
- {"reason":"org.sbgn.bindings.Port cannot be cast to org.sbgn.bindings.Glyph","error":"Internal server error."}
inside.

**Comment by ugurdogrusoz** [comment]
Again looks like a problem with the SBML conversion service.

**Comment by piotr-gawron** [comment]
Dear @hasanbalci,

I will take a look and fix it.

**Comment by piotr-gawron** [comment]
Dear @ugurdogrusoz, @hasanbalci 

I  think I fixed the problem. I put it on our dev machine for testing (https://minerva-dev.lcsb.uni.lu/ - this is machine that you are using for conversion so it should be available immediately). Please let me know if I omitted something or close the issue if it's fixed.

**Comment by ugurdogrusoz** [comment]
@piotr-gawron we don't see any difference, the same sample files reported above will not convert to SBML. For instance, with the third sample "ATM mediated phosphorylation of repair proteins" in Newt we get:
{"reason":"org.sbgn.bindings.Glyph cannot be cast to org.sbgn.bindings.Port","error":"Internal server error."}

**Comment by piotr-gawron** [comment]
Dear @ugurdogrusoz, @hasanbalci

I just double checked. Everything should be fixed now. If the problem persist please let me know.

**Comment by ugurdogrusoz** [comment]
@hasanbalci I checked the first 5 samples from PD and the 1st one from AF, they all converted fine. Please check the others and close if OK.

**Comment by hasanbalci** [comment]
@ugurdogrusoz 7th sample (PolyQ proteins interference) in PD gives "Conversion failed!" error during export. AF samples don't give error but not exported correctly. Many of the nodes are lost during export. You can see that when you import them again.

**Comment by ugurdogrusoz** [comment]
The following is probably the email notification due to conversion failing with the 7th PD sample:

Error message: {"reason":"lcsb.mapviewer.model.map.InconsistentModelException: [StateTransitionReaction glyph25]\tProblem with exporting bioEntity","error":"Internal server error."}

[input.txt](https://github.com/iVis-at-Bilkent/newt/files/4413688/input.txt)

**Comment by ugurdogrusoz** [comment]
Obsolete. We use an external service for this and we're limited by their capabilities anyway.
