### ISSUE TITLE
Infobox position not preserved in compounds after save and load

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#518]
To reproduce:
- Add a compartment
- Add a macromolecule inside the compartment
- Add an infobox to compartment
- Save the map and load again

Before save:
![image](https://user-images.githubusercontent.com/22586369/71715760-89de4600-2e23-11ea-8fc9-95781253ac63.png)

After save and load:
![image](https://user-images.githubusercontent.com/22586369/71715806-af6b4f80-2e23-11ea-9b0e-de57c3c3403f.png)

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  actually this is an issue with writing non-empty compound nodes coordinates to files. I created a non-empty compound node and an empty one with the exact size and exact location and noticed the saved file the coordinate of the two nodes are different. 
This is the same issue as this one  https://github.com/iVis-at-Bilkent/newt/issues/328

**Comment by ugurdogrusoz** [comment]
The above scenario works as expected now but this one doesn't:
- create a compound with infoboxes relocated:
![new_file (3)](https://user-images.githubusercontent.com/3874988/71822420-dcc73000-30a5-11ea-8d8e-611a6614c070.png)

When saved the map is: 
[comp-infobox-save-load_nwt.txt](https://github.com/iVis-at-Bilkent/newt/files/4026315/comp-infobox-save-load_nwt.txt)

- load back and you get:
![new_file (4)](https://user-images.githubusercontent.com/3874988/71822585-42b3b780-30a6-11ea-812c-8d83f39c1307.png)
