### ISSUE TITLE
Full sized Newt with auto-adjusting sub-windows

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#52]
As discussed today, we'd like to improve the Newt window in certain ways:
- get rid of the unused spaced on the left and right
- make tab panel (inspector, palette, etc.) width dynamic w.r.t. window dimensions so that we (almost) never get to see horizontal scrollbars. For instance, palette rows should contain less nodes/edges when window is smaller
- prevent issues like https://github.com/iVis-at-Bilkent/newt/issues/20 by making sure the canvas/drawing area is properly resized as the Newt window is resized

**Comment by istemi-bahceci** [comment]
- get rid of the unused spaced on the left and right
    - About this, I think it seems fine now but I can get rid all of it If you wish

~~- make tab panel (inspector, palette, etc.) width dynamic w.r.t. window dimensions so that we (almost) never get to see horizontal scrollbars. For instance, palette rows should contain less nodes/edges when window is smaller~~


~~- prevent issues like https://github.com/iVis-at-Bilkent/newt/issues/20 by making sure the canvas/drawing area is properly resized as the Newt window is resized~~

**Comment by royludo** [comment]
The blue rectangle indicating selection in the palette no longer turn to dashed line once we get into selection mode.

**Comment by istemi-bahceci** [comment]
@royludo  Fixed the issue, thanks for pointing out :)

**Comment by ugurdogrusoz** [comment]
Let's please get rid of the unused space on the left and right. If it doesn't look nice, we could have some minimal paddings on left and right.

**Comment by ugurdogrusoz** [comment]
perfect, thanks!

**Comment by ugurdogrusoz** [comment]
When the Palette pane is quite wide, should we not fit more than 4 icons per row?
![image](https://user-images.githubusercontent.com/3874988/27023106-b8790906-4f59-11e7-940a-c1a7daf62d4d.png)

**Comment by ugurdogrusoz** [comment]
Can we also please move toolbar and the drawing canvas closer to the menubar by reducing the space between them like this: 
![image](https://user-images.githubusercontent.com/3874988/27023188-1d7777e8-4f5a-11e7-8f35-60a75b0c7c08.png)

**Comment by istemi-bahceci** [comment]
Fitted 5 icons per row, and decreased margins. Should be fixed now.

**Comment by ugurdogrusoz** [comment]
Margins are fine thanks. But regarding icons in the Palette; that's not really what we want. We want to see a dynamic number of icons per row in the Palette. If it's big enough we can fit more than 4, even more than 5. But if it's small, we should decrease it down to maybe even 3.

**Comment by ugurdogrusoz** [comment]
Or simply 4 or 5 icons per node depending on the width of the window but with the same paddings between icons.

**Comment by istemi-bahceci** [comment]
Dynamically adjusted number of icons per row, should be ok now.

**Comment by ugurdogrusoz** [comment]
Great; one minor thing: can we make the icons centered (as opposed to left justified):
![image](https://user-images.githubusercontent.com/3874988/27382093-147a8c8a-568e-11e7-8b7f-8b5604fb90d3.png)

**Comment by istemi-bahceci** [comment]
Should be fixed.

**Comment by ugurdogrusoz** [comment]
doesn't look fixed to me (sometimes the rows are closer to the right, sometimes to the left):
<img width="1280" alt="screen shot 2017-06-22 at 09 37 44" src="https://user-images.githubusercontent.com/3874988/27420437-89eceb16-572e-11e7-9564-ad660b236943.png">
<img width="1280" alt="screen shot 2017-06-22 at 09 37 34" src="https://user-images.githubusercontent.com/3874988/27420443-8ef3a294-572e-11e7-83b1-fc6b21249283.png">

**Comment by ugurdogrusoz** [comment]
Margins aren't balanced. Additionally, nodes, edges aren't left justified as it's always been (see last row of PD edges and AF nodes). Moreover, fine-tuning of the paddings around node and edge palettes are lost!
![image](https://user-images.githubusercontent.com/3874988/27727710-580eaa3e-5d88-11e7-817b-6bf66b38b0ca.png)

**Comment by hasanbalci** [comment]
In my laptop with 1920x1080 resolution and Windows 10, a horizontal scrollbar appears in Chrome as in the figure:

![screenshot from 2017-07-12 11-43-03](https://user-images.githubusercontent.com/22586369/28109835-2443a0f4-66f9-11e7-9c52-e8cb43232d49.png)

Is this a problem that can be fixed easily?

**Comment by ugurdogrusoz** [comment]
@istemi-bahceci please see scrollbar problem reported by @hasanbalci

**Comment by hasanbalci** [comment]
Thanks, scrollbar problem is solved.

**Comment by istemi-bahceci** [comment]
Paddings are broken on Firefox

**Comment by kinimesi** [comment]
In Firefox (Windows and Linux), there is very large empty space at the bottom. Scrollbars appear unnecessarily. See attached screenshot below.
![screenshot_20170724_181216](https://user-images.githubusercontent.com/7281872/28530255-ea557eba-709b-11e7-8317-c05a8bd5f4ff.png)

Once the window is resized, the empty space and scrollbars disappear.

**Comment by ugurdogrusoz** [comment]
I am not sure this is an issue any longer.
