### ISSUE TITLE
Compound padding values

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#521]
- Rename "Compound Padding" to "Additional Compound Padding"
- Set its default to 0 and do not allow anything below 0 (current negative values result in an error in Console)
- By default complexes should have a minimum padding 5 (when the above is set to 0)
- By default non-complexes should have a minimum padding 14 (currently 19)
- Rename all variables in code accordingly. Constants that we have for base paddings should be named including "complex" and "non-complex"

**Comment by nasimsaleh** [comment]
@ugurdogrusoz no commit is present here because I committed these changes before I saw there was an issue created for it. I also rebuilt local newt.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh For next time, in such cases you should be able to at least list such commits as comments.

**Comment by ugurdogrusoz** [comment]
Seems to be fine but I want to make sure we renamed all variables accordingly. If so, please go ahead and close the issue.

**Comment by ugurdogrusoz** [comment]
Actually we have an issue here. When a complex has label, current paddings are not sufficient:
![new_file (28)](https://user-images.githubusercontent.com/3874988/73514661-985c5500-4403-11ea-9b7e-90a2c86e3424.png)

Let's talk about how to fix this.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz complex padding should be ok now. I also added comments to padding variables explaining what they mean.

**Comment by ugurdogrusoz** [comment]
Why did we change the padding for non-complex nodes? We have problems like this now:
![new_file (30)](https://user-images.githubusercontent.com/3874988/73524283-d9616300-441d-11ea-905d-01e937109837.png)

**Comment by ugurdogrusoz** [comment]
Looks like we had this problem before as well. Let's not bother doing anything about this since: compartments are usually very large and we don't have many infoboxes. So there is little chance of such overlaps.
