### ISSUE TITLE
Expand does not work from menubar with only one compound 

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#53]
When there is only one compound node, View->Collapse/Expand->Expand All and Expand Complexes (if compound is a complex) does not work and gives error.

**Comment by hasanbalci** [comment]
Expand also does not work when there is one compound, animation is closed, and visual cue is used to expand the node.

**Comment by ugurdogrusoz** [comment]
According to @kinimesi if this issue is resolved, so should this one: https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/issues/39

**Comment by kinimesi** [comment]
@leonarddrv @hasanbalci it seems like solving iVis-at-Bilkent/cytoscape.js-expand-collapse/issues/39, resolved this issue too. Can you verify? Thanks.
