### ISSUE TITLE
Complex paddings are drawn incorrectly in NEWT

### ISSUE THREAD

**Issue by evescat** [iVis-at-Bilkent/newt#531]
According to the attached file (generated from NEWT) [simple-nwt.txt](https://github.com/iVis-at-Bilkent/newt/files/4185908/simple-nwt.txt), the padding between the complex and the protein should be approx. 1.5. Image below shows that in newt the padding is approx. 10 (1/3 of protein's height).    
![Screen Shot 2020-02-11 at 14 48 43](https://user-images.githubusercontent.com/52324846/74242116-a0f33c00-4cdd-11ea-8447-5a69eb9dcc1f.png)

Moreover, in case there is a reaction, which is connected to the complex, production position is located on the border visible in newt (with padding equals to 10). However, according to sbgn data the reaction does not reach the complex border.

![Screen Shot 2020-02-11 at 14 55 36](https://user-images.githubusercontent.com/52324846/74242639-971e0880-4cde-11ea-899f-da103e555371.png)

![Screen Shot 2020-02-11 at 14 55 12](https://user-images.githubusercontent.com/52324846/74242603-88375600-4cde-11ea-83b3-a398597d44b5.png)

**Comment by nasimsaleh** [comment]
Hello @evescat , Thank you for your feedback. We are aware of the padding and coordinates problem in compound nodes in Newt files. We are working on it and it will be fixed in a point release in the near future.

**Comment by ugurdogrusoz** [comment]
@evescat We just released Newt 3.0. This problem is fixed now along with some exciting new features such as experiment data overlay. Please check it out.
