### ISSUE TITLE
Resize cue flickers during expand

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#534]
Resize cue flickers during expand operation in internal Newt. Public Newt doesn't have this problem. To reproduce, add a compartment and fill the compartment with nodes and edges. Then first collapse and then expand the compartment. 
![ResizeCue](https://user-images.githubusercontent.com/22586369/74911439-a7fd0700-53cd-11ea-93a9-d5d460e59514.gif)

**Comment by nasimsaleh** [comment]
@ugurdogrusoz issue occurred after this [fix](https://github.com/iVis-at-Bilkent/chise.js/commit/0455f76b6bd642885b38e11bf24b1876958ad806) to this [issue](https://github.com/iVis-at-Bilkent/newt/issues/524). While expanding the positions of the nodes are changing so the resize cue keeps deleted and redrawn. Now before expand, a flag is put on the node stating it is expanding, and after layout of expanding stops that flag is removed.
