### ISSUE TITLE
render information in nwt file

### ISSUE THREAD

**Issue by piotr-gawron** [iVis-at-Bilkent/newt#536]
In exported nwt file you are using renderInformation schema from sbml render package.

According to the render specification (https://sourceforge.net/p/sbml/code/HEAD/tree/trunk/specifications/sbml-level-3/version-1/render/sbml-render-version-1-release-1.pdf?format=raw) the `style` node should have `idList` attribute, but you are using `id-list` (check section 3.6.3 of above mentioned specification). If you could change the attribute to `idList` then nwt file would be a bit more standardized.

Below you can find example xml node with your implementation:

```xml
<renderInformation 
  xmlns="http://www.sbml.org/sbml/level3/version1/render/version1" id="renderInformation" program-name="sbgnviz" program-version="5.0.0" background-color="#00000000">
  <listOfColorDefinitions>
     <colorDefinition id="color_1" value="#c8d8ebff"/>
     <colorDefinition id="color_2" value="#000000"/>
  </listOfColorDefinitions>
  <listOfBackgroundImages/>
  <listOfStyles>
     <style id="nodec8d8eb1000000114normalnormalHelvetica000" id-list="n1">
      <g font-size="14" font-family="Helvetica" font-weight="normal" font-style="normal" font-color="#000" stroke="color_2" stroke-width="1" fill="color_1"/>
    </style>
  </listOfStyles>
</renderInformation>
```

**Comment by ugurdogrusoz** [comment]
@nasimsaleh Similar to [this issue](https://github.com/iVis-at-Bilkent/newt/issues/393) I think. Did we not decide to do this for all attributes?

**Comment by fbergmann** [comment]
@ugurdogrusoz , indeed 'idList' is the spelling in the specification: 

<http://co.mbine.org/specifications/sbml.level-3.version-1.render.version-1.release-1.pdf>

 In fact my implementations wouldn't have read id-list and would have failed to apply styles for it. The original author of the render specification decided that for the graphic groups he preferred the SVG style, thus there you have `stroke-width` rather than `strokeWidth`.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh So, let's change id-list to idList and leave the graphics related ones to continue using camel casing.

**Comment by ugurdogrusoz** [comment]
@piotr-gawron Could you please confirm the fix in [our daily build](http://ivis.cs.bilkent.edu.tr/) and close this if OK?

**Comment by piotr-gawron** [comment]
I can confirm that it does work. 
However I think it's not in master yet, because I just cloned newt repo and it didn't work.

**Comment by ugurdogrusoz** [comment]
@piotr-gawron Thanks! We will merge it to master with a point release in the near future.
