### ISSUE TITLE
Exporting as SIF

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#537]
Open one of the SIF samples and Export | SIF. Notice how the file contains only nodes, no edges. Export seems to be problematic only when topology grouping is enabled.

**Comment by metincansiper** [comment]
@ugurdogrusoz I created a PR in sbgnviz (https://github.com/iVis-at-Bilkent/sbgnviz.js/pull/205) to fix this issue.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh Please test the PR locally and merge if OK.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz I merged it.
