### ISSUE TITLE
Undo/redo bug

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#539]
- Open first sample
- Enable "Allow Compound Resize"
- Resize one of the compartments
- Undo (compartment back to original size)
- Undo (Allow Compound Resize is disabled)
- Redo (Allow Compound Resize is enabled)
- Redo: should resize the compartment but doesn't

**Comment by nasimsaleh** [comment]
@ugurdogrusoz This bug was old, it also exists on public Newt
