### ISSUE TITLE
Newt doesn't work with latest stable node.js version

### ISSUE THREAD

**Issue by piotr-gawron** [iVis-at-Bilkent/newt#540]
I tried to run newt on node.js 12 (v12.16.1) and I couldn't make it happen. During npm install I got errors when installing `libxmljs` dependency. Here is a sample of the error (full error log is much longer):

```
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:203,
                 from ../src/libxmljs.h:7,
                 from ../src/libxmljs.cc:7:
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::Function>::return_t Nan::imp::Factory<v8::Function>::New(Nan::FunctionCallback, v8::Local<v8::Value>)’:
../../nan/nan_implementation_12_inl.h:105:32: error: no matching function for call to ‘v8::Function::New(v8::Isolate*&, void (&)(const v8::FunctionCallbackInfo<v8::Value>&), v8::Local<v8::Object>&)’
                           , obj));
```

I think this dependency is using some deprecated stuff that was removed in node 12.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh let's check what the latest in unstable builds with and doesn't build with.

**Comment by nasimsaleh** [comment]
@piotr-gawron the library indeed has a problem with versions of node later than (10.x.x). We will address this issue in later versions of Newt. You can use Node  v10.19 LTS

**Comment by ugurdogrusoz** [comment]
@nasimsaleh Can you also try "^0.19.3" for this library with latest version of node.js (version 12)? They supposedly made this library work with latest node.js with 0.19.6.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz I was already trying with version "0.19.3". It doesn't work.

**Comment by ugurdogrusoz** [comment]
Looks like the *master* branch will build fine with latest node.js but not *unstable*. We'll address this later.

**Comment by hasanbalci** [comment]
After upgrading `libxmljs` with commit https://github.com/iVis-at-Bilkent/newt/commit/41586d2e7f278f0567af73b8602b0b4520bf7c16After, I am able to install unstable branch both on node.js v12.16.1 (Windows) and on node.js v13.10.1 (Linux).

**Comment by ugurdogrusoz** [comment]
@nasimsaleh Can you try one more time making sure you do it from scratch? I would use the latest LTS version v12.16.1.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz I tried with V12.16.1 and it works now. I tried from scratch.

**Comment by ugurdogrusoz** [comment]
@piotr-gawron We think this is now resolved. Please try with the **unstable** branch to verify if you got the time.
