### ISSUE TITLE
Experiment data overlay problems

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#542]
Now perhaps the most important missing piece of the puzzle for Newt is experiment data overlay support. @mervekilicarslan5 and @rumeysaozaydin worked on this feature and are almost done with it (a few minor formatting/naming issues remain) on a separate branch named *ExperimentDataOverlap*.
Before this branch is merged to *unstable*, let's do some testing to see if there are any **show stopper** problems. Initial requirements for this work is [here](https://docs.google.com/document/d/15xvnYdCpJPB0ADl9iKFrx--TjAp1cfOAq8-NJNKR5sM/edit?usp=sharing). Areas to test include:
- File format for experiment data
- Experiment data vs. color scheme (they both use background image sometimes). When experiment data is loaded the color scheme should go to default b&w scheme, not using background images.
- Loading multiple files or a file with multiple experiment data
- Enabling / disabling experiment sets or entire files
- Undo/redo for experiment data related operations

[sample1.txt](https://github.com/iVis-at-Bilkent/newt/files/4300821/sample1.txt)
[sample2.txt](https://github.com/iVis-at-Bilkent/newt/files/4300822/sample2.txt)
[sample3.txt](https://github.com/iVis-at-Bilkent/newt/files/4317953/sample3.txt)
[sample4.txt](https://github.com/iVis-at-Bilkent/newt/files/4328536/sample4.txt)
How sample4.txt looks with sample data map:
![sample-exp-map](https://user-images.githubusercontent.com/3874988/76603314-d1690880-651d-11ea-93ad-5c1d0a42c080.png)

Samples are for CaM-CaMK dependent signaling to nucleus. Different number combinations can be tried. Everything is tab-delimited. Node labels are directly used.

**Comment by mervekilicarslan5** [comment]
[sample1.txt](https://github.com/iVis-at-Bilkent/newt/files/4300821/sample1.txt)
[sample2.txt](https://github.com/iVis-at-Bilkent/newt/files/4300822/sample2.txt)

**Comment by mervekilicarslan5** [comment]
Samples are for CaM-CaMK dependent signaling to nucleus. Different number combinations can be tried. Everything is tab-delimited. Node labels are directly used.

**Comment by nasimsaleh** [comment]
- [ ]  "Experiment" menu should have "Remove All Data" to remove/clear all experiment data

- [ ] When no data is available, experiment section should only contain this text: “No experiment data to display!”

- [ ] When experiment data file is not in correct format, error is thrown in console, it should be smoothly handled. Maybe by displaying error message to user.

- [ ]  List of files and experiments should be aligned.

**Comment by hasanbalci** [comment]
When I load sample1 to CaM-CaMK sample, CaN macromolecule gets three color. On top of it, if I load sample2 without the CaN data (with only CaM and Ca++ data), all CaN, CaM and Ca++ gets 6 color. Is this normal? I was expecting that the second sample will affect only CaN and Ca++.

**Comment by ugurdogrusoz** [comment]
@hasanbalci I think this is normal. in the second experiment set if data is not available for a particular node, it should be shown in grey (to mean not available).

**Comment by ugurdogrusoz** [comment]
@nasimsaleh please work on issues titled **Improvements**.
@mervekilicarslan5 please work on issues titled **Bugs**.

**Comment by hasanbalci** [comment]
Bug 5 should be solved. However, if a complex doesn't have child initially and gets experiment data and then if we add a child into it, removing experiment data from the complex requires further action such as hiding one of the experiments, or removing and restoring experiment data.

**Comment by hasanbalci** [comment]
I cannot reproduce bug 4.

**Comment by hasanbalci** [comment]
Bug 2 is fixed.

**Comment by hasanbalci** [comment]
Bug 1 is fixed with https://github.com/iVis-at-Bilkent/newt/commit/b36c55ce7e8d7a157b6ace5ddd260b46bc99af07 and https://github.com/iVis-at-Bilkent/sbgnviz.js/commit/9e353b5046d62c9dee4704b89d1bb97781365dc1.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh 14: this is done as specified but there is room for improvement I think as follows:
![image](https://user-images.githubusercontent.com/3874988/76834889-fd96c900-683e-11ea-84df-e0a000a92f6f.png)
- Since the border width is fixed, sometimes there is ample empty space within the borders which looks ugly. Let's try to use separators before **and** after each experiment file content.
- Let's dedicate more space to the delete icon (70-30 or 65-35 instead of 80-20)
- Let's use bold face for file names to distinguish them from experiment names.

**Comment by hasanbalci** [comment]
Bug 2 is fixed.

**Comment by ugurdogrusoz** [comment]
**Minor issues to be addressed later**:
- [Windows + Chrome] When title & description of an experiment file is concatenated for filename tooltip, we see a weird character in between the two.

- [Mac OS + Chrome] Filename tooltip has an extra blank line at the end (even when title & description aren't concatenated but only the description is used as tooltip)

**Comment by ugurdogrusoz** [comment]
Closing this, remaining problems are in other individual issues.
