### ISSUE TITLE
How do I programmatically edit .nwt files?

### ISSUE THREAD

**Issue by ashtonteng** [iVis-at-Bilkent/newt#545]
Hello, 

Thanks for making this awesome editor! I am trying to programmatically insert a <style> tag and its associated <g> tag into a .nwt file. The purpose is to change the colors of some of the glyphs given differential expression input. Do you have any suggestions of the best way to do it? The libsbgn-python package doesn't deal with <style> tags, and using the built in xml package seems to mess up the .nwt format.

Cheers,

Ashton

**Comment by ugurdogrusoz** [comment]
@ashtonteng Our default format (.nwt) is an extension (for color and other style information) of plain [SBGN-ML](https://github.com/sbgn/sbgn/wiki/SBGN_ML) file format. Newt uses [libsbgn.js](https://github.com/sbgn/libsbgn.js) to read/write SBGN-ML files with style extension. Let us know if you need pointers to these files. Ideal resolution for what you need is for the python version of the libsbgn library to support the style extension as well. 

Btw, soon to be released version of Newt will have support for experiment data overlay. Users will be able to input experiment data with tab-delimited files to overlay them on pathways. Example:
![sample-exp-map](https://user-images.githubusercontent.com/3874988/76603314-d1690880-651d-11ea-93ad-5c1d0a42c080.png)

**Comment by ashtonteng** [comment]
Yeah, I figured out a hacky way to do it and it works for now. Looking forward to the experimental data overlay!
