### ISSUE TITLE
Problem on experiment file load

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#547]
Attached file will give an "Incorrect file format!" error but will show the file and experiments in the associated panel.
[acc_2014vs2019.txt](https://github.com/iVis-at-Bilkent/newt/files/4348883/acc_2014vs2019.txt)
![image](https://user-images.githubusercontent.com/3874988/76960349-4ed0b680-692c-11ea-8f34-38daa8ff7b45.png)

**Comment by hasanbalci** [comment]
Attached file causes the same problem. 
[sample5.txt](https://github.com/iVis-at-Bilkent/newt/files/4379724/sample5.txt)

**Comment by nasimsaleh** [comment]
@hasanbalci  @ugurdogrusoz in the file instead of "15,2" it should be "15.2"  use dots for decimal points not comma.

**Comment by hasanbalci** [comment]
@nasimsaleh I intentionally used comma to get "Incorrect file format!" error and I got it, but it still shows the file in Experiment panel.

**Comment by nasimsaleh** [comment]
@hasanbalci  It should be OK now, it was working before but I think after the merge few things changed. Can you check and close if OK?

**Comment by ugurdogrusoz** [comment]
@hasanbalci Please verify and close if OK

**Comment by hasanbalci** [comment]
@nasimsaleh If there is no other experiment data loaded before and I try to load this file, then it works correctly (it says "Incorrect file format!" and data aren't shown in Experiment section). However, if there is previously loaded experiment data and I try to load this file, then it says "Incorrect file format!" but data are still shown in the Experiment section.
