### ISSUE TITLE
Experiment data undo problem

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#550]
Loading an experiment file is not undoable (undo stack is reset). Suppose I have a map that I just made changes with (say layout). Then I load an experiment file. When I undo twice, the experiment file/data should be removed and the map should go back to before layout positions.

**Comment by hasanbalci** [comment]
@ugurdogrusoz Could you please verify that it is solved?

**Comment by ugurdogrusoz** [comment]
I still need to do extensive testing but looks very nice in general.
