### ISSUE TITLE
Experiment data color scheme issue

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#552]
- [x] 1. When an experiment data is overlaid on a map, the color scheme should be changed to the default (solid b&w). Following shows otherwise:
    - Load the first PD sample
    - Load an experiment data file
    - Now add a new macromolecule from the palette. Notice how the new node has the style of the original color scheme before the experiment data is loaded.
![image](https://user-images.githubusercontent.com/3874988/77041658-598e5880-69cb-11ea-8c6d-a3b9d2b69658.png)
Related to https://github.com/iVis-at-Bilkent/newt/issues/551 but not the same problem?

- [x] 2. Another problem I see with color scheme:
    - Load the first PD sample
    - Collapse one of the outer compartments
    - Load an experiment file (nodes become b&w)
    - Now expand the collapsed node, the unrevealed nodes come back in original color scheme:
![neuronal_muscle_signaling](https://user-images.githubusercontent.com/3874988/77100517-d3076480-6a26-11ea-9a22-fcb029db5553.png)

**Comment by hasanbalci** [comment]
This may be resolved after the merge of ExperimentalDataOverlay branch to unstable. Let's check it again after the merge.

**Comment by ugurdogrusoz** [comment]
1: this is fine with the default tab **but** if you create a second tab and do it there, the problem is still there. I don't know why there would be a different behavior between the first and second tabs.

**Comment by hasanbalci** [comment]
Second bug is fixed.
