### ISSUE TITLE
Showing experiment data values

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#553]
Now that we can overlay experiment data on pathways using color coding, we should also facilitate showing the actual data values to the user. This could be done in two ways simultaneously:
1. As node tooltips: e.g. for RB1 in sample data "(36, 12)"
2. As a table that contains n+1 columns (one for the node labels, remaining are for all n experiments in all files as listed in the right panel) and m+1 rows (one for the headers: "Node expr1 expr2 ..." and m for m nodes with at least one experiment data). This table should be popped up from a button in the same row as "Hide All" and "Remove All" before both with [this icon](https://www.flaticon.com/free-icon/table-grid_25617).

**Comment by ugurdogrusoz** [comment]
Work on **unstable** branch for this!
@nasimsaleh Please work on adding tooltips
@canbax Please work on adding a table of values (ask @nasimsaleh about where to find these values)

**Comment by ugurdogrusoz** [comment]
1: 
- [ ] 1. When a node doesn't have experiment data , we should use "-" for that entry as a tooltip. E.g.
<img width="255" alt="Screen Shot 2020-03-20 at 16 11 18" src="https://user-images.githubusercontent.com/3874988/77166503-6abb9000-6ac5-11ea-9e18-8cd864675942.png">

2: 
- [ ] 10. The table icon should be middle aligned with "Hide All" and "Remove All" text. Currently the icon is a little below the text.
- [ ] 11. Except for the header, let's decrease the font text size by 1.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  point [1] should be OK now.

**Comment by ugurdogrusoz** [comment]
11: problem is still there?
16: can we please decrease the font size in Search field to be the same as node labels in the table?
- [ ] 20. Can we remove the separator line after the Search field before the table? There should be a separator line after the last row though (missing right now).

**Comment by ugurdogrusoz** [comment]
11: Can we please use a simple and compatible icon (e.g. the one in Layout Properties dialog)?

**Comment by ugurdogrusoz** [comment]
11: The icon looks good. If we can make the x sign aligned to be not below the title "Experiment Data", we're good to go.
