### ISSUE TITLE
Review Help menu for 3.0 release

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#566]
Can we please review what's under the Help menu for the 3.0 release? Specifically:
- [x] Quick Help: add/remove anything?
- [x] Quick Tutorial: anything that's show stopper for using 2.0 tutorial for 3.0?
- [x] UI Guide: anything to be updated here? We need to add Experiment menu!

**Comment by hasanbalci** [comment]
1- Quick Help: "Ctrl/Cmd + Shift + drag" functionality may be added for Marquee Zoom.

2- Quick Tutorial: All functionality seem valid for version 3.0, but the only problem is that videos start as Newt Version 2 and their titles also indicate Newt 2.

3- UI guide: It seems the only need is to mention about Experiment menu in the Map Properties section of the guide.
