### ISSUE TITLE
Tooltips can be annoying

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#57]
Tooltips sometimes get in the way of visualizing things since they are very big. Maybe we don't need them at all since the inspector shows this information or maybe they should be transparent. In the case of complexes if named complex label display is enabled and the complex doesn't have any infobox, we don't need tooltips anyway.

**Comment by ugurdogrusoz** [comment]
We increased the delay for tooltips; let's experiment with this a bit.

**Comment by ugurdogrusoz** [comment]
@kinimesi Shall we get rid of the tooltips completely?

**Comment by kinimesi** [comment]
@ugurdogrusoz I am not sure about completely removing them.  They might be useful when the labels are truncated after fitting them to nodes and information boxes.

**Comment by ugurdogrusoz** [comment]
They pop up during dragging as well and they are really obstructive. Since inspector (on selection) has all the information in the tooltip anyway, I think we should remove tooltips completely. Let's comment them out and give it a try.
