### ISSUE TITLE
Undo-redo batch operation removes bend points

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#573]
Simply create two nodes and an edge between them. Then create a bend point on the edge and click on "Tile Information Boxes" in the root context menu. Bend point is removed.

**Comment by nasimsaleh** [comment]
@hasanbalci This issue is not related to Tiling information boxes. Any undoRedo batch action will remove the bend points. I tried from browser console undoRedo.do("batch",[])

**Comment by hasanbalci** [comment]
@nasimsaleh Yes, you're right. It seems that I caused this issue while solving #126. I'll try to fix it.

**Comment by hasanbalci** [comment]
https://github.com/iVis-at-Bilkent/sbgnviz.js/commit/328027ffa0b69348c1716d9aef711b613823b18b solves issue.
