### ISSUE TITLE
Alignment problems

### ISSUE THREAD

**Issue by canbax** [iVis-at-Bilkent/newt#575]
Load [the SBGN file](https://github.com/iVis-at-Bilkent/newt/files/4393690/af0.txt)

It will give a map like 
![image](https://user-images.githubusercontent.com/8426741/77760103-e6c65280-7046-11ea-990f-95e4564a597d.png)

select all 
![image](https://user-images.githubusercontent.com/8426741/77760189-01003080-7047-11ea-969e-527684c09222.png)

align horizontal middle
![image](https://user-images.githubusercontent.com/8426741/77760302-29882a80-7047-11ea-8a67-515aaec344b4.png)

noticed there the "black dots" are not positioned.

**Comment by ugurdogrusoz** [comment]
- [ ] Alignment results in incorrect reconnection handle locations if a single edge is selected on alignment. This is true regardless of map type. Perhaps the cleanest solution is to unselect such edges on alignment?

- [ ] There is another more serious problem with this map. The alignment should be done w.r.t. first selected node but I don't see that happening. I wasn't able to reproduce this problem for a map created from scratch though.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz unselecting is the cleanest solution, if I only unselect the edge it looks a bit weird, so I unselect the nodes with it. Let me know if you want me to change that. I only unselect if one edge is selected.

About the second point I didn't see a problem. I tried as follows:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16354894/77832396-caa9da80-7146-11ea-9d43-0682a9243a13.gif)

**Comment by ugurdogrusoz** [comment]
@nasimsaleh The user will like to see the nodes that he selected and check the alignment. So, let's unselect the edge and only when there is a single edge (I think we applied the same workaround in some other context).

**Comment by ugurdogrusoz** [comment]
- [ ] 3. A new problem I noticed is with the topology groups (compounds) in SIF views. For instance, load the first SIF sample and select at least one topology group to align with others. The alignment works fine but when you undo, things get messed up.
![RTN4-controllers-and-binding-proteins](https://user-images.githubusercontent.com/3874988/77856367-52ebb680-71ff-11ea-9bcb-61086586575a.png)

**Comment by nasimsaleh** [comment]
@ugurdogrusoz It was also creating problem with compound alignment, now both should be ok.
