### ISSUE TITLE
Custom annotation validation service down

### ISSUE THREAD

**Issue by canbax** [iVis-at-Bilkent/newt#576]
try to validate GTSE1 as in here https://www.youtube.com/watch?v=6pP78sht7PM&t=155

It gives error

> validation error Error: Testing availability of url http://identifiers.org/hgnc:515152 failed. Request status: 400. Error: null
    at Object.success (bundle.js:306)
    at fire (bundle.js:83199)
    at Object.fireWith [as resolveWith] (bundle.js:83329)
    at done (bundle.js:89236)

![image](https://user-images.githubusercontent.com/8426741/77764605-f72dfb80-704d-11ea-9d1b-e98d4b78e95f.png)

**Comment by ugurdogrusoz** [comment]
@nasimsaleh I wonder if the related service is down! This was working just the other day.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz I tried and it is working. Maybe service was down at that point of time.

![attachment](https://user-images.githubusercontent.com/16354894/77824982-79cebd80-7117-11ea-927d-cb153f05d214.JPG)

**Comment by hasanbalci** [comment]
@ugurdogrusoz @nasimsaleh I think the number in the video is 51512 and it is working, but @canbax tried it with 525152 and it gives error.

**Comment by ugurdogrusoz** [comment]
Sorry my bad. I mixed up incorrect ID with service not working. Things are working fine, ID was wrong!
