### ISSUE TITLE
Object>image>URL does not work

### ISSUE THREAD

**Issue by canbax** [iVis-at-Bilkent/newt#577]
add a "macromolecule". Open "Object" tab. Go to "Image" part. Check "URL". Give this url https://webgradients.com/public/webgradients_png/170%20Light%20Blue.png . 

Console will give print below

> /#:1 Access to image at 'https://webgradients.com/public/webgradients_png/170%20Light%20Blue.png' from origin 'http://ivis.cs.bilkent.edu.tr' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
webgradients.com/public/webgradients_png/170%20Light%20Blue.png:1 GET https://webgradients.com/public/webgradients_png/170%20Light%20Blue.png net::ERR_FAILED

Nothing changes on the background of the "macromolecule"

**Comment by ugurdogrusoz** [comment]
This is a known problem https://github.com/iVis-at-Bilkent/newt/issues/327.
It works for [this one](https://cdn3.iconfinder.com/data/icons/people-icons/64/Person-512.png) for instance. I wonder what the pattern is here?
