### ISSUE TITLE
Selection sticks and gives error

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#578]
- Load the following map
[vitamins_modified.nwt.txt](https://github.com/iVis-at-Bilkent/newt/files/4401709/vitamins_modified.nwt.txt)

- Select (click and release on) node labeled "1", and then move the mouse. Notice how the node starts moving (even though you released the mouse) and an error is shown on the Console.

The problem is there in public Newt as well. The way I created this map is by:
- Load the associated sample
- Change border color and thickness of some labels as well as renaming them

**Comment by nasimsaleh** [comment]
The problem occurs for any node that has a label that's purely a number.

**Comment by ugurdogrusoz** [comment]
This issue was there for a long time. I came across it while I was preparing exam questions for Data Structures where the node labels were integers :)
