### ISSUE TITLE
Node opacity lost on save/load

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#579]
- Create a macromolecule
- Set a visible fill color
- Set opacity to be 0.5
- Save and load back. The opacity is back to default 1.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  Aslo I made this [commit](https://github.com/sbgn/libsbgn.js/commit/754a4c754c7b1ce70c6e82939ab54825e4e5f3a0) to LIbsbgn.js develop branch. Now it supports _background-opacity_ and _background-image-opacity_
