### ISSUE TITLE
Increase padding for complexes with infoboxes

### ISSUE THREAD

**Issue by royludo** [iVis-at-Bilkent/newt#58]
Infoboxes of complexes still touch the elements or the element's infoboxes.

**Comment by ugurdogrusoz** [comment]
Please be as conservative as possible to keep drawing compacts

**Comment by royludo** [comment]
I did things as tight as possible, only increasing the padding to get 1-2px of space, only when it is necessary (for instance, no need to increase when there is no infobox, or no label..)

**Comment by ugurdogrusoz** [comment]
I think paddings, etc. are perfect now, thanks!
