### ISSUE TITLE
Review README and third party libraries

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#580]
Let's please review the README and the third party libraries, making sure the list is complete and the licenses are stated correctly.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  It should be Ok now.

**Comment by hasanbalci** [comment]
@ugurdogrusoz It seems that README is up-to-date.

**Comment by hasanbalci** [comment]
It seems ok, so I'm closing.
