### ISSUE TITLE
Undo-redo of fill opacity not working correctly

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#581]
- Set color-scheme to 3D and to a color-style.
- Add a macromolecule and set its fill opacity to 0.25.
- Then it requires two undo operations to set it back to 1 but even though the value in the inspector seems as 1, the real opacity on the node doesn't seem as 1.

When I saved the file, background-image-opacity="0.25" and background-opacity="1".

**Comment by ugurdogrusoz** [comment]
@hasanbalci looks good to me, pls check and close if ok

**Comment by hasanbalci** [comment]
The two-step undo operation is fixed, but opacity doesn't return into its previous state on the node.
For example initially:
![image](https://user-images.githubusercontent.com/22586369/78159980-fd581980-744b-11ea-879c-1e805a29fa24.png)

After setting to 0.25:
![image](https://user-images.githubusercontent.com/22586369/78160080-1d87d880-744c-11ea-8620-50ff6879522b.png)

After undo:
![image](https://user-images.githubusercontent.com/22586369/78160300-68095500-744c-11ea-8d1f-0ec4abf96076.png)

See how node in first and third image is different. When I save the file after undo, its background-image-opacity="0.25" and background-opacity="1". I think background-image-opacity stays as 0.25 after undo, it's not set to 1 again.

**Comment by nasimsaleh** [comment]
@hasanbalci can you check now. background-image-opacity was not set in the nodes default properties. value was undefined so on undo it couldnt be set to undefined, so it stays to whatever value it was initially changed to.

**Comment by hasanbalci** [comment]
It works now, thanks!
