### ISSUE TITLE
Long rendering time after layout

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#584]
In the `layoutstop` event [here](https://github.com/iVis-at-Bilkent/newt/blob/ebb8d84d1968ae379750e584d1b3876248c292e3/app/js/app-cy.js#L1275), there is a line that sets `expanding` data of each node to `false`. I think this line is added for #534, but it is called even though layout is not applied for expand-collapse. Probably this change in data triggers style update at each time and slows down the rendering of the graph after layout drastically especially for large graphs.

Some thoughts on how to speed up this process:
- This operation should be done only after the layout is applied for expand-collapse.
- It should be done in a batch, if possible.
- Setting `expanding` data only on parent nodes should be enough instead of processing all the nodes.

**Comment by hasanbalci** [comment]
Flickering of resize cue is now prevented during both expand and layout operations. This was happening if there is only one selected compound node, hence required operations are now applied only on the corresponding node and this prevents the actual loss of performance.

**Comment by ugurdogrusoz** [comment]
@hasanbalci is this resolved?
