### ISSUE TITLE
Label truncation performance improvement

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#588]
In order to improve the performance due to label truncation (when Fit labels to nodes is true), which seems to be an expensive operation, we could truncate them just once at the beginning of the element instantiation, save it in a new data field, and then use that field all the time.

**Comment by ugurdogrusoz** [comment]
@canbax This is a similar improvement to the one we did with another project.

**Comment by canbax** [comment]
related with b8a9f60e6e6f53fce8694bf9b3d7b6115b1fb48c
