### ISSUE TITLE
Remembering user / drawing preferences

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#59]
Some drawings tools can remember both user / drawing preferences. 
Such preferences include:
- File > Properties...
- View > Grid and Guidelines...
- Layout > Layout Properties...
- Defaults for styles (per node/edge defaults, color scheme)

We should think about whether these should be saved as user preferences (so the next time Newt is used by the same user or on the same computer, preferences are the same) or drawing preferences (when an arbitrary user loads up the same drawing, preferences are the same). Maybe a combination of both; needs discussion.

**Comment by ugurdogrusoz** [comment]
Looks great overall, some improvements:
- [ ] 1. Swap save and load in the menu for consistency
- [ ] 2. Move Validate Map to be right before the separator

Save dialog related:
- [ ] 10. It should have a consistent look & feel with others (e.g. Layout Properties) including font style and size, title background, etc.
- [ ] 11. Section names should not be in bold and without ":". For instance, "Map Properties".
- [ ] 12. The order of section names should be consistent: Map, Grid, Layout, and then Object
- [ ] 13. Subsections under Object Properties should be named to be the same as the titles in the inspector "Macromolecule", "Consumption" etc.

Load dialog related:
- [ ] 20. Similar to Save, look & feel should be consistent
- [ ] 21. Naming should be "Grid Properties" instead of "Load Grid Properties:", etc.
- [ ] 22. Order should similarly be consistent: Map, Grid, Layout and then Object

**Comment by ugurdogrusoz** [comment]
Could we also:
- [ ] 31. Add a checkbox next to Object Properties to **select/deselect all*:
Object Properties  <checkbox>
When checked, all individual checkboxes should be disabled.

- [ ] 32. Can we capitalize the individual object properties as follows:
  "Unspecified entity" -> "Unspecified Entity"
  "BA macromolecule" -> "BA Macromolecule"

- [ ] 33. Can we put a couple of leading blank spaces before these individual object property? Make sure even the longest properly fits here.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  the bug you mentioned occurs because we are saving "Color Scheme" in Map Properties, which interferes with the element styling. I would suggest that we don't save the "Color Scheme" in Map properties to the preference file because anyhow the color scheme is applied to all elements only by one click.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh I think the problem is we save and apply default values on load, which overrides the style determined by the user. Let's not persist *non-default* settings to avoid this.

**Comment by ugurdogrusoz** [comment]
![image](https://user-images.githubusercontent.com/3874988/61778717-f3cfd980-ae07-11e9-9bda-d87188183de3.png)
