### ISSUE TITLE
Incorrect ports on Plain SBGNML export/import

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#590]
Also available in the public Newt:
- Load Drosophila sample
- Export as "SBGNML Plain"
- Load into another tab. Notice for instance how some stimulation edges connect to their process from a port.
<img width="313" alt="Screen Shot 2020-05-18 at 13 49 21" src="https://user-images.githubusercontent.com/3874988/82205149-c9a75500-990e-11ea-8b73-aa0c5574762a.png">

**Comment by hasanbalci** [comment]
It seems that stimulation and catalysis edges in Drosophila sample had incorrect target assignments (actually they were targeting ports instead of nodes). I fixed sample and it should be ok now.
