### ISSUE TITLE
Compounds cannot be resized to content from menu

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#591]
Add a compartment with a macromolecule inside. Resize compartment from resize grapples. Then click on "Resize Nodes To Content" from menu. Macromolecule is resized while compartment isn't affected.

**Comment by hasanbalci** [comment]
Apparently, this is intentional from the third item in issue #517.

**Comment by ugurdogrusoz** [comment]
It's not a bug, it's a feature then :)
