### ISSUE TITLE
Export as SVG images not found by Inkscape

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#597]
If you export the cam-camk sample as SVG and try to edit with Inkscape, you get:
![image](https://user-images.githubusercontent.com/3874988/82423467-7529e400-9a8c-11ea-843f-873d0ff634ba.png)
The file opens fine with IE browser for instance.

**Comment by msalihaltun** [comment]
It seems to open fine for me, maybe the background image wasn't exported correctly? Not sure how to reproduce this.

![image](https://user-images.githubusercontent.com/26147738/120970323-f45f8800-c773-11eb-99ab-470ad4e965cb.png)

**Comment by ugurdogrusoz** [comment]
I was able to reproduce this in version 0.92 of Inkscape on Windows. Then I upgraded Inkscape to version 1.1 and it disappeared. So no worries!
