### ISSUE TITLE
Check up time regularly for Newt servers

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#601]
For the two servers below (public and internal, resp.), let's use something like Uptime Robot to ensure its up time regularly.

139.179.21.94 (web.newteditor.org)
139.179.21.90 (ivis.cs.bilkent.edu.tr)

**Comment by onsah** [comment]
It's now implemented. It checks in every 15 minutes and notifies to ivisatbilkent gmail account whenever an up or down occurs.  

There is also public status page that can be checked from [here](https://stats.uptimerobot.com/v954AuWLRE)

There are 2 monitors as follows: 
* Newt Stable HTTP: checks HTTP connection for url http://web.newteditor.org
* Newt Unstable HTTP: checks HTTP connection for url http://ivis.cs.bilkent.edu.tr

**Comment by ugurdogrusoz** [comment]
Great, perhaps we can add services like cd2sbgnml here later on. Let's keep the issue open.

**Comment by ugurdogrusoz** [comment]
Just tested the daily / internal server. It was down for 16 minutes and no notification email was sent.

**Comment by onsah** [comment]
It was my mistake I thought adding the mail adresses to alert list would be sufficient. But then I realized that alert contacts needs to be enabled for each url separately after adding alert contacts to list. 

After making the changes I tested for down and up statuses and mail is received
