### ISSUE TITLE
Slow first time load

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#602]
From @kinimesi:
I'm not sure what is going on, but accessing Newt from the US is very slow, it takes almost 30 seconds to load (it's not loading at the moment). There might be some kind of DDoS attack to the server, the physical distance also contributes to the slow load time. I think we need to integrate a CDN service. Cloudflare's free plan includes both DDoS attack mitigation and Global Content Delivery Network: https://www.cloudflare.com/plans/ It also looks like the integration is just a couple of clicks.

Let's investigate this.

**Comment by ugurdogrusoz** [comment]
@kinimesi Please check (might be effective at the end of the day) if you see a difference.

**Comment by kinimesi** [comment]
@ugurdogrusoz It's still slow, essentially same as before. From the HTTP response header, it looks like the Cloudflare cache is never hit.

**Comment by onsah** [comment]
@kinimesi I set Cloudflare to cache everything under http://web.newteditor.org/. Now checking I sometimes get `cf-cache-status: HIT` in the headers so it seems to work. On my computer response time is ~400ms. Can you also check?

Also should we also cache newteditor.org or only the application? Currently it only caches the app.

**Comment by ugurdogrusoz** [comment]
@onsah I think we can also cache the web site.

**Comment by kinimesi** [comment]
@onsah based on my limited testing, it loads much faster and the cache status is `HIT`. Great job!

@ugurdogrusoz I think it'd unnecessary (adds another layer to maintain) to cache the website. It's hosted on GitHub pages and it already loads fast.

**Comment by ugurdogrusoz** [comment]
@kinimesi Thanks for bringing this up and verifying.
@onsah Good job. Let's not worry about the web pages then.
