### ISSUE TITLE
Error when tiling infoboxes in an empty map

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#603]
Click on "Tile Information Boxes" in the root context menu while map is empty, an error is thrown in console, but it doesn't prevent application from running.

**Comment by msalihaltun** [comment]
This should be fine now.

**Comment by ugurdogrusoz** [comment]
@hasanbalci please test and close if OK

**Comment by hasanbalci** [comment]
It seems ok.
