### ISSUE TITLE
More SBGN bricks

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#606]
Previously we implemented some convenience menu items (similar to SBGN bricks) to quickly create building blocks of SBGN maps via [this issue](https://github.com/iVis-at-Bilkent/newt/issues/519). Now we should extend our support with more SBGN bricks (see [here](http://sbgnbricks.org/getting_started/)):
- [x] irreversible (we already have reversible)
- [x] activation and deactivation
- [x] metabolic catalytic activity
- [x] transcription
- [x] translation

We should also
- [x] Better align the associated Edit menu item and other names, descriptions, etc.

**Comment by msalihaltun** [comment]
I have added the new bricks. As far as I have tested, the reactions are added correctly, and I changed the modal UI as we discussed.

**Comment by ugurdogrusoz** [comment]
- [ ] 1. Rename "Add from Template..." to "Add using SBGN Bricks..."
- [ ] 2. "?" icon should be smaller (not taller than the combo box) and separated a little bit more from the combo box
- [ ] 3. Activation & Deactivation: "Protein" -> "Label"
- [ ] 4. Metabolic Catalytic Activity: I am not sure about this one (I asked someone) but I think rather than fixing the type of the Catalyst here we should give choices through a combo box. Choices should be: Macromolecule, Simple Chemical, Unspecified Entity, Nucleic Acid Feature and Perturbing Agent.

**Comment by ugurdogrusoz** [comment]
1. "using" -> "Using"
5. undoing this will not convert the map type back to what it was

**Comment by msalihaltun** [comment]
I should also have linked [this commit](https://github.com/iVis-at-Bilkent/chise.js/commit/9106cebb9b27cabfd04d843de8c4e6d4235e0dba) to this issue.

**Comment by ugurdogrusoz** [comment]
Based on the recent discussions and work with Alexander and Adrien, we should start preparing some mockups (let's start with the first one evaluate).

**Comment by ugurdogrusoz** [comment]
Let's address issues with each type of brick in a separate branch.
