### ISSUE TITLE
Plain SBGN export

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#608]
When we export maps in regular SBGN (we currently call this *plain SBGN*), we should not trim off the style and annotation information (we should trim off Newt specific information though such as map properties). May be we should do this for 0.3 only, let's check.

**Comment by msalihaltun** [comment]
It seems we already save annotations on nodes in plain SBGN. Is that intended?

**Comment by ugurdogrusoz** [comment]
Plain SBGN (0.2, default): no annotations, no style, no map properties
Plain SBGN (0.3): annotations and style but no map properties
Newt (0.2 default or 0.3): annotations, style and map properties

**Comment by msalihaltun** [comment]
I believe it should be okay now.
