### ISSUE TITLE
Original styles missing when re-loading sample via experiment menu

### ISSUE THREAD

**Issue by msalihaltun** [iVis-at-Bilkent/newt#609]
When I load the sample via `Experiment` dropdown menu's `Load Sample` option once, everything seems fine. But when the same option is used again and the confirmation box is confirmed, it appears that the sample is loaded without styling -or at least without the original styles-.

Reproduce the bug: After the first time loading, which loads fine, I am able to reproduce this issue every time I try to load the sample, seemingly regardless of whether I make changes on it or not.

**Comment by msalihaltun** [comment]
@hasanbalci can you confirm that it works now?

**Comment by hasanbalci** [comment]
@msalihaltun Thanks, it works.
