### ISSUE TITLE
Links on learning SBGN and SIF

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#612]
Let's add the following to make sure the user has easy access to the necessary resources on learning the notation:
- Under "Help > Quick Help", as the first two items before "File > Samples", add:
  o "**SBGN Notation**: [Learning SBGN](https://sbgn.github.io/learning) - [Learner's Cards](https://sbgn.github.io/learnerscards)"
  o "**SIF Notation**: [SIF Relations](http://www.pathwaycommons.org/pc2/formats#sif_relations)"

- Under "Legend" menu, in respective pages put the following as *center aligned* at the bottom of each page:
  o PD legend page: [Reference Card](https://sbgn.github.io/referencecards) - [Specifications](https://sbgn.github.io/specifications) 
  o AF legend page: [Reference Card](https://sbgn.github.io/referencecards) - [Specifications](https://sbgn.github.io/specifications) 
  o SIF legend page: [SIF Relations](http://www.pathwaycommons.org/pc2/formats#sif_relations)

**Comment by msalihaltun** [comment]
Links have been added.

**Comment by ugurdogrusoz** [comment]
In Quick Help, let's capitalize as follows (my bad):
- "SBGN Notation" -> "SBGN notation"
- "SIF Notation" -> "SIF notation"

**Comment by msalihaltun** [comment]
Working on the edit now, sorry.

**Comment by ugurdogrusoz** [comment]
Sorry to go back to this but can we please:
- Make sure the text for links in Legend pages have a consistent style with others? Font size should be smaller (see the email and web page links in the About page), font style should be the same, etc.
- Can we leave a bit more space before these links (after the actual Legend content)?

**Comment by msalihaltun** [comment]
![image](https://user-images.githubusercontent.com/26147738/90633634-10b72600-e22f-11ea-95d1-f3831cd581cb.png)

Is this okay? I used the same css class as in the About page. Are the margins okay here?

**Comment by ugurdogrusoz** [comment]
@msalihaltun Thanks. Margins and spacing are fine. If the font size is the same as those of the links in the About page, we're good to go.
