### ISSUE TITLE
Learner's cards as samples

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#613]
The two Newt files (one for PD and one for AF) in the [Learner's Cards](https://sbgn.github.io/learnerscards) section of SBGN website could be made available as samples. Let's put them at the *end* of each section under File > Samples with titles "PD Learner’s Reference Card" and "AF Learner’s Reference Card", respectively.

**Comment by msalihaltun** [comment]
Added Learner's Cards as samples in respective menus.
