### ISSUE TITLE
Duplicate attribute prevents minifying bundle.js

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#615]
'background-opacity' attribute is defined [here](https://github.com/iVis-at-Bilkent/newt/blob/d0e1c11503236376d8982c69d9463d185bad474a/app/js/app-utilities.js#L2139) twice and it prevents minifying bundle.js during release. Probably, Javascript uses the second one, so if the first one is really unnecessary it should be removed.

**Comment by ugurdogrusoz** [comment]
@hasanbalci Pls check and close if OK
