### ISSUE TITLE
Error if pressed to arrow keys while text field is open to label a node  

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#62]
After a node is double clicked to label it, if arrow keys are pressed to move on the text, it gives error.
I think it tries to move the node as well, but it fails. 

Related to the text field that is opened on the node , when the label of a node is too long, a horizontal or vertical scrollbar appears on the text field but cannot be used. Maybe we can remove them.

**Comment by ugurdogrusoz** [comment]
@leonarddrv please assign an issue when resolved to the person who created the issue
@hasanbalci please verify and close if fixed

**Comment by hasanbalci** [comment]
It is ok now, thanks!

**Comment by hasanbalci** [comment]
I am not sure, whether this error emerged after the commits related to above mentioned problems, but now, while anything is selected and we press the arrow keys, it gives error in the console.

**Comment by leonarddrv** [comment]
@hasanbalci I don't know if the problem was present before but I made some changes on cytoscape.js-node-resize (unstable). I guess it should be fixed now.
