### ISSUE TITLE
Use of process in AF bug

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#620]
- Load an AF sample
- Try to directly create a process between two macromolecues
Notice how the connection points of AF edges get messed up:
![Screenshot 2020-10-05 151823](https://user-images.githubusercontent.com/3874988/95078578-0806aa80-071e-11eb-8ac4-bc7c869bbdd2.png)

**Comment by hasanbalci** [comment]
Interestingly, applying process creation between any two nodes in "Transforming growth factor .." sample affects only "TGFB receptor" node.

**Comment by ugurdogrusoz** [comment]
@hasanbalci looks good to me, please confirm

**Comment by hasanbalci** [comment]
It seems ok, thanks.
