### ISSUE TITLE
Resize undo is not batched

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#622]
If you select multiple nodes and resize all of them using the Object tab. Undo will not change all of them back to previous size (will do one by one).

**Comment by msalihaltun** [comment]
You also need to do an undo inbetween the resize operations that seems to do nothing. As in, you need to undo and see one node get back to the previous size, then undo and see nothing happening, then undo again to see another node get back to previous size.

**Comment by ugurdogrusoz** [comment]
- Check "Allow Compound Resize"
- Select the shown complex and the macromolecule
- Set width to 100
We get an error in the Console
![Screenshot 2020-10-07 160009](https://user-images.githubusercontent.com/3874988/95334172-72525300-08b6-11eb-9aa9-9fd046bb487a.png)
