### ISSUE TITLE
Resize to content with fit labels to node enabled

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#626]
When we resize nodes to content *after* node labels are already fit to nodes, we should not make labels long and at the same time see "..."s. Either the nodes should be resized as much as needed and fit labels to nodes should be disabled or the nodes should not be resized (assuming their labels already fit with ellipses). This can be observed at around 1:45 of the Newt advanced tutorial.

**Comment by ugurdogrusoz** [comment]
If "Fit Labels to Nodes" is checked, I think we can simply take the current displayed labels (with ellipses when too long) and figure out a size accordingly for the node when the user asks to resize nodes to content.

**Comment by msalihaltun** [comment]
There is a problem with cytoscape core regarding how node labels are edited when text wrapping with ellipsis is enabled. Corresponding issue is [here](https://github.com/cytoscape/cytoscape.js/issues/2761). When solved, it should solve the issue of nodes being resized to fit content but still leaving ellipsis in the label.

**Comment by msalihaltun** [comment]
There is another issue with this functionality that needs to be addressed. When "Resize Nodes to Content" is chosen from 'Edit' option in the top menu, the resized nodes are filtered by the following criteria:

- Nodes with class (logical OR, so at least one of): Process, Association, Dissociation, Source and Sink, And, Or, Not, Delay
- Parent nodes

Whereas when resizing to content with resize cues the above filtering does not take place.

**Comment by ugurdogrusoz** [comment]
Those nodes (filtered) are the ones without a user defined label. We should consistently leave them out of any resizing operations.

**Comment by hasanbalci** [comment]
@msalihaltun Please take into consideration the following issues about "Resize Nodes to Content" in 'Edit' menu: https://github.com/iVis-at-Bilkent/newt/issues/517 and https://github.com/iVis-at-Bilkent/newt/issues/591.

**Comment by msalihaltun** [comment]
As per #517, everything works correctly regarding "Resize Nodes to Content". The inconsistency of the menu option vs. the 'resize to content cue' came up briefly during discussion of the original issue, but they are working as intended.

**Comment by msalihaltun** [comment]
> There is a problem with cytoscape.js core regarding how node labels are edited when text wrapping with ellipsis is enabled. Corresponding issue is [here](https://github.com/cytoscape/cytoscape.js/issues/2761). When adressed, it should solve the issue of nodes being resized to fit content but still leaving ellipsis in the label.

The mentioned issue is resolved now and changes are reflected in our [fork](https://github.com/iVis-at-Bilkent/cytoscape.js). With this change, when nodes are resized after 'Fit Labels to Node' is enabled, they will go back to full size (technically, they already did but the full size with `ellipsis` style option didn't show full labels).
