### ISSUE TITLE
Shortcuts for selection

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#628]
Currently we have the following shortcut: tap hold on a node for selecting a node with its neighbors (in case of a PD map, it's the set of processes that this node is involved in).
Let's also add the following:
- tap hold on an edge for selecting the neighbors of the end nodes of the edge (if end nodes of e is a & b, then apply selection above to both end nodes and select their union)
- ctrl tap hold a node / edge for selecting all objects of this type (see Select Objects of This Type on context menus)

**Comment by msalihaltun** [comment]
Currently, `ctrl + tap` on nodes sets drag and drop mode which disables selection. Tap events fire before taphold events, so the 'Select Objects of This Type' functionality will not work with `ctrl + taphold`. In accordance, shortcut combination will be implemented as `alt + taphold` instead.
