### ISSUE TITLE
Error accessing simple chemical properties from ChEBI

### ISSUE THREAD

**Issue by msalihaltun** [iVis-at-Bilkent/newt#629]
When I load a sample from the menu (I ran into the issue with Neuronal Muscle Signaling sample loaded) and select a simple chemical, I see the following error on console. 

![image](https://user-images.githubusercontent.com/26147738/95751297-19fcc600-0ca7-11eb-9172-3da8256ef818.png)

The error says that Newt expected a `JSON` file from some operation but received a markup file (`XML` or `HTML`).

Upon closer inspection, when selecting a simple chemical, a fetch operation is triggered to receive some data from ChEBI. This fetch operation is broken, possibly on the ChEBI end since Newt expects the data in `JSON` format but it receives a document formatted in `HTML`.

**Comment by hasanbalci** [comment]
It seems that it's a temporary crash, so closing the issue.
