### ISSUE TITLE
Meta edge information is not saved when topology grouping is enabled

### ISSUE THREAD

**Issue by msalihaltun** [iVis-at-Bilkent/newt#630]
SIF maps are saved without information about meta edges that are created for topology grouping. 

#618 was created assuming all SIF maps had this problem but it occurs only when topology grouping is enabled. Anchor point information is saved for edges that are hidden when topology grouping is enabled, but they are lost on meta edges.

**Comment by ugurdogrusoz** [comment]
Let's resolve this problem by saving the current topology of a SIF model as is (including any compounds and meta edges created for topology grouping, style information of all edges with bends/control points, etc.) when persisted in .nwt format.

**Comment by ozgunbabur** [comment]
Found a bug in the implementation. When I save the below graph as .nwt

![image](https://user-images.githubusercontent.com/1376779/103293381-ce141000-49bd-11eb-9379-689f6edd27ba.png)

and reload it, I get the below the graph

![image](https://user-images.githubusercontent.com/1376779/103293434-ef74fc00-49bd-11eb-9990-d6973a4ccb9c.png)

The edge from AKT1 to IRS1 is missing in the graph. 

To duplicate this issue, use these .sif and .format files to generate the graph.
[sif-and-format.zip](https://github.com/iVis-at-Bilkent/newt/files/5751145/sif-and-format.zip)

First, load the .sif by File --> Import --> SIF.
Then load the .format by File --> Import --> SIF Style
Select the "Enable Topology Grouping of SIF" option in the Map panel.
Save and get the .nwt file
Load the same .nwt file to see that the edge between AKT1 and IRS1 is missing.

**Comment by ugurdogrusoz** [comment]
@ozgunbabur Please verify the fix in daily build

**Comment by ozgunbabur** [comment]
It works. Thanks.
