### ISSUE TITLE
Expand collapse cue won't respond to compound node resize undo/redo

### ISSUE THREAD

**Issue by msalihaltun** [iVis-at-Bilkent/newt#634]
This bug appeared in internal Newt after a recent fix in #632 and https://github.com/iVis-at-Bilkent/cytoscape.js-node-editing/issues/36.

Steps to reproduce:

1. Resize compound node (with handles or resize to content cue).
2. Undo and redo a bunch. The expand-collapse cue will not be redrawn each time.

It seems like expand-collapse extension doesn't listen for style changes on nodes and redraw the cue. Refreshing the cue on style event might be a fix.

**Comment by msalihaltun** [comment]
The problem actually exists in public version too, so it must not be related to the above.

**Comment by msalihaltun** [comment]
This should be fixed now, can you please verify @hasanbalci ?

**Comment by hasanbalci** [comment]
It seems ok, so closing.
