### ISSUE TITLE
Cell Designer "Conversion service is not available!"

### ISSUE THREAD

**Issue by rmtfleming** [iVis-at-Bilkent/newt#635]
Great piece of software. Very user friendly. One issue...
Why does this file not export to Cell Designer format?
Rename iDopa_hcys_L.c._v3.txt to iDopa_hcys_L.c._v3.nwt
[iDopa_hcys_L[c]_v3.txt](https://github.com/iVis-at-Bilkent/newt/files/5461920/iDopa_hcys_L.c._v3.txt)

**Comment by hasanbalci** [comment]
@rmtfleming Thanks for using our software! I think, conversion service was temporarily down, you should be able to convert your file now.

**Comment by rmtfleming** [comment]
Yes, it works.
