### ISSUE TITLE
Object properties inspector - label left justify

### ISSUE THREAD

**Issue by rmtfleming** [iVis-at-Bilkent/newt#637]
When a label is over a certain amount of characters in length, one cannot see the label, except in the network. One could left justify the label box so that a longer length label could be shown.

**Comment by ugurdogrusoz** [comment]
Let's make the value field for the labels *resizable* with the current default size. In case the user would like to see more of the label text without scrolling, they can do so. Something like this:
![Screenshot 2020-11-06 133432](https://user-images.githubusercontent.com/3874988/98356615-e8bcaf00-2034-11eb-889d-64799933ede2.png)

**Comment by ugurdogrusoz** [comment]
Could be verified in daily (unstable) build: http://ivis.cs.bilkent.edu.tr/
