### ISSUE TITLE
Object properties inspector - show the node id and compartment

### ISSUE THREAD

**Issue by rmtfleming** [iVis-at-Bilkent/newt#638]
The underlying id of the node and its compartment should be shown because the label can be the same for an identical metabolite, even though it is in two separate compartments.

**Comment by ugurdogrusoz** [comment]
The IDs are typically programmatically generated (as in Newt and many other tools). Hence, it wouldn't make sense to users. One can visually inspect the compartment that the node is in. If this is not possible, they could just click right outside the node to select the compartment and inspect as well.
If such customization is necessary in your case, you could fork the Newt repository and make the necessary changes in your own version.
