### ISSUE TITLE
Object properties inspector - process labels

### ISSUE THREAD

**Issue by rmtfleming** [iVis-at-Bilkent/newt#639]
It does not seem to be possible to view process labels? e.g. many biochemical reactions have names, but one cannot see the name associated with an edge/hyperedge.

**Comment by ugurdogrusoz** [comment]
SBGN PD does not associate a label or a description with a process. That's why we don't have them in Newt. We might however add a notes property to all our nodes and edges perhaps (as extensions) to enable users doing this kind of labeling.

**Comment by ugurdogrusoz** [comment]
I just remembered that we already have a "custom property" in the inspector:
![Screenshot 2020-11-17 154035](https://user-images.githubusercontent.com/3874988/99391444-42ea2980-28eb-11eb-81ba-93d88537d6d9.png)
