### ISSUE TITLE
Buggy behavior on anchor points after layout

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#641]
I have noticed two problems on the behaviour of anchor points after layout, probably related to each other. The first one is:

- Create two bend/control points on an edge.
- Apply layout, this will remove bend/control points from the edge visually.
- Right-click on the edge to open the context-menu, see "Remove All Bend/Control Points" item is still visible and clicking on it produces error in the console.

The second one:

- Create a control point on an edge.
- Apply layout, this will remove the control point from the edge visually.
- Now, try to add a control point again, this produces error in the console.
- This behaviour only occurs for control points, not for bend points.

**Comment by msalihaltun** [comment]
The first one is reproducable in public version as well, which means it existed before the latest breaking edge-editing release. Second one should be caused by something that happened after (or with) the release.
