### ISSUE TITLE
Problems with cloned perturbing agent/unspecified entity

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#642]
This can be seen as a continuation of the issue #574. I noticed a few more problems on the cloned perturbing agent and unspecified entity:

- [x] Open the first sample. Add a perturbing agent/unspecified entity. When you make it cloned, the entire background painted as clone marker.

- [x]  Add a perturbing agent/unspecified entity to an empty map. Add a background image and make it cloned. Then, the background image cannot be removed even cloned property is disabled.

- [x] It seems that the color of the clone marker for perturbing agent/unspecified entity is different than the color of the clone marker for other node types.

**Comment by msalihaltun** [comment]
I found another problem that is most likely related to any one of the above problems.

When I add a background image to any node, I can undo/redo as many times as I like and it will work. When I add background image and then clone Perturbing Agent/Unspecified Entity, undo'ing twice removes clonemarker and background image as expected but redo won't bring back the background image I originally added. Also, in the inspector, the background image seems like it is still there.

**Comment by msalihaltun** [comment]
This small fix should handle the first point.

**Comment by msalihaltun** [comment]
There is another problem, with background images and color schemes. Color scheme changes remove background images but in the inspector object menu it seems like the image is still there.

**Comment by msalihaltun** [comment]
I believe everything *should* be okay now.

**Comment by ugurdogrusoz** [comment]
@hasanbalci things look fine to me. Please verify.

**Comment by hasanbalci** [comment]
All problems seems to be solved except the last one @msalihaltun pointed: 

> There is another problem, with background images and color schemes. Color scheme changes remove background images but in the inspector object menu it seems like the image is still there.

Here are my steps to reproduce:

- Add a node to an empty map
- Add a background image to that node
- Change the color scheme to one of Solid options
- Background image is removed from the node but when I switch to Object tab, it seems like the image is still there.

**Comment by msalihaltun** [comment]
It appears that inspector is not updated on tab change, the update is tied to some events in `app-menu` instead.

**Comment by msalihaltun** [comment]
> There is another problem, with background images and color schemes. Color scheme changes remove background images but in the inspector object menu it seems like the image is still there.

When I made the above comment I was also referring to 3D and Gradient color schemes, but since those color schemes _are_ background images they appear as such in inspector regardless of previous background. The problem with solid color scheme should be solved now though.
