### ISSUE TITLE
Layout acting weird

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#643]
Notice that incremental layout acts weird sometimes (see below), I don't know if this is related to #640 though:
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/3874988/98942932-d2649680-24ff-11eb-8a34-956aa1b1ba97.gif)

**Comment by ugurdogrusoz** [comment]
Are these related? https://github.com/iVis-at-Bilkent/newt/issues/624

**Comment by hasanbalci** [comment]
This issue seems invalid anymore.
