### ISSUE TITLE
Wrong warning during edge reconnection

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#644]
When we create a connection between an association and any other valid node types (macromolecule, complex etc.) using a production edge, it is ok. However, when we keep the production edge from its reconnection handle in the arrow side and try to reconnect it to the same or a different valid node, it gives warning of "Invalid edge type!" and doesn't apply the reconnection.

**Comment by ugurdogrusoz** [comment]
@hasanbalci Can you provide the exact sequence of operations? Maybe this is because there can only be a single production and you're trying to create a second one and the issue is the number of such edges not its type?

**Comment by hasanbalci** [comment]
![Peek 2020-11-26 10-20](https://user-images.githubusercontent.com/22586369/100319656-0dbb9680-2fd1-11eb-97d6-8ee7c7b65bdd.gif)

**Comment by ugurdogrusoz** [comment]
@msalihaltun As you know if the map type is not hybrid we do make validation checks on whether or not the source and target of an edge is of a suitable type according to that map type (see Legends). Allowing initial creation but not reconnection is something that should never happen.

**Comment by hasanbalci** [comment]
Looks good to me. @ugurdogrusoz  Can you also please check in terms of validation of edge connections?
