### ISSUE TITLE
Remote launch from SBML model

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#648]
In relation to [this](https://github.com/iVis-at-Bilkent/newt/issues/496) issue, we would like to implement a facility for launching Newt with an SBML model (convert given SBML model automatically to SBGNML and load).

**Comment by msalihaltun** [comment]
We should be able to launch from sbml models now. 

Example link: ivis.cs.bilkent.edu.tr/?URL=https://www.ebi.ac.uk/biomodels/model/download/BIOMD0000000068.2?filename=BIOMD0000000068_url.xml

**Comment by ugurdogrusoz** [comment]
Launches nicely but I am not able to specify options such as "inferNestingOnLoad=true"!

**Comment by msalihaltun** [comment]
inferNestingOnLoad option should work now.

**Comment by ugurdogrusoz** [comment]
Great thanks
