### ISSUE TITLE
Review map properties used while launching from URI/URL

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#651]
We allow users to set some [map properties](http://newteditor.org/tutorials.html#remote-launch) while launching a map from URI/URL. I noticed that `enablePorts` and `compoundPadding` parameters given with URI/URL are not working correctly now and there may be some others as well. It will be good if all parameters are tested in this sense and problems related to them are fixed. A related issue with the `compoundPadding` parameter can be found [here](https://github.com/iVis-at-Bilkent/newt/issues/586).

Examples to launch with URI and URL:
URI: http://ivis.cs.bilkent.edu.tr/?URI=http://identifiers.org/reactome/R-HSA-6803211&enablePorts=true
URL: http://ivis.cs.bilkent.edu.tr/?URL=https://raw.githubusercontent.com/iVis-at-Bilkent/newt/master/app/samples/polyq_proteins_interference.nwt&compoundPadding=50&fitLabelsToNodes=true

**Comment by msalihaltun** [comment]
I have reviewed and fixed the parameters. I think they should be fine now, though there might be some cases I didn't test for, I'm not quite certain.

**Comment by hasanbalci** [comment]
@msalihaltun It seems that applying `compoundPadding` option after map is loaded doesn't produce good layouts, because in this case layout is applied before the map is updated with the `compoundPadding` information. Then compound paddings are adjusted, but this causes overlaps on nodes. I think this is one of the reasons why we tried to apply `compoundPadding` option before the map is loaded in iVis-at-Bilkent/newt#586. It can be seen in the following link: http://ivis.cs.bilkent.edu.tr/?URI=http://identifiers.org/reactome/R-HSA-6803211&compoundPadding=50

**Comment by ugurdogrusoz** [comment]
Let's address the problem @hasanbalci mentions. Looks good otherwise.

**Comment by hasanbalci** [comment]
It seems working now, thanks!
