### ISSUE TITLE
Filename dialog for SIF and image exports 

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#654]
Currently, user is allowed to change the filename via a dialog just before exporting the current map to various file formats except SIF and SIF Layout. It would be good to add this feature for SIF and SIF Layout export in terms of user experience and consistency. The same is valid for image exports as well.

**Comment by hasanbalci** [comment]
I added filename dialog for SIF and image exports. Can you please test and verify?

**Comment by ugurdogrusoz** [comment]
looks good to me
