### ISSUE TITLE
Background color lost on save/load

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#657]
I lost the background color of nodes when the below graph was saved as .nwt and reloaded.
![new_file (4)](https://user-images.githubusercontent.com/3874988/113870753-d9e05100-97ba-11eb-88b8-23b3de33b06d.png)

[new_file (5).nwt.txt](https://github.com/iVis-at-Bilkent/newt/files/6271770/new_file.5.nwt.txt)

**Comment by msalihaltun** [comment]
I made a mistake while trying to make sure the URL parameter applied the color scheme. Should be fixed now.
