### ISSUE TITLE
Remote launch from CellDesigner model and SIF

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#659]
We can implement a similar feature (similar to [this](https://github.com/iVis-at-Bilkent/newt/issues/648)) for CellDesigner as we already have a conversion facility for it as well.
Launching with SIF would also be rather useful.

**Comment by msalihaltun** [comment]
Launching with SIF style file as well as SIF file doesn't work because it creates a circular dependency between two files where one needs an object created by the other to function but the object is not created at the time of application launch / when URL is being evaluated.
