### ISSUE TITLE
PC query problems

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#661]
- [x] 1. If you perform a PC neighborhood query with HMGS2, you get "Invalid query"? There is nothing invalid about this query. Do we perhaps get no results and interpret that as invalid?
- [ ] 2. If you perform a neighborhood query with PMVK, it takes a while to get the result but the result is not properly laid out:
<img width="261" alt="Screen Shot 2021-04-16 at 11 54 13" src="https://user-images.githubusercontent.com/3874988/114999399-7f29b200-9eaa-11eb-9676-1296f79c98b0.png">
According to @hasanbalci this is since we perform "draft" quality layout when results are big.

**Comment by msalihaltun** [comment]
The first point is caused by empty response body, we check for `data.response.body` truth value and empty strings are evaluated as `false`. How should we fix this? Should we go ahead as normal or prompt the user that an empty response was received?

**Comment by ugurdogrusoz** [comment]
Let's properly notify the user that the response is empty rather than saying their query is invalid. Do not worry about the layout issue.
