### ISSUE TITLE
SBGN brick: Post-translational modification

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#664]
Let's implement this set now according to the guidelines, reusing as much code as possible where it makes sense.

**Comment by ugurdogrusoz** [comment]
I don't see the dropbox to determine the subtype (phosphorylation, etc.)?!
<img width="848" alt="Screen Shot 2021-05-04 at 19 18 40" src="https://user-images.githubusercontent.com/3874988/117036158-d1bdf780-ad0d-11eb-8a6d-58892054bb72.png">

**Comment by msalihaltun** [comment]
I can see them right now. Yours looks like yesterday's version somehow.

![image](https://user-images.githubusercontent.com/26147738/117048675-eb663b80-ad1b-11eb-8e31-26e956970555.png)

**Comment by ugurdogrusoz** [comment]
Based on the feedback from Alexander & Adrien, let's allow the user to:
- Add multiple modifications (row with dropdown box containing different types of modifications and the Residue field could be increased to be 1 or more), each having a possibly different modification (e.g. 2 phosphorylations and 1 methylation).
- We should get rid of the square brackets we have when there is a residue provided.
- I suggest we get rid of the checkbox for Residue and assume there is no residue when nothing is input to simply UI.
- Add a checkbox for Multimer to describe the input and output macromolecules (put this after Input & Output as checkbox in the middle of the row?).

**Comment by ugurdogrusoz** [comment]
- [ ] change multimer count infobox to "unit of information" (not "state variable")

**Comment by msalihaltun** [comment]
I will make another small change to dynamically change position after resize.

**Comment by msalihaltun** [comment]
I made the change now, it should be okay.

**Comment by ugurdogrusoz** [comment]
It'd be nice if auto-resize took the node label into account as well.

**Comment by msalihaltun** [comment]
Should be okay with https://github.com/iVis-at-Bilkent/chise.js/commit/148442f3e623c03201dc0456aa146b37767550e0

**Comment by ugurdogrusoz** [comment]
Thanks auto-resizing is working nicely now but as that happens we lose the vertical alignment (top-to-bottom layout):
![Screenshot 2021-05-17 114044](https://user-images.githubusercontent.com/3874988/118459931-e4203400-b704-11eb-932a-28a2dfb7b11c.png)

**Comment by msalihaltun** [comment]
Seems I overlooked the fact that I need to consider orientation as I reposition the nodes getting larger.
