### ISSUE TITLE
SBGN bricks: Association & Dissociation

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#668]
If the code is nicely reusable we could separate these two (two **separate** bricks). Notice that regulation is either stimulation or inhibition (a separate dropdown box).

**Comment by msalihaltun** [comment]
Association added now.

**Comment by ugurdogrusoz** [comment]
Association:
- Put the type of regulation *after* multimer checkbox and count (leave some space in between) as regulator name and type belong to the regulating node, whereas regulation type is related to the edge from the regulator node to the process.
