### ISSUE TITLE
Resize grapple bug when changing compound parent

### ISSUE THREAD

**Issue by royludo** [iVis-at-Bilkent/newt#67]
<img width="291" alt="image" src="https://user-images.githubusercontent.com/7210995/27014065-566bfd8a-4ef1-11e7-91a4-5972d08b8279.png">

The kind of result as above is obtained when moving compounds with an even number of children. It's okay if the number of children is odd...

**Comment by kinimesi** [comment]
Looks like it got introduced after https://github.com/iVis-at-Bilkent/cytoscape.js-node-resize/pull/13

**Comment by royludo** [comment]
@kinimesi 
The addition of this line:
https://github.com/iVis-at-Bilkent/cytoscape.js-node-resize/commit/439d30c43e5721f114dccf59ac9b0775ea9a5064#diff-ca46d02dc61561651c567bd69d6d336fR931

makes this bug disappear. The way I understand it, there may be a problem with the position being cached, and not being updated. That leads to this issue. By adding the previous line, and calling the position() function, it somehow updates the cache. The position becomes accurate, and so the grapples can be drawn correctly.

**Comment by kinimesi** [comment]
This bug was not there before konva implementation. We should find the bug and fix it **properly**.

**Comment by royludo** [comment]
@kinimesi agreed.

**Comment by royludo** [comment]
As pointed out by @kinimesi, this problem still occurs when one of the node inside the complex has a unit of info or state variable.
