### ISSUE TITLE
Style properties not read correctly if value is zero

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#674]
While reading style properties of the graph elements, if the property value is zero it is ignored because of the buggy code [here](https://github.com/iVis-at-Bilkent/newt/blob/dcf284cbae6a985ceb3ed3431faa5996281c79a3/app/js/app-utilities.js#L2205). That if statement should differentiate "0" value from "undefined". As a result, those properties are not written to the file during save operation.

**Comment by hasanbalci** [comment]
I encountered with a similar issue in infobox values. Apparently, if there is an infobox with value 0, it's saved in the file, but while loading, those values are lost somewhere and infoboxes seem as empty. Probably, there is a similar bug during load operation.

**Comment by ugurdogrusoz** [comment]
@msalihaltun See if this straightforward to fix for this release. @hasanbalci should know.

**Comment by msalihaltun** [comment]
Nodes with label "0" are saved but can't be reloaded either.

In javascript, if we use the value `0` as a predicate inside an if statement (or anything similar) the value is evaluated as false. This is likely the reason for these problems. When we are reading value fields from files, we can't do truth checks with those values. We just need to make sure we don't get `undefined`.

**Comment by msalihaltun** [comment]
"0" style values should be fixed now but labels are not fixed. We take the nwt file as an xml file while loading and call `libsbgnjs.Sbgn.fromXML()` on this file. This function returns label text value as `undefined` when we use "0" as label.

**Comment by msalihaltun** [comment]
Nevermind, apperantly my changes had many unexpected side affects. Reverted for now. It is my mistake, I didn't run the tests locally.

**Comment by msalihaltun** [comment]
It should be fine now. @hasanbalci please test and confirm.

**Comment by msalihaltun** [comment]
Also I created an issue about label values [here](https://github.com/sbgn/libsbgn.js/issues/10).

**Comment by hasanbalci** [comment]
- I assume that the problem with label values includes both node labels and infobox labels, so they will be fixed in libsbgn.js.
- I noticed that when we set "Border Width" to 0 for a node, after save/load, that field in inspector becomes empty for that node instead of 0. I think we should show 0 again.

**Comment by msalihaltun** [comment]
- I believe so yes, it should be solved in libsbgn.js.
- We had the same problem with border width value as all others where 0's truth value is evaluated as false, fixed now.

**Comment by hasanbalci** [comment]
Labels will be fixed in libsbgn.js. The rest seems fixed, so closing.
