### ISSUE TITLE
Error loading preferences file

### ISSUE THREAD

**Issue by msalihaltun** [iVis-at-Bilkent/newt#676]
Happens in public version as well. Realized when applying Youtube tutorials. I can see an error in the console while loading the following preferences file: 

[mapk_cascade.newtp.txt](https://github.com/iVis-at-Bilkent/newt/files/6663154/mapk_cascade.newtp.txt)

#675

**Comment by ugurdogrusoz** [comment]
When I tried to open the following preferences on a newly loaded Newt page with an empty canvas, I get an error:
Uncaught TypeError: Cannot read property 'length' of undefined
    at bundle.js:10701
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.<anonymous> (bundle.js:10632)
    at HTMLDocument.dispatch (bundle.js:77445)
    at HTMLDocument.elemData.handle (bundle.js:77253)
[vitamins_b6_activation_to_pyridoxal_phosphate_newtp.txt](https://github.com/iVis-at-Bilkent/newt/files/6667692/vitamins_b6_activation_to_pyridoxal_phosphate_newtp.txt)
