### ISSUE TITLE
Interactive resize does not update dimension in inspector

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#68]
When you resize a node interactively, you expect that the dimensions in the inspector are updated accordingly but they aren't. This must have been introduced recently (was fine during my demo with June 6 build).

**Comment by ugurdogrusoz** [comment]
@royludo Could this be related with replacement of ocanvas?

**Comment by royludo** [comment]
@ugurdogrusoz is is likely. I'll take a look.
