### ISSUE TITLE
Solid color scheme not loading

### ISSUE THREAD

**Issue by SelbiEreshova** [iVis-at-Bilkent/newt#689]
On unstable branch saving maps with solid color scheme and uploading them back to newt gives an error.

Try this:
- Open first PD sample
- Change color scheme to solid
- Save the file
- Load this file back to Newt

**Comment by ugurdogrusoz** [comment]
Might be related to #708 item 1.

**Comment by okg21** [comment]
I believe this bug has been introduced with this commit for fixing https://github.com/iVis-at-Bilkent/newt/commit/e9666554593dc79688a61add64984148b470d2ea #574. 
Actions to remove background image related style properties have been added. And these fields are saved to the file with empty('') values. For the following properties: 
['background-fit', 'background-image-opacity', 'background-position-x', 'background-position-y', 'background-height', 'background-width'] 

Having empty fields in the saved file results in NaN values when parsed. And cytoscape's style does not accept these NaN values.

Removing these actions fixes this bug, without the clone marker bug mentioned on the #574 reappearing and undo does not take two times. But I wonder if we do lose any utility in this case.

Another solution is checking for NaN values before applying node.style(). But this seems like a bad practice.

**Comment by ugurdogrusoz** [comment]
Let's try reverting the incorrect parts of the mentioned commit. We'll test it thoroughly later.

**Comment by okg21** [comment]
I committed a fix for the clone marker bug. Now color schemes are loading correctly. And clone marker bug for unspecified entity and perturbing agent is fixed.

**Comment by ugurdogrusoz** [comment]
All samples are loading as **solid** right now. Most should be 3D or gradient.

**Comment by ugurdogrusoz** [comment]
@okg21 When we load a sample, the color scheme is incorrect. Let's first fix that so we can see if this original issue is fixed.
The picture below is what we get when we load the first PD sample; what's wrong is red, whereas what is correct is in green:
<img width="589" alt="Screenshot 2024-06-20 at 17 40 33" src="https://github.com/iVis-at-Bilkent/newt/assets/3874988/8aa63085-ecaf-43ca-ba7c-0ebc279e6846">

**Comment by okg21** [comment]
With the latest rebuild color schemes are displayed correctly on unstable. 
![ScreenRecording2024-06-26at14 11 17-ezgif com-video-to-gif-converter](https://github.com/iVis-at-Bilkent/newt/assets/24496613/3db784f7-98aa-42f0-b3e6-c0abe3a398bf)
