### ISSUE TITLE
SBML samples in Newt

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#692]
Let's add a couple of samples under File > Samples with title "_SBML_":

1) The sample in Syblars: http://syblars.cs.bilkent.edu.tr/. Import this into Newt, automatically and/or manually create a nice layout and save as a sample.

2) Another one that I'm going to attach here later on.

**Comment by hasanbalci** [comment]
Let's enrich the SBML samples to include more node and edge types. Currently, they only include compartment, simple molecule and process as node type and consumption, production and catalysis as edge type.
