### ISSUE TITLE
Error on saving imported sbml file 

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#695]
When we export an sbml file and try to save it as a nwt file, it gives error which can be seen in the developer console.

Edit: When I try to import below sbml file, it also gives an error. (This is the sample sbml file used in syblars.)

 
[SBML_Sample.sbml.txt](https://github.com/iVis-at-Bilkent/newt/files/11120312/SBML_Sample.sbml.txt)

**Comment by ugurdogrusoz** [comment]
Now when I import the attached above sample and save it (as .nwt) and load it back, I do not get the complex members back:
![SBML_Sample sbml (1)](https://user-images.githubusercontent.com/3874988/229468770-c7351a0a-5a00-415a-b826-b2187f9019e7.png)

**Comment by NoorMuhammad1** [comment]
@ugurdogrusoz I have fixed the bug. The problem was with sbgnviz. Can you please check?
