### ISSUE TITLE
Select all nodes and/or edges

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#7]
In cases the user would like to select all objects, all nodes or all edges, they should be able to do that under the View menu as follows:

View >
    Select >
        All Nodes and Edges (Note that Ctrl/Cmd-A already provides a shortcut for this)
        All Nodes
        All Edges

Select should go as the first operation of the View menu.

**Comment by royludo** [comment]
Implemented in 66d0200d09523e5e6a55f51c7740154aa6a9d1bb

**Comment by ugurdogrusoz** [comment]
Great. I think we should deselect what's currently selected before each of these.
