### ISSUE TITLE
Increase complex corners as paddings allow

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#70]
Now that we have more paddings around complexes due to expand-collapse cues and complex name labels, we should be able to increase the amount of cut off in complex corners to make them more distinguishable.

**Comment by ugurdogrusoz** [comment]
Can we increase the corner sizes as much as the minimal paddings of complexes? In other words, if the complex padding is 10 units at the least (without infoboxes, name being displayed, etc.), then the corners should be cut off 10 units before the corner (i.e. the isosceles triangle formed by the cutoff would have dimensions 10x10xsqrt(2)10 ).

**Comment by ugurdogrusoz** [comment]
Actually we might be able to increase the cutoff even more:
![complex-new-cutoff](https://user-images.githubusercontent.com/3874988/27074056-95190486-502e-11e7-81a1-f6c5832ca1a9.png)
New cutoff location: What I described earlier
Alternative 1: maximum cutoff we can have
Alternative 2: more moderate one
So, maybe we should try Alternative 2 and if it's reasonable (complexes can be differentiated from other shapes at 100% zoom level easily), then that's it. Otherwise, we might go with Alternative 1 as well.

**Comment by ugurdogrusoz** [comment]
This is perfect. However, clipping isn't adjusted to the new corners (edge arrow doesn't go all the way to the corner of the complex as it used to be):
![image](https://user-images.githubusercontent.com/3874988/27178888-ba20dc84-51d4-11e7-9472-0f7af09256df.png)

**Comment by ugurdogrusoz** [comment]
Let's also slightly decrease the cutoff amount since when the complex is not named (or Display Labels for Named Complexes is off), members almost touch the corners:
![image](https://user-images.githubusercontent.com/3874988/27179238-5c373436-51d6-11e7-8cfd-535d76ba762b.png)

**Comment by kinimesi** [comment]
@ugurdogrusoz I think we do not add extra padding to complexes due to *expand-collapse cues*.

**Comment by ugurdogrusoz** [comment]
As far as I know we only changed cahanged cutoff amount not paddings
