### ISSUE TITLE
Removing submaps/compartments is not possible

### ISSUE THREAD

**Issue by micwij** [iVis-at-Bilkent/newt#700]
I was using the web-application (https://web.newteditor.org/#) and I think it would be great if it was possible to remove submaps/compartments, without deleting the elements which are enclosed by it. It seems also not possible to copy something out of a submap/compartment and paste it into a different submap/compartment or just "outside" the submap/compartment. This means that once you set a submap/compartment, it is permanent and there is no way of changing this post hoc. I think being able to change this afterwards would greatly improve the reusability of PD maps.

**Comment by ugurdogrusoz** [comment]
@micwij It **is** possible to move elements in a compartment out (select them and Cntrl/Cmd drag them outside).
To duplicate a sub-pathway outside a compartment or in another compartment, you may copy-paste and then transfer as described above.

**Comment by micwij** [comment]
That is great! Thank you so much for the quick reply. I see now, it is also written in the quick help.
