### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#702]
- Update README to provide new paper specifics
- Remove SBGNViz paper from README for citation
- Add the following text to About box right before third party library paragraph **and** under Quick Help right before contact paragraph at the end:
    Please cite: Balci et al. [Newt: a comprehensive web-based tool for viewing,constructing, and analyzing biological maps](https://doi.org/10.1093/bioinformatics/btaa850), Bioinf., 37(10), pp.1475-1477, 2021.

**Comment by hasanbalci** [comment]
Done.
