### ISSUE TITLE
conversion of SBGN -> SBML not working

### ISSUE THREAD

**Issue by fbergmann** [iVis-at-Bilkent/newt#707]
During HARMONY we noticed, that the conversion of SBGN file to SBML with layout / render is currently not working in the deployed newteditor. Error messages come from the minerva API calls: 

```
[Error] Failed to load resource: the server responded with a status of 415 () (SBGN-ML:SBML, line 0)
[Error] Failed to load resource: the server responded with a status of 524 () (validateSBGNML, line 0)
[Error] Error during file validation – "error" – ""
```

going to <https://minerva-service.lcsb.uni.lu/minerva/api/convert/SBGN-ML:SBML>

**Comment by ugurdogrusoz** [comment]
This used to work fine. Let's check what's wrong (Minerva service down or was relocated or something else).

**Comment by ugurdogrusoz** [comment]
@fbergmann Can you please check again in our release candidate [here](http://newt.cs.bilkent.edu.tr/)?

**Comment by fbergmann** [comment]
The SBML export is working in that version, though it does not export the layout, which was what i was looking for. Thank you so much though.

**Comment by ugurdogrusoz** [comment]
@fbergmann Can you perhaps provide us the exact file you're loading and trying to export to SBML (File > Export > SBML)?

**Comment by fbergmann** [comment]
@ugurdogrusoz I'll add all the files here ... I'm not sure it is dependent on any of the files. The original purpose was just for me to see the state of support for SBML Layout / Render with newt. (needed to zip the files since xml cant be attached)

[brusselator-sbml.zip](https://github.com/user-attachments/files/15897344/brusselator-sbml.zip)

**Comment by ugurdogrusoz** [comment]
When testing with the provided files, I found out that:
- If they are imported as SBML (File > Import > SBML), we get an error in the Console
- If they are imported as CellDesigner (File > Import > CellDesigner), we get "Conversion service is not available"
Let's investigate both.

**Comment by ugurdogrusoz** [comment]
We will handle this as part of the general import/export issue #712. So closing this.
