### ISSUE TITLE
Newt 4 issues

### ISSUE THREAD

**Issue by NoorMuhammad1** [iVis-at-Bilkent/newt#708]
Upon my testing of the current unstable branch of newt, I have encountered the following issues:

- [x] 1. [@okg21] Color scheme not being properly loaded for sample maps.
- [x] ~~2. [@NoorMuhammad1] SBGN bricks not working for Association. Can also test for other types as well.~~

If anybody finds any other issues or bugs please add it here.

**Comment by NoorMuhammad1** [comment]
No that is precisely the issue that the options that we see in the video
are not available when we run the application. To be more specific, There
is no option to select simple molecule from the menu in SBGN brick. That is
what I was referring to.

**Comment by umut-er** [comment]
Same issue with: 
metabolic reaction (input/outputs fields should include macromolecules)
dissociation (input/outputs fields should include simple chemicals)
degradation (input/outputs fields should include simple chemicals)

**Comment by ugurdogrusoz** [comment]
@amazein @adrienrougny can you please check [this release candidate](http://newt.cs.bilkent.edu.tr/) for Newt 4 in regards to our requirements for what input/outputs for above mentioned SGBN bricks should be (see under Edit > Add Using SBGN Bricks..)?

**Comment by NoorMuhammad1** [comment]
I checked and the SBGN bricks modal works and is following all the specified rules.

**Comment by ugurdogrusoz** [comment]
> @amazein @adrienrougny can you please check [this release candidate](http://newt.cs.bilkent.edu.tr/) for Newt 4 in regards to our requirements for what input/outputs for above mentioned SGBN bricks should be (see under Edit > Add Using SBGN Bricks..)? We might have changed these when we extended the support for SBGN bricks.
> 
> [Specs](https://docs.google.com/spreadsheets/d/1vjDXAbS2GEUwBZ1ytjO3dytnVQloxEP3xhg_KuzwVaE/edit?usp=sharing) we had prepared earlier.

@NoorMuhammad1 checked and things looked fine according to [this document](https://docs.google.com/spreadsheets/d/1vjDXAbS2GEUwBZ1ytjO3dytnVQloxEP3xhg_KuzwVaE/edit?usp=sharing)

**Comment by okg21** [comment]
With this PR on sbgnviz https://github.com/iVis-at-Bilkent/sbgnviz.js/pull/219, the color scheme issue for samples is fixed.
