### ISSUE TITLE
Invalid query error

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#709]
Query > Pathway Commons > Paths Between..

If I enter:
BRCA1
BRCA2

It works find. But if I type:

PTEN
BRCA1

I get an error: "Invalid query"

**Comment by NoorMuhammad1** [comment]
What is the output we are expecting?

**Comment by ugurdogrusoz** [comment]
Some map similar to the one that works should be displayed in the canvas

**Comment by NoorMuhammad1** [comment]
![image](https://github.com/iVis-at-Bilkent/newt/assets/48602830/0529bddc-03e4-4415-b195-eb4b10c34ac0)
So I debugged the issue and the API that is being used for this query is returning an empty output for the given inputs. I mentioned the outputs of both BRCA1 to BRCA2 query as well as the PTEN to BRCA1 query as well.

**Comment by ugurdogrusoz** [comment]
Maybe you can try the same query directly in [pathway commons web site](https://www.pathwaycommons.org/)?

**Comment by NoorMuhammad1** [comment]
So I checked the website, and there is not output for those input on that website too. I checked the following documentation they provided on the website:
https://www.pathwaycommons.org/pc2/swagger-ui.html#!/biopax45model45controller/graphQueryUsingGET

For Source: BRCA1 and Source:BRCA2, it gives the same output as in Newt.
But for Source:PTEN and Source BRCA1, it gives not output just like in Newt.

**Comment by umut-er** [comment]
Apparently empty query result table only exists for queries of type neighborhood. Is this intended or accidental? See relevant code section below (from backbone-views.js):
```js
success: function(data){
          if (!data.error && data.response.statusCode == 200 && data.response.body) {
            var xml = $.parseXML(data.response.body);
            $(document).trigger('sbgnvizLoadFile', [ filename, cy ]);
            currentGeneralProperties.inferNestingOnLoad = false;
            chiseInstance.updateGraph(chiseInstance.convertSbgnmlToJson(xml), undefined, currentLayoutProperties);
            currentGeneralProperties.inferNestingOnLoad = currentInferNestingOnLoad;
            chiseInstance.endSpinner('neighborhood-spinner');
            $(document).trigger('sbgnvizLoadFileEnd', [ filename, cy ]);
          }
          else if (data.response.body === "") {
            new PromptEmptyQueryResultView({el: '#prompt-emptyQueryResult-table'}).render();
            chiseInstance.endSpinner('neighborhood-spinner');
          }
          else {
            new PromptInvalidQueryView({el: '#prompt-invalidQuery-table'}).render();
            chiseInstance.endSpinner('neighborhood-spinner');
          }
        },
```

**Comment by ugurdogrusoz** [comment]
When a query result is empty, it is not the same as a query being invalid. A query is typically invalid when for instance a gene symbol is incorrect or contains invalid symbols, etc. So, in cases where it's empty, we should display a proper message.

**Comment by ugurdogrusoz** [comment]
@NoorMuhammad1 Let's check all the queries and have consistent messaging. The rules should be as follows:
- If the query has an error, then we display an error message
- If the query is valid but returns an empty result, then we display an appropriate message
For instance, right now if you choose BRCA1 as source and PTEN as target for 'Paths From To Query', again we get an error message, whereas it should be an empty result message.

**Comment by ugurdogrusoz** [comment]
With current Newt when I type rubbish as a gene name (see below), I get invalid query (which is true). With 4.0, however, I get no results found. Under what conditions is a query invalid?

![image](https://github.com/iVis-at-Bilkent/newt/assets/3874988/8fa81de6-85b2-42cf-a36b-a367d61af105)

**Comment by umut-er** [comment]
Maybe I can shed some light on this issue. Below is the result for the paths between BRCA1 and PTEN (we know this is empty):
```json
{
    "error": null,
    "response": {
        "statusCode": 200,
        "body": "",
        "headers": {
            "server": "nginx/1.16.1",
            "date": "Wed, 12 Jun 2024 19:58:40 GMT",
            "content-type": "application/xml",
            "content-length": "0",
            "connection": "close",
            "access-control-allow-origin": "*"
        },
        "request": {
            "uri": {
                "protocol": "http:",
                "slashes": true,
                "auth": null,
                "host": "www.pathwaycommons.org",
                "port": 80,
                "hostname": "www.pathwaycommons.org",
                "hash": null,
                "search": "?format=SBGN&kind=PATHSBETWEEN&limit=1&source=PTEN&source=BRCA1",
                "query": "format=SBGN&kind=PATHSBETWEEN&limit=1&source=PTEN&source=BRCA1",
                "pathname": "/pc2/graph",
                "path": "/pc2/graph?format=SBGN&kind=PATHSBETWEEN&limit=1&source=PTEN&source=BRCA1",
                "href": "http://www.pathwaycommons.org/pc2/graph?format=SBGN&kind=PATHSBETWEEN&limit=1&source=PTEN&source=BRCA1"
            },
            "method": "GET",
            "headers": {}
        }
    }
}
```
and here is the result for garbage input:
```json
{
    "error": null,
    "response": {
        "statusCode": 200,
        "body": "",
        "headers": {
            "server": "nginx/1.16.1",
            "date": "Wed, 12 Jun 2024 19:58:48 GMT",
            "content-type": "application/xml",
            "content-length": "0",
            "connection": "close",
            "access-control-allow-origin": "*"
        },
        "request": {
            "uri": {
                "protocol": "http:",
                "slashes": true,
                "auth": null,
                "host": "www.pathwaycommons.org",
                "port": 80,
                "hostname": "www.pathwaycommons.org",
                "hash": null,
                "search": "?format=SBGN&kind=PATHSBETWEEN&limit=1&source=aafsefsef&source=afawawdw",
                "query": "format=SBGN&kind=PATHSBETWEEN&limit=1&source=aafsefsef&source=afawawdw",
                "pathname": "/pc2/graph",
                "path": "/pc2/graph?format=SBGN&kind=PATHSBETWEEN&limit=1&source=aafsefsef&source=afawawdw",
                "href": "http://www.pathwaycommons.org/pc2/graph?format=SBGN&kind=PATHSBETWEEN&limit=1&source=aafsefsef&source=afawawdw"
            },
            "method": "GET",
            "headers": {}
        }
    }
}
```
as you can see, PathwayCommons generates exactly the same response (which is a response with status code 200 and an empty body) in both cases. So, there is no way of knowing why the query failed (invalid input or no result found) from the return values alone. There needs to be some additional verification of whether these genes/proteins actually exist in the database.
I hope this was helpful.

**Comment by ugurdogrusoz** [comment]
Observation: special symbols like *, %, +, etc. are apparently cleaned up before usage.

Now we do have proper messaging. However, for some reason, the spinner gets stuck even though the query is complete and results are displayed (not the behavior we have with the public Newt). I suspect this might be related to this fix by @NoorMuhammad1  or highlighting implemented by @umut-er.
