### ISSUE TITLE
GPML elements in Palette

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#718]
Node and edge types to be supported include DataNodes, Interactions and Shapes:
[DataNodes](https://pathvisio.org/pathvisio-book/data-nodes.html#data-nodes):

<img width="480" alt="Screenshot 2024-06-21 at 07 47 02" src="https://github.com/iVis-at-Bilkent/newt/assets/22586369/1d3797fa-de8f-41ea-8442-521e51936bb3">

[Interactions](https://pathvisio.org/pathvisio-book/interactions.html#interactions): 

<img width="479" alt="Screenshot 2024-06-21 at 07 47 18" src="https://github.com/iVis-at-Bilkent/newt/assets/22586369/5d03500d-679b-479e-b19a-acbea8e1766b">

[Shapes](https://pathvisio.org/pathvisio-book/shapes.html#shapes):
Here we may skip line, arc and brace for now because Cytoscape.js doesn’t allow such shapes. 

<img width="486" alt="Screenshot 2024-06-21 at 07 47 31" src="https://github.com/iVis-at-Bilkent/newt/assets/22586369/7f18490b-413e-429b-8b83-d26a6d69a5d6">

We need to add these items as svg images (a new svg image for each node/edge) to Palette as a new section under the title “GPML” after the SBML section. For now let’s skip the titles in above images such as Molecular DataNodes etc. and try to place svg images in line with current UI convention. We can separate DataNodes, Interactions and Shapes with straight line separators as we do in other sections and we can separate subcategories with a dashed line separator. The actual images should go to newt/app/img/nodes and newt/app/img/edges folders in Github repo.

We may use draw.io or inkscape to draw these shapes and export as svg. Please keep the source files as they may be needed to draw actual shapes on canvas as well (at least coordinates). For the interactions and some complex shapes, there are some svgs [here](https://github.com/wikipathways/pvjs/tree/fb321e5b8796ecc3312c9a604f75b7ace94a81aa/src/themes/markers) and [here](https://github.com/wikipathways/pvjs/tree/fb321e5b8796ecc3312c9a604f75b7ace94a81aa/src/themes/symbols). I think they are not drawn as directly but the coordinates inside the svgs may be helpful to draw them.

**Comment by hasanbalci** [comment]
Let's name new svg images with their full names such as gene-product.svg, disease.svg etc. If there is already an image with same name, please add "-gpml", e.g. RNA-gpml.svg.

**Comment by SainiAditya1** [comment]
@hasanbalci  I've made the changes in this commit [be960d1](https://github.com/iVis-at-Bilkent/newt/commit/be960d1f0a52175dc950ef11a6d19484145d41d5).  Please check it .

**Comment by hasanbalci** [comment]
@SainiAditya1 Thanks Aditya! I added a few more improvements above.

**Comment by SainiAditya1** [comment]
@hasanbalci , I have  made the changes in this commit  (https://github.com/iVis-at-Bilkent/newt/commit/7b1421c7adc4e64ab80f673ec4facfd2a5914443) .Please check it again.

**Comment by hasanbalci** [comment]
Hi @SainiAditya1, can we increase the resolution of EndoplasmicReticulum and SarcoplasmicReticulum as the final step in this issue (similar to GolgiApparatus and Mitochondria)? Then I will close the issue. 
<img width="248" alt="Screenshot 2024-06-30 at 18 25 26" src="https://github.com/iVis-at-Bilkent/newt/assets/22586369/7f285435-c18c-4c9d-bc56-a23807f5928d">

**Comment by SainiAditya1** [comment]
Hi @hasanbalci , I have increased the resolution of EndoplasmicReticulum and SarcoplasmicReticulum. Please find the changes in this commit [cd78f02](https://github.com/iVis-at-Bilkent/newt/commit/cd78f02cf58349e94e3637ece62504bfbe299837).

**Comment by hasanbalci** [comment]
I cannot see any change:
<img width="244" alt="Screenshot 2024-07-01 at 07 39 38" src="https://github.com/iVis-at-Bilkent/newt/assets/22586369/2acd9549-f01e-4939-86d9-91077ee48813">

**Comment by SainiAditya1** [comment]
@hasanbalci , I have made the changes in this commit (https://github.com/iVis-at-Bilkent/newt/commit/b1a073a2ee43ce5f3572fc45677721897b6e9eb5)
