### ISSUE TITLE
Remove redundant processes from query results

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#722]
Since Pathway Commons is a database with contents from several prominent pathway databases, there are often redundancies in the data. Hence, we would like to give the user a chance to not see these. Let's add a new option `Remove Redundant Processes` in query dialogs, which is `true` by default. When true we would fine and delete redundant processes from the query result before laying out and presenting it to the user. Examples from 1-neighborhood of ANK1, four instances of the same process:
<img width="870" alt="Screenshot 2024-07-01 at 13 53 40" src="https://github.com/iVis-at-Bilkent/newt/assets/3874988/6b8df92e-97d3-436e-b333-7dd71b98d3b3">

Here are the rules for deciding whether or not two processes are redundant:
- The *type* and *compartments* of the two processes are the same, and
- The *number*, *types*, *compartments*, and *labels* of all their (the two processes') substrates (input), products (output), and effectors (modulation, stimulation, catalysis, etc.) are the same.

This should be done **before** removal of the disconnected nodes if enabled.

**Comment by umut-er** [comment]
This is not fully complete, but here is the current version working on the same query:


<img width="1078" alt="image" src="https://github.com/iVis-at-Bilkent/newt/assets/102927626/9ded391c-501c-411a-bbaa-e68d3e6601cf">


It removes a significant amount of nodes that have very similar structure, which can be seen on the left side of this picture (the only query type that seems to generate a huge number of those is the neighborhood query). As a result, the structure of the remaining graph seems to be a little weird. Do we perform layouts on these queries? Maybe we should do that after the deletions.

**Comment by umut-er** [comment]
So, here is what I decided to do. For every process, I calculate a string that uniquely determines the neighborhood of the process. Here is what I do:
1. Start with an empty hashmap. Arrange all the nodes that connect to the process in lexicographical order (this is the most expensive operation in this list)
2. Start with descriptorString = "". Iterate over the array constructed in step 1. Every time, add the label of the node and the class of the edge connecting that node to the process to the descriptor string. At the end, append the class of the process.
3. Check if this string exists in the hashmap. If it doesn't, add it. If it does, add this process to the deletion list.
4. Remove all the items in the deletion list.
Let me do an example. Here is an example process:


<img width="442" alt="image" src="https://github.com/iVis-at-Bilkent/newt/assets/102927626/aebbaab3-3f7f-43e9-be8d-a377ebb1c8d6">


Arranging the nodes in lexicographical order we get ["AB", "BC", "CD"]. Iterating over this we first append `ABconsumption` and then append `BCinhibition` and then append `CDconsumption` to the descriptorString. We have  descriptorString = `ABconsumptionBCinhibitionCDconsumptionprocess` as the final string. We check for this string in the hashmap.

Let me know if this makes sense / is a good approach. There are also a couple of things that I will address. First of all, this obviously discards parent information. I will add that also to the desriptorString. There also exists an edge case. Consider this:


<img width="433" alt="image" src="https://github.com/iVis-at-Bilkent/newt/assets/102927626/94f14928-84bb-484c-90b6-71061e59a9b5">
  
  
In the code, the sort algorithm doesn't distinguish between the edges if the nodes are the same. So, both `ABconsumptionABinhibitionCDconsumptionprocess` and `ABinhibitionABconsumptionCDconsumptionprocess` are valid descriptors for this neighborhood. I will fix this by also including the edge class as a tie-breaker in the sort algorithm.

**Comment by ugurdogrusoz** [comment]
This is along the lines I was thinking. Coding each process can be done more efficiently I think by simple mappings (e.g. 1 for consumption edges, 2 for product edges, etc. or 1 for macromolecules, 2 for simple chemicals, etc.). A process can be defined by its type, followed by its substrates (in lexicographic order), followed by its products, followed by its effectors.

**Comment by umut-er** [comment]
This should be ready for review. It is on the internal server.

I have done some tests and removed the time limit on queries (30 seconds) to get the 1-neighborhood of ANK1 ANK2 ANK3, which returned at around 60 seconds (note that this is only the API response and doesn't include the time to render the graph). It has ~650 processes. The redundancy removal took something like 650 milliseconds with the current algorithm, which should be adequate. Note that our software can't even properly edit a graph of this size (the software slows down significantly).

**Comment by ugurdogrusoz** [comment]
Well done @umut-er !
