### ISSUE TITLE
Pathway Commons query issues

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#724]
We still have issues with our queries. Let's find out why these are happening:
- When you perform a **common stream** query with BRCA1 and BRCA2, we get an error (Invalid query!)
- Similar result when you perform a **neighborhood** query with ANK1 and PTEN.
I can understand no results but these queries should be valid since both gene names are valid.

**Comment by NoorMuhammad1** [comment]
I checked the error, and the problem is that for the requests of common stream query and neighborhood with these inputs (BRCA1 and BRCA2), the API responds back with Internal Server Error(status code 500). I have added a new modal to show the user this error.
![image](https://github.com/iVis-at-Bilkent/newt/assets/48602830/3fa129f7-768e-4d05-8515-42ed739a3540)

**Comment by IgorRodchenkov** [comment]
Confirmation, example query (with "message" param for debugging): 
```
curl -X 'GET' \
  'https://www.pathwaycommons.org/pc2/graph?source=BRCA1&source=BRCA2&limit=1&format=SBGN&kind=COMMONSTREAM&message=true' \
  -H 'accept: */*'
```

So quick-fix here would be to add direction=downstream or upstream... 
Or, should there be a default?

**Comment by ugurdogrusoz** [comment]
I confirm that the common stream problem is now fixed (see https://github.com/PathwayCommons/cpath2/issues/320). Thanks @IgorRodchenkov.

**Comment by IgorRodchenkov** [comment]
I rebuilt the cpath2/pc2 image and restarted the service... The neighborhood for PTEN as SBGN hould be now fixed too.

**Comment by ugurdogrusoz** [comment]
The neighborhood query also seems to be fixed; though a neighborhood query with ANK1 and PTEN takes forever, I was able to confirm it with a smaller result (just ANK1).

**Comment by IgorRodchenkov** [comment]
@ugurdogrusoz , btw, you cannot confirm the fix with just ANK1, because it worked before the fix ;) 
But you could do with PTEN (that caused the error; luckly hlped us catch some rare condition and NPE bug...).
