### ISSUE TITLE
Bug About Loading Solid Color Scheme Maps on another Map

### ISSUE THREAD

**Issue by umut-er** [iVis-at-Bilkent/newt#726]
Here is a bug I detected with item 4 (file operations) of issue #725. This is specifically about color schemes.

If a sample or file with color scheme of type `solid` is loaded on top of a another already existing map of color scheme `gradient` or `3D`, the colors won't be rendered correctly on the map even though it will be shown correctly on the sidebar. Refer to the video below:

https://github.com/iVis-at-Bilkent/newt/assets/102927626/eb6a2e95-1ab0-4726-b97e-0190636a2235

I determined that this issue is caused by not properly deleting the background image. I tried to fix this and it seems to be gone. Here is the code I changed (this is in newt app-menu.js lines 823-839):

```js
if(currentGeneralProperties.mapColorSchemeStyle == 'solid'){
  for(var nodeClass in appUtilities.mapColorSchemes[currentGeneralProperties.mapColorScheme]['values']){
    classBgColor = appUtilities.mapColorSchemes[currentGeneralProperties.mapColorScheme]['values'][nodeClass];
    // nodeClass may not be defined in the defaultProperties (for edges, for example)

    // NEW CODE
    var bgObj = chiseInstance.elementUtilities.getBackgroundImageObjs(cy.nodes());
    chiseInstance.removeBackgroundImage(cy.nodes(), bgObj);

    // OLD CODE
    // if(nodeClass in chiseInstance.elementUtilities.getDefaultProperties()){
    //   chiseInstance.undoRedoActionFunctions.setDefaultProperty({class: nodeClass, name: 'background-image', value: ''});
    //   chiseInstance.undoRedoActionFunctions.setDefaultProperty({class: nodeClass, name: 'background-color', value: classBgColor});
    // }
  }
}
```

I found the new code after inspecting how the manual removal of background images works. You can see the button related to that:

<img width="285" alt="image" src="https://github.com/iVis-at-Bilkent/newt/assets/102927626/cc3549ff-ea8f-4eb4-bb4f-fe5fecfebd65">

and here is the code related to that button (found at newt inspector-utilities.js lines 817-821):

```js
$('#inspector-delete-bg').on('click', function () {
  var bgObj = chiseInstance.elementUtilities.getBackgroundImageObjs(selectedEles);
  chiseInstance.removeBackgroundImage(selectedEles, bgObj);
  updateBackgroundDeleteInfo();
});
```

as you can see, I copy pasted it almost one-to-one and it seems to be working. However, I don't exactly understand what the old code does and why it doesn't work. I think someone more knowledgable than me should review this change and insure that it doesn't get rid of other functionalities that we might want.

**Comment by umut-er** [comment]
My commit about this issue is misattributed to #725. Here is the commit: a3a52a10acc9bd5d2b7e5781e9342eb1c954235a

**Comment by umut-er** [comment]
Btw, the way to test this easily is this:
1. Load `Neuronal Muscle Signaling` (this has `3D` color scheme)
2. Load `Insuling like growth factor (IGF) signaling` (this has `solid` color scheme).

The changes are now live on the internal server.

**Comment by hasanbalci** [comment]
@umut-er The code you commented is required to set default properties of the map based on the properties read from the file. For example, open Newt, set color scheme to Gradient, open Insulin sample (with solid color scheme) and try to add new nodes to map. You will see that new elements added don't use the color scheme of Insulın but the Gradient.

**Comment by umut-er** [comment]
What if I uncomment the old code as well? Do you think that is a good idea?

**Comment by hasanbalci** [comment]
@umut-er I think it should work. So please uncomment the previous code and keep the new one.

**Comment by umut-er** [comment]
There is another issue as well. If you try to load a plain sbgnml map (not a sample this time) on top of a gradient or 3D the colors are still off. Here is the cause of this issue: After loading a new map, we look for map properties defined inside of it. Since plain sbgnml files don't have such information (compare samples of type .nwt, which have that information), we do not correctly reset the color scheme. I will make a fix for this as well and push them together.

**Comment by umut-er** [comment]
@hasanbalci I did as you requested. The changes are now live on the internal server. Can you review please?

**Comment by hasanbalci** [comment]
It seems working well, thanks. For the other issue, I think it is ok to use the current color scheme when we load SBGN plain files.
