### ISSUE TITLE
Phenotypes in unstable not working properly

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#729]
- Its shape is different than the one in public release. Normally it should be 60x30 but 30x30 in the unstable.
-  When we select multimer option for a phenotype, it becomes invisible and also makes other process nodes invisible as well.

**Comment by hasanbalci** [comment]
After some investigation, I realized that normally Phenotype nodes in PD and AF cannot be multimer, as in the Public deployment. During SBML implementation it is added mistakenly. This commit https://github.com/iVis-at-Bilkent/sbgnviz.js/commit/91cf8ab34cc59dcf26349a4733210efdbfdba8ee adds it first as "phenotype" and then this commit https://github.com/iVis-at-Bilkent/sbgnviz.js/commit/6e543651ea149ed2c6708fc99c946b5d76283398 adds as "phenotype sbml". 

We shouldn't allow "phenotype" in PD and AF to be multimer. Also let's check CellDesigner documentation to ensure the multimer status of "phenotype sbml" nodes in SBML.

**Comment by ugurdogrusoz** [comment]
Regarding the last point above, according to [this](https://docs.google.com/document/d/1pJSngQB3lNcvqk3xSZAJpMdvFsHJlcUJkyAU7Jj2mhE/edit?usp=sharing) phenotypes can be multimers in SBML. Let's just fix SBGN PD and AF, so phenotypes cannot be multimers.

**Comment by NoorMuhammad1** [comment]
Ok. I will make the multimer option to not show for the PD and AF.

**Comment by NoorMuhammad1** [comment]
So I changed the settings that showed multimer option for PD and AF with phenotype. If there is any other node (other than phenotype) that cannot be a multimer, we can change that as well.

**Comment by hasanbalci** [comment]
@NoorMuhammad1 Please instead of commenting it out or returning to false, delete those lines. We don't need to keep unnecessary code.

**Comment by ugurdogrusoz** [comment]
> So I changed the settings that showed multimer option for PD and AF with phenotype. If there is any other node (other than phenotype) that cannot be a multimer, we can change that as well.

Just compare with the public Newt and look at the spec I shared over Skype if needed.

**Comment by NoorMuhammad1** [comment]
I have cross referenced all the nodes from the public Newt and the unstable one. All the nodes have the correct option to make multimer now.
