### ISSUE TITLE
Layout post-processing for port orientation improvement

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#73]
Let's experiment with the following idea and see how it does:
If ports are enabled when layout is called:
- do not disable ports by default on layout
- apply a post-processing step to improve individual port orientations based on some kind of a scoring system. if a particular orientation other than the current one scores better, change the orientation to that one. this is to be done for all process nodes and logical operators.

**Comment by ugurdogrusoz** [comment]
@leonarddrv Thanks, this is great! Can you please post your profiling results? Time without these 2 heuristics and with them.

**Comment by leonarddrv** [comment]
Large graphs
signalling2.sbgn.xml
Time with these heuristics           Time without these heuristics           Percentage of heuristics
53904 ms                                     53535 ms                                          0.7%

signalling3.sbgn.xml
Time with these heuristics           Time without these heuristics           Percentage of heuristics
45910 ms                                     45518 ms                                          0.85%


signalling4.sbgn.xml
Time with these heuristics           Time without these heuristics           Percentage of heuristics
74370 ms                                     73766 ms                                         0.81%

Small graphs
TP53_regulates_trans.sbgn.xml
Time with these heuristics           Time without these heuristics           Percentage of heuristics
1917 ms                                      1823 ms                                            4.9%

vitamins_b6_activation_to_pyridoxal_phosphate.xml
Time with these heuristics           Time without these heuristics           Percentage of heuristics
847 ms                                         824 ms                                            2.7%
