### ISSUE TITLE
File loading improvements

### ISSUE THREAD

**Issue by umut-er** [iVis-at-Bilkent/newt#730]
Here are a couple of suggestions on loading files:

- [ ] 1. When loading large files, the spinner would be a good addition. It is currently commented out in the code. Notice that this is the behavior when remote launching. You can try [this](http://newt.cs.bilkent.edu.tr/?URL=https://www.ebi.ac.uk/biomodels/model/download/MODEL1108160000.2?filename=MODEL1108160000_url.xml&inferNestingOnLoad=true&applyLayoutOnURL=true) (it takes a long time), export it and load it again.
- [x] 2. When trying to drag and drop files to load, we can only load plain sbgnml or newt files. For the other ones, we need to use the import menu. Maybe we can try to infer the type of the file, i.e., check if it has a .sif extension or a .sbml extension.

**Comment by ugurdogrusoz** [comment]
There must be a reason for commenting this out. Needs to be investigated. 
We can proceed with 2. though.

**Comment by umut-er** [comment]
These are now on the internal server. Please review. You just need to drag / drop files with correct extensions. 

- .sbml -> SBML
- .gpml -> GPML
- .sif -> SIF
- .xml -> CD
- everything else -> NWT

Not every file currently works with our converters (see #712). [Here](https://drive.google.com/drive/folders/1Nc9CsgD93twWmn5x0G7XmVuD1nSNihcX?usp=drive_link) are the files I used to test this. Please do check with invalid files (i.e. files that don't work with the import feature also). I haven't extensively tested those scenarios yet.

**Comment by ugurdogrusoz** [comment]
1. I tried loading this sbgnml
[huge1.txt](https://github.com/user-attachments/files/16169172/huge1.txt)
file and @hasanbalci tried loading the file in the launch example (launch, save and then load) and we don't see any spinners.

 2. looks good to me

**Comment by umut-er** [comment]
Sorry I thought I added this. Must've been in my forked repository. Should be fine now. It is up on the internal server for review.

**Comment by ugurdogrusoz** [comment]
1. now works in both cases, thanks. I am surprised though that with the example you provided launching it with URL displays a message about "sipping your coffee" but when you save the file and perform a file load we don't get this message. I don't care if people who are not aware of launching Newt with a URL don't get to sip their coffee, I am just worried that the same code base is not being used and there is code duplication?

**Comment by umut-er** [comment]
I took a look and discovered that the remote launch code has some problems. It tries to access the backbone views (things like promptConfirmationView which shows up if the map is not initially empty) from a context where they are not defined. The reason it appears to be fine in the internal server is that we don't need these views. During remote launch, we won't need a promptConfirmationView to reset the map, for example. However, if you have a map that is not compatible with our converters (like certain cd maps) that can be remote launched, please try that. I don't have any of those maps myself but I am reasonably sure it will cause an error in the console.

**Comment by hasanbalci** [comment]
@umut-er Can you please direct me where this happens: "It tries to access the backbone views from a context where they are not defined."? 

I'm not sure if it makes sense to undertake a large-scale refactoring at this stage.

**Comment by umut-er** [comment]
https://github.com/iVis-at-Bilkent/newt/blob/54d9beac3702f51ec60ec8c720661313e7c22cc3/app/js/app-utilities.js#L3148

https://github.com/iVis-at-Bilkent/newt/blob/54d9beac3702f51ec60ec8c720661313e7c22cc3/app/js/app-utilities.js#L3093

https://github.com/iVis-at-Bilkent/newt/blob/54d9beac3702f51ec60ec8c720661313e7c22cc3/app/js/app-utilities.js#L3159

There are more of them in that same function as well.

I have done a majority of the work. I need to understand what this is
https://github.com/iVis-at-Bilkent/newt/blob/54d9beac3702f51ec60ec8c720661313e7c22cc3/app/js/app-utilities.js#L3182
In the drag & drop type inference, I associate .xml automatically with cd. However, this line above seems to be another criterion to choose between rendering as sbml or cd. What does it do exactly?

**Comment by umut-er** [comment]
Also this:
https://github.com/iVis-at-Bilkent/newt/blob/54d9beac3702f51ec60ec8c720661313e7c22cc3/app/js/app-utilities.js#L3199-L3200

**Comment by umut-er** [comment]
@hasanbalci the first one seems to be a way of rendering and .xml file as sbml. However, I tried to incorporate this and it doesn't work all the time. It misses some files that can be rendered as cd. The second one seems to be a way of rendering sbml files as either sbml or sbgn but I don't understand what this choice is based on.

**Comment by hasanbalci** [comment]
`promptInvalidURLWarning` is currently accessible as it is defined [here](https://github.com/iVis-at-Bilkent/newt/blob/54d9beac3702f51ec60ec8c720661313e7c22cc3/app/js/app-utilities.js#L3058). Probably, the others needs similar initialisations. 

`if (xmlObject.children.item(0).getAttribute('xmlns:celldesigner')) { ` 
This is to decide if .xml file contains sbml or cellDesigner content. 

```
var sbmlProperty= appUtilities.getScratch(appUtilities.getActiveCy(), "sbmlProperty") 
var sbgnOrSbml = sbmlProperty.sbmlMap; //True for sbml, false or undefined for sbgn 
```
This one is to decide whether we will load sbml file in sbml notation or in sbgn notation (after a conversion).

**Comment by umut-er** [comment]
Is there any way we can remote launch cellcycle from [this](https://drive.google.com/drive/folders/1Nc9CsgD93twWmn5x0G7XmVuD1nSNihcX)?

**Comment by hasanbalci** [comment]
@umut-er I think you can push it temporarily to Newt/samples folder.

**Comment by umut-er** [comment]
#733 has been created to issue the further concerns here. I am closing this issue.
