### ISSUE TITLE
Last build date in About box

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#731]
Let's do it similar to the Visuall sample app

**Comment by umut-er** [comment]
I built the Visuall sample app (unstable branch). Here is the about tab.


<img width="376" alt="image" src="https://github.com/iVis-at-Bilkent/newt/assets/102927626/27e33bcf-0e55-4141-8aa3-93db893fbd2c">


I don't see the build time. Can you please elaborate @ugurdogrusoz?

**Comment by ugurdogrusoz** [comment]
My bad; it was another application. I am sharing it privately.

**Comment by umut-er** [comment]
Currently we have the last build date up on the internal server. New timestamp is added each time the build.sh script is run. However, I think there is some ~10 min discrepancy between the time stamp and actual build time. This doesn't happen on my local development environment, only on the internal server. I don't know the cause. I am using standard libraries and did this extremely similar to the visuall app.

One potential concern is about the automatic builds. I don't know if they run the regular build.sh script.
