### ISSUE TITLE
SBML UI, palette and legend improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#734]
We need to address some enhancements (thanks @adrienrougny) before the release in SBML:

- [x] 1. Drug node type should be represented with a **stadium** shape, not a rounded rectangle (see Simple Chemical in PD that also uses stadium shape)
- [x] 2. Text of the **Omitted Process** node should be "//" (for compatibility with CellDesigner), not "\\\\" (which is used in PD)
- [x] 3. **Truncated Process** would look better with a non-italic "N"
- [ ] 4. We should reorganize nodes and edges both in the palette (tiled row by row with separators) and in the legend (tiled column by column without separators) as suggested by @adrienrougny below. Also, let's decrease the space between icons in the same row and between rows to make them more compact
- [x] 5. This is fine in the palette but in the legend, either the nodes that should have a square shape do not have square shapes or they are distorted when displayed. I also noticed this with edges (arrows that should be square seem to be stretched). Marked as noticed below:
- [x] 6. Some nodes in the SBML palette are not aligned properly when selected (e.g. Gene). The SVG images for these nodes seem to have some white space on one side (for Gene it's on the right for instance). We should get rid of these white spaces. Also, some nodes are wider than others (i.e. Receptor), whereas some are narrower (e.g. Ion). We should size these consistently.
- [x] 7. The width of the node and edge tools in the toolbar (see below) should be fixed so that when a different node or edge is chosen from the palette or from the toolbar, icons in the toolbar should not shift.
<img width="548" alt="Screenshot 2024-07-18 at 15 36 04" src="https://github.com/user-attachments/assets/59d2159c-cdf5-4977-ac88-09962e40b646">
<img width="372" alt="Screenshot 2024-07-18 at 15 33 12" src="https://github.com/user-attachments/assets/2210e538-606c-4910-a88f-d960754284f8">

**Comment by ugurdogrusoz** [comment]
For item 4, I changed the description.

**Comment by umut-er** [comment]
<img width="268" alt="image" src="https://github.com/user-attachments/assets/a7a7bd6f-9809-4e5e-a432-412b311bd07f">

When you select some nodes in the palette, their blue border is not centered. See with `gene` on the SBML palette.
@ugurdogrusoz can you add this to the list?

**Comment by umut-er** [comment]
Please check items 2, 3, 4, 5. 
  
For item 1, we want two stadium shapes, one inside the other, right (like the current drug node)? And from what I understand the stadium shape is defined as a rectangle with half circles as the side borders. Let me know if that is accurate.
  
Item 6 affects 3 nodes (that I can detect). Those being gene, ion channel and drug. I will fix the drug node while resolving item 1.

**Comment by umut-er** [comment]
For item 6, I have this (left is old, right is new). I tried to match them horizontally and not so much vertically:
    
<img width="282" alt="image" src="https://github.com/user-attachments/assets/9f65369f-8cb7-4ac2-93a4-5239f160607c"><img width="281" alt="image" src="https://github.com/user-attachments/assets/63faf368-ebb5-4cb9-82e3-2047efebfecd">
<img width="268" alt="image" src="https://github.com/user-attachments/assets/899609fb-4c90-4c93-be0c-6f36e3fe7f56"><img width="269" alt="image" src="https://github.com/user-attachments/assets/ed4e169b-b4a7-44ba-8652-32a72b0ef746">

For the other two I didn't change much. If you like this new one, I can push it to the internal server. Keep in mind that the `drug` node will change.

**Comment by adrienrougny** [comment]
Could it be possible to have more divisions than just the nodes/arc divisions? For example one for the EPNs, another one for the logical operators, another one for the process nodes, etc.?

**Comment by umut-er** [comment]
I don't see why it shouldn't be possible. Please write exactly how you want the divisions to be and I will see what I can do.

**Comment by adrienrougny** [comment]
> Please check items 2, 3, 4, 5.
> 
> For item 1, we want two stadium shapes, one inside the other, right (like the current drug node)? And from what I understand the stadium shape is defined as a rectangle with half circles as the side borders. Let me know if that is accurate.
> 
> Item 6, the centering problem affects 3 nodes (that I can detect). Those being gene, ion channel and drug. I will fix the drug node while resolving item 1.

The drug glyph is indeed two times a rectangle with half circles when w >= h, but in CellDesigner it is not half circles anymore when w < h (see attached). Not sure you want to have it like in CellDesigner though. The stadium shape is also used for the Simple chemical glyph in the PD palette (though here, when w < h, the two half circles are made vertical).
![drug](https://github.com/user-attachments/assets/c8f492ea-c05d-45b0-85f4-21b11d8196f8)

**Comment by adrienrougny** [comment]
For the PD palette I would suggest:
---
7 first nodes (from macromolecule to empty set)
---
6 following nodes, from the phenotype to the dissociation (and phenotype could be put at the end)
---
compartment
---
3 logical operators
---
submap and terminal/tag
---
consumption and producation arcs
---
all the modulation arcs
---
logic arc and equivalence arc

**Comment by adrienrougny** [comment]
For the SBML palette I would suggest:
***
13 first nodes:  protein, protein receptor, ion channel, truncated protein, gene, rna, antisense rna, phenotype, ion, simple molecule, drug, unknown, complex, degraded (order in CellDesigner)
***
6 following nodes: state transition, known omitted state transition, unknown transition, heterodimer association, dissociation, truncation
***
compartment
***
the four logical operators
***
consumption, production, transcription consumption, transcription production, translation consumption, translation production, transport production
***
catalysis, unknown catalysis, inhibition, unknown inhibition, physical stimulation, modulation, trigger
***
positive influence, unknown positive influence, unknown physical stimulation, unknown modulation, unknown trigger

**Comment by ugurdogrusoz** [comment]
> Please check items 2, 3, 4, 5.
> 
> For item 1, we want two stadium shapes, one inside the other, right (like the current drug node)? And from what I understand the stadium shape is defined as a rectangle with half circles as the side borders. Let me know if that is accurate.

Yes, correct.

**Comment by ugurdogrusoz** [comment]
Let's organize (with separators) the nodes and edges in the Palette as @adrienrougny suggests.
We should have the same ordering in the Legends (no separation and column by column as before).

**Comment by ugurdogrusoz** [comment]
> The drug glyph is indeed two times a rectangle with half circles when w >= h, but in CellDesigner it is not half circles anymore when w < h (see attached). Not sure you want to have it like in CellDesigner though. The stadium shape is also used for the Simple chemical glyph in the PD palette (though here, when w < h, the two half circles are made vertical).

Let's use the same UI as PD simple chemical but wider by default (current dimensions are fine).

**Comment by umut-er** [comment]
> 5 is not fixed (nodes that are square are not; same with edge arrows)

Can you say what nodes and edges are problematic? I focused on modulation arcs and process nodes. Is there something I am missing?

**Comment by umut-er** [comment]
The new drug shape and all related svg images (sidebar icon and legend) has been added. Please review it after the server is rebuilt. 6 should also be fine for review. I am moving on to item 4 and waiting for the list of stretched nodes for item 5. Just a note, in some of the edges (positive / negative influence, transcription consumption etc.), I used the gene node as a demonstration, which is a rectangle. I checked the process nodes in the svg and they seem to be squares.

**Comment by umut-er** [comment]
For item 4, if we are going to seperate based on common functionality, what about labeling them as well? I went ahead and created a visual for you below. If you like it, I can implement it. Please feel free to make suggestions. Also, please make a list of what the labels should be on the current seperator plan if you want it to be implemented.

<img width="282" alt="image" src="https://github.com/user-attachments/assets/98b08a50-7abc-4e9a-8a6f-b79923ce9861">

**Comment by umut-er** [comment]
I have pushed the change above so you can look at it in the internal server (after rebuild). We can go back to the original easily as well.

**Comment by umut-er** [comment]
Just as a summary: Please check 1, 4, 6 and for 5 tell me which nodes / edges are stretched.

**Comment by ugurdogrusoz** [comment]
PD:
- *Entity Pool Nodes*: move Complex to the end of the list
- *Container Nodes* should be eliminated and Compartment should be moved to *Other Nodes*. *Container Nodes* should be in this order: Compartment, Submap, and Tag (same as *Other Nodes* in AF actually)
- *Logic Arcs* should be eliminated and contents should be moved to the end of *Connecting Arcs* in the same order (Logic Arc and then Equivalence)

AF:
- *Logical Operations*: rename as *Logical Operators*
- Combine *Modulating Arcs* and *Logic Arcs* into one (modulating arcs followed by logic arcs in the current order) and name it *Connecting Arcs*

SIF:
- *SIF Edges*: rename as *Connecting Edges*

SBML:
- To be continued

**Comment by umut-er** [comment]
I think this should be ready for a complete review (all 7 items).

**Comment by hasanbalci** [comment]
IMHO, we should go back to the original version of the Palette and only separate groups by using simple separators with section titles as shown in the above comment and nothing else. We don't need to change image sizes, since they are reflecting the actual node sizes (we draw EPNs larger than logic node and we draw logic nodes larger than PNs, so original version is good in reflecting this). Currently, elements are left-aligned but it causes unnecessary empty space on the right, so they should also be aligned in the center like in the original version.

**Comment by umut-er** [comment]
I have pushed the fix to the centering problem. Please make the decision about whether we are going to use old images and margins on the palette. We can go back fairly easily, so that is not a concern.

**Comment by ugurdogrusoz** [comment]
Looks very good in general. Remaining improvements (and then we are good to go):
item 4. The nodes are too close to each other in SBML palette. Let's put a bit more space between nodes in all palettes (then for example EPNs in PD will better cover their row as well). Let's also center align nodes in their respective position (might be already fixed):
<img width="142" alt="Screenshot 2024-07-19 at 16 01 18" src="https://github.com/user-attachments/assets/f3b8c020-1da6-4d42-911c-36076b27365e">

As before, we should reflect the relative dimensions of nodes in the palette somehow. For this, we should just make process nodes in PD and SBML smaller (slightly smaller than logical operators as they are drawn on the canvas).

item 5: The two diamonds on the right should be a bit bigger to match the left one:
<img width="232" alt="Screenshot 2024-07-19 at 16 03 57" src="https://github.com/user-attachments/assets/94f0a620-45db-4b04-a1d6-83569e1d2671">

item 7: This problem is resolved but by stretching narrower nodes. Each node/edge should occupy the same width but without stretching (e.g., an association is a circle, not an ellipse):
<img width="229" alt="Screenshot 2024-07-19 at 16 05 50" src="https://github.com/user-attachments/assets/d09e4dc8-c783-4133-bbee-238449742323">

**Comment by ugurdogrusoz** [comment]
Almost there:
- Legend - SBML: Let's make the degradation node a bit smaller
- Palette: can we make the left padding/indentation a bit smaller (or the spacing bw nodes/edges a bit smaller), so that more nodes (1 more on a 16inch laptop screen) fit in one row:
<img width="393" alt="image" src="https://github.com/user-attachments/assets/6c3c341f-449c-4bfe-8411-2c5663d36f84">

**Comment by umut-er** [comment]
I have added those features. Regarding the palettte improvement:

I think screen resolution (and specifically in the horizontal direction) is the determining factor rather than screen size. Here are some common screen resolutions and how the palette looks like in those resolutions:

1920x1080: Untestable on my machine. It will have 7 nodes per row with pretty good margins.

1680 x 1050:
<img width="332" alt="image" src="https://github.com/user-attachments/assets/be008a42-033a-4eba-9dcd-d44a0312a854">

1536x864:
<img width="300" alt="image" src="https://github.com/user-attachments/assets/a5b873f1-55c7-48f5-aba7-2eea43d153e5">

1440x900:
<img width="283" alt="image" src="https://github.com/user-attachments/assets/2804c643-6516-4c7f-b1c7-42a962d63fed">

1366x768:
<img width="268" alt="image" src="https://github.com/user-attachments/assets/b3046889-f088-428b-9247-1da8c18ff267">

If the screen width is:
- \>1660px, we have 7 nodes / row, 
- \>1450px, we have 6 nodes / row,
- \>1200px, we have 5 nodes / row
- otherwise, we have 4 nodes / row

**Comment by umut-er** [comment]
Can I learn the screen resolution in which the picture above is taken?

**Comment by ugurdogrusoz** [comment]
> Can I learn the screen resolution in which the picture above is taken?

1792 x 1120

**Comment by ugurdogrusoz** [comment]
The palette and the toolbar are great now. The only thing left is to change the order of the nodes and edges in the **Legends** (same order except organized column by column, instead of row by row and no need for separators - leave SIF as is).

**Comment by ugurdogrusoz** [comment]
Two more very minor issues in SBML legend:
- These two process nodes should be swapped
- The logical operators should be closer to each as in other notations
