### ISSUE TITLE
Losing unit of information boxes after export/import of SBML maps

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#738]
In SBML map type, if we add unit of information to the nodes and then export and import the map, the unit of information data is lost. We cannot see them both on the node and on its properties.

**Comment by hasanbalci** [comment]
Apparently, the same goes for Binding Region and Residue Variables.

**Comment by umut-er** [comment]
@hasanbalci Do you know if those functionalities (unit of information, binding region and residue variables) are a part of any official sbml standard or any official sbml extension? Or are they endemic to Newt? I have not seen anything about those in the documentations. If they are only available in Newt, we might have to add those information as annotations because no other service will be able to understand those.

**Comment by hasanbalci** [comment]
I think they come from CellDesigner notation. If you open SBML table from Legend -> SBML -> SBML Table, you will see them on the top-left, under Species. See also [this](https://www.celldesigner.org/help/CDH_Protein_03.html).

**Comment by umut-er** [comment]
Yes, they export it in annotations also. We will do the same.

**Comment by umut-er** [comment]
Here is my plan on how I am going to encode necessary information:
  
First of all let's look at how celldesigner encodes it:
```xml
<model>
    <annotation>
        <celldesigner:extension>
            <!--Unnecessary parts omitted--> 
            <celldesigner:info state="open" prefix="pc" label="T" angle="-1.5707963267948966"/>
            <!--Unnecessary parts omitted-->
        <celldesigner:extension>
    </annotation>
<model>
```
This document contained only a single RNA with information `pc:T`. The annotation part of an SBML document is basically software generated optional content which is not meant to be directly shown to the user (i.e., it doesn't contain formatted strings etc.). See also bottom of page 16 on the [official SBML specifications](https://sbml.org/specifications/sbml-level-3/version-2/core/release-2/sbml-level-3-version-2-release-2-core.pdf). 

On #712 we decided to use `nwt:` as our sbgnml namespace. I will also go with this namespace in our sbml annotations. We also `must choose a URI (Universal Resource Identifier ; Harold and Means 2001;
5 W3C 2000a) reference that uniquely identifies the vocabulary the application will use.` (page 17 on SBML specs) I am not sure what this is exactly. Celldesigner uses `http://www.sbml.org/2001/ns/celldesigner`.

Here is a brief explanation. We will have to encode multimer, active, hypothetical as boolean values; unit of information, binding region, residue variables as string values. Here is an example:
```xml
<model>
    <annotation>
        <nwt:extension xmlns="URI goes here">
            <nwt:info nwt:multimer="true" nwt:active="false" nwt:hypothetical="true" nwt:info-id="info_1" nwt:id="nwtSV_9c013ecf-435a-4038-87ea-faccadae1321">
               <nwt:unit-info>something</nwt:unit-info>
               <nwt:unit-info>another thing</nwt:unit-info>
               <nwt:binding-region>yet another thing</nwt:binding-region>
               <nwt:residue-variable>you get the point</nwt:residue-variable>
            </nwt:info>
        </nwt:extension>
        
        <layout:listOfLayouts>
            <!--Layout information from issue #712 will eventually go here--> 
        </layout:listOfLayouts>
    </annotation>
<model>
```

We will also have to implement functionality to read annotations on files. I am not sure how to do that yet.

Please let me know if you have feedback. Also let me know what I should do about the URI thing I mentioned above.

**Comment by ugurdogrusoz** [comment]
Let's use `https://newteditor.org/` for URI until we figure this out. Using "nwt:" as namespace when outputting .sbml files is also OK as long as we know how to read it back (**as well as** being able to read in .sbml files that don't use this namespace).

**Comment by umut-er** [comment]
@hasanbalci Please check this after the server rebuilds. There *might be* some cases where the boxes are preserved but their order might be different. I don't know why that happens (If it happens, I am not sure. It might be fixed).

**Comment by ugurdogrusoz** [comment]
If it's not easy to handle, I think it's ok to leave it for feature work (just lose the milestone).

**Comment by umut-er** [comment]
It might be fixed. Please check after the server rebuilds @hasanbalci @ugurdogrusoz.

**Comment by hasanbalci** [comment]
@umut-er It works now, thanks!
