### ISSUE TITLE
SBML connection problem

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#740]
In case we have a protein, process and AND node, if we first connect AND to process via a catalysis edge, then we cannot connect protein to process via a consumption edge. However, if we first connect protein to process via a consumption edge, then we can connect AND to process via a catalysis edge. We should be able to connect consumption edge in the first case as well.

**Comment by umut-er** [comment]
There is a more general issue of sbml processes not being allowed to take in multiple inputs or multiple outputs (except association / dissociation, those are allowed to give out only 1 output but can take unlimited inputs). This is probably relevant to this issue.

**Comment by ugurdogrusoz** [comment]
> There is a more general issue of sbml processes not being allowed to take in multiple inputs or multiple outputs (except association / dissociation, those are allowed to give out only 1 output but can take unlimited inputs). This is probably relevant to this issue.

Associations take 2 or more inputs and output 1. Dissociations do the reverse and take only 1 input, producing at least. Constructing a compound molecule (i.e. a complex) vs. decomposing it back.

From what I can tell dissociation works fine. Associations can also take multiple inputs but no output can be constructed.

All other process node types seem to have problems taking multiple inputs or outputs, except truncated processes which can produce multiple outputs. 

So, things are pretty random / messed up for some reason.

**Comment by umut-er** [comment]
@ugurdogrusoz  This behavior you described above was also implemented into the export functionality. I changed those so that we can have the wanted behavior as part of #712.

**Comment by ugurdogrusoz** [comment]
@umut-er Do you mean this issue is part of #712 (redundant) and can be closed? If so, please close it.

**Comment by umut-er** [comment]
No, I am not saying that. I am saying that the export functionality was made with this in mind. It is now changed though.

**Comment by ugurdogrusoz** [comment]
Original problem with protein, process and AND node connections are fixed but:
- we have problems with the rules on what can connect to what
- we have problems that a process cannot produce multiple species (>1 output)
