### ISSUE TITLE
Prevent SBGN Bricks on map type SBML

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#741]
Normally, we can add specified node groups by using SBGN Bricks (Edit -> Add Using SBGN Bricks...) if the map type involves PD. If map type doesn't involve PD, we do nothing. However, currently we can add nodes via SBGN Bricks if the map type is SBML. Let's disable it as well.

**Comment by ugurdogrusoz** [comment]
When the map type is not PD or PD+AF or All, we should put a warning that says "Can only use with PD maps!"

**Comment by umut-er** [comment]
Should be fixed.

**Comment by hasanbalci** [comment]
@umut-er It works correctly now, thanks!
