### ISSUE TITLE
Complex/compartment UI improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#79]
- an empty complex and a collapsed complex should have the same dimensions; currently not the case (collapsed one is slightly bigger):
![image](https://user-images.githubusercontent.com/3874988/27185421-eee3de80-51ed-11e7-8183-ac4f6da41072.png)
- empty and collapsed complexes are pretty small and should have smaller cutoffs at corners (smaller than expanded complexes); otherwise the shape looks like a diamond
- apparently (as can be seen above as well) label length to fit into a complex/compartment node is not calculated correctly (overflows bounds)

**Comment by kinimesi** [comment]
@ugurdogrusoz 

Didn't you want to increase the cutoffs in https://github.com/iVis-at-Bilkent/newt/issues/70 Should I do the reverse of what @leonarddrv  did in #70?

I think empty and collapsed complexes had the same dimensions before fixes applied to #70

**Comment by ugurdogrusoz** [comment]
@kinimesi collapsed complexes and compartments are 36x36, which is fine. the problem is due to large cutoff corners, they look like a different shape. using the same dimension as empty complexes or compartments is not needed (the reason we want them a bit big is because we want users to be able to easily drag new members into them). I think we should use smaller cutoffs when complexes are collapsed (if this is not technically difficult/tricky) and we'll be fine.
