### ISSUE TITLE
Compound is resized even though "Allow Compound Node Resize" option is checked

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#80]
Produce:
- Open a new sheet and check the "Allow Compound Node Resize" option
- Add a compartment and make it larger
- Add an entity inside the compartment
- **It resizes, which is not wanted!**
- Then, make the compartment larger again
- Add a new entity inside the compartment, now it works correctly

**Comment by metincansiper** [comment]
I think that when you add the compartment it is a simple node. When you are resizing it you resize a simple node, not a compound node. Therefore, I think that there is no compound resize action here and this may not be related to "allow compound resize" option.
