### ISSUE TITLE
Collapse visual cue repaint problem

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#81]
Drag and drop a new child towards the upper right corner of a compound node at a location where addition of the child is to make compound bigger. You will see that two collapse cues are displayed incorrectly:
![image](https://user-images.githubusercontent.com/3874988/27329184-64d7d042-55bd-11e7-8b78-a8b461c54375.png)
Happens independent of the value of Allow Compound Node Resize flag

**Comment by metincansiper** [comment]
It seems to be solved.
