### ISSUE TITLE
Complex changing class to complex multimer

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#82]
As mentioned in this issue (https://github.com/iVis-at-Bilkent/newt/issues/76), a complex changing class to complex multimer during its lifetime is problematic. Can we perhaps redesign this?
Example: dragging (or transferring) a node from the palette into a complex multimer won't work since the related code checks for class "complex" not "complex multimer".

**Comment by ugurdogrusoz** [comment]
Looks like SBGNML itself differentiates multimers from non-multimer nodes (e.g. complex from complex multimer). So maybe it's OK to have separate classes for such nodes. What we need to do is anything that applies to a node type should also apply to its multimer version. For instance, if a macromolecule can go inside a complex, it can also go inside a complex multimer; or if a n.a.f. can have a consumption edge, so can a n.a.f. multimer. Since we're checking for node types by looking at its class, which is a string, we can simply remove "multimer" from the class name prior to checking for rules (@kinimesi's idea).

**Comment by ugurdogrusoz** [comment]
This works fine when I drag a node (using control) into a complex multimer but not when I directly drop a macromolecule into a complex multimer.

**Comment by kinimesi** [comment]
It is not only dragging and dropping nodes. There are much more cases to consider including collapse/expand multimer complexes, edge constrains for multimer nodes, and parent - child relationship for multimer nodes, default properties and more.
