### ISSUE TITLE
Use new node shape barrel for compartments

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#85]
Use this new shape named barrel to be available in version 3.2.0 or Cytoscape.js for compartments

**Comment by ugurdogrusoz** [comment]
From Dylan:
Here are the commits related to it.  Maybe you could try porting it over to your branch.

https://github.com/cytoscape/cytoscape.js/pull/1824/commits

https://github.com/cytoscape/cytoscape.js/pull/1831/commits

**Comment by ugurdogrusoz** [comment]
Done?

**Comment by kinimesi** [comment]
@ugurdogrusoz https://github.com/cytoscape/cytoscape.js/issues/1874 is the remaining problem. Since compartments can not have edges connected to them in AF and PD maps, this won't effect the functionality.

**Comment by ugurdogrusoz** [comment]
I already updated the legends and the palette icons but we also need to update the shape that is rendered during dragging and dropping from the palette.

**Comment by ugurdogrusoz** [comment]
Looks like the same image is used; so this is OK.
