### ISSUE TITLE
Talk about weird bug!

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#89]
- Starting from a blank map, create 2 AF nodes
- Edit > Create Compartment for Selected
- Try dragging the compartment or the children nodes and see what happens :)

**Comment by kinimesi** [comment]
@ugurdogrusoz it is specific to AF.
1. Create a PD node and add unit of information box
2. Edit > Create Compartment for Selected
3. Try dragging the compartment or the children nodes and see what happens :(

This was working before (see: http://cs.bilkent.edu.tr/~ivis/ChiSE_tiling_test/) Most probably this was introduced after https://github.com/iVis-at-Bilkent/sbgnviz.js/pull/182

**Comment by royludo** [comment]
Fixed. But part of this issue is caused by changeParent() not being used here. For this kind of macro-like feature, I think we should be able to use a sequence of already defined undoable actions in a batch.

**Comment by ugurdogrusoz** [comment]
@metincansiper are we not using exposed API but a workaround from the past here?

**Comment by metincansiper** [comment]
We are using exposed API (http://js.cytoscape.org/#eles.move) to change parent of nodes.

**Comment by ugurdogrusoz** [comment]
@metincansiper are we not using a sequence of already defined undoable actions in a batch?

**Comment by metincansiper** [comment]
@ugurdogrusoz I think we do not always use batch of already defined undoable actions. Some undoable actions may be reviewed.

**Comment by metincansiper** [comment]
For example we have a base function ```elementUtilities.createCompoundForGivenNodes()``` If undoable option is false it is called directly. If it is true, ```undoRedoActionFunctions.createCompoundForGivenNodes()``` is called internally which utilizes ```elementUtilities.createCompoundForGivenNodes()```. It seems that if we use batch of undoable actions here, ```undoRedoActionFunctions.createCompoundForGivenNodes()``` will not utilize ```elementUtilities.createCompoundForGivenNodes()```. I think that having a relation between ```undoRedoActionFunctions.createCompoundForGivenNodes()``` and ```elementUtilities.createCompoundForGivenNodes()``` may be good because if we have it, we can ensure that things will work similar both in undoable and not-undoable mode. There may be such concerns behind defining such undoable things as batch of other undoable operations.

**Comment by ugurdogrusoz** [comment]
@royludo the issue seems to be resolved, thanks. about your other comments, I tried to gather some facts from Metin. let us know if you still have concerns, suggesting how to handle them (a discussion, a separate issue?) in any case please close the issue after answering this.

**Comment by royludo** [comment]
@metincansiper I guess you're right. I think I was mostly complaining about the fact that the our specific changeParent() function wasn't used there instead of the generice move() function of cytoscape.
