### ISSUE TITLE
Select objects of this type could be more differentiating in AF

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#90]
I think all biological activities are treated to be of the same type for "Select Objects of This Type" context menu operation. Can we have this to be more differentiating and selecting only macromolecules when performed on a macromolecule for instance?

**Comment by kinimesi** [comment]
@ugurdogrusoz All biological activities have the same `class` in SBGNML file format. Therefore we assign all biological activities the same `class` -- `biological-activity`.and "Select Objects of This Type" selects objects based on `class`.

Why should we treat each biological activity separately, while they are considered the same in the official format?

**Comment by ugurdogrusoz** [comment]
For example, a user might like to style all macromelocule BAs to have a distinguishing color. We can reconsider if the implementation of this introduces some kind of a workaround potentially creating bugs.

**Comment by kinimesi** [comment]
@ugurdogrusoz updated daily as well

**Comment by ugurdogrusoz** [comment]
Here is a similar problem. When you change the style of a BA macromolecule to have green borders for instance and set it as default from Object Properties. This new style applies to all BAs, not just BA macromolecules.

**Comment by ugurdogrusoz** [comment]
Should this be done using the newly refined class scheme?

**Comment by kinimesi** [comment]
I reverted the previous fix https://github.com/iVis-at-Bilkent/newt/commit/78878b64cde63ac6ec7acb9eb1be39ddf5fb32aa

Now everything is done based on the class type.
