### ISSUE TITLE
AF delay symbol could be a bit bigger

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#91]
Would it cause trouble (say in adjusting font label size automatically) if the delay symbol in AF had a larger font size (than other logical operators) since its label looks smaller than other logical operators'?
![image](https://user-images.githubusercontent.com/3874988/27468573-32a62dd4-57f3-11e7-9a23-0ca8f1cbc7f3.png)

**Comment by ugurdogrusoz** [comment]
Can we perhaps use a different font for the delay symbol (if it's not going to complicate any calculations) so it looks more like the greek symbol as opposed to T? Math Cambria is what I used in designing the associated icon.

**Comment by kinimesi** [comment]
If we change the font to Cambria and set font size to 15 (as opposed to 10):
![image](https://user-images.githubusercontent.com/7281872/27474899-01c6e53c-580c-11e7-891e-28f6fb436cfd.png)

For referance, the icon is below:
![image](https://user-images.githubusercontent.com/7281872/27474969-339cdd46-580c-11e7-8d5b-f464a5f769f4.png)

It should not complicate anything that I know.

**Comment by ugurdogrusoz** [comment]
Yes, this is good, let's do it then. Shall we use font size 16?

**Comment by kinimesi** [comment]
@ugurdogrusoz  Now font size of delay is calculated dynamically (on resize font size updated).

You can test it on daily.
