### ISSUE TITLE
AF persistency

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#93]
We need load/save support for AF maps as well. 
We also need to discuss what to do on Save when the map is mixed (PD + AF). I forget if SBGML supported having both types of glyphs in the same file.
In addition, on opening a new file, if the loaded model is a purely PD one, let’s set the map type as PD and have PD nodes/edges open in the Palette and AF ones closed and vice versa.

**Comment by royludo** [comment]
@ugurdogrusoz Af can be persisted now, still need to handle palette accordingly.

I save mixed maps with and 'unknown' language, that will never be something that is valid for sbgnml format I think. On load, if language is unknown then all nodes are of type unknown and map type is also unknown. It works for us, the problem will be when exchanging this kind of file. But if we explain it correctly then users you will probably understand that it's not supposed to be a standard thing.

There isn't really a different type of glyph for AF, it's just a different class name and one more <entity> tag attached to units of information. So mixing them in one file isn't so problematic for us, from an sbgnml perspective, and if we keep in mind that it isn't valid of course.

**Comment by royludo** [comment]
If map type is unknown, palettes are left as is.
