### ISSUE TITLE
Operations applicable in specific map type

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#95]
When an operation is applicable only for a specific map type, we should ignore that operation (shouldn't create a command in undo stack for it either). Such operations:
- Edit > Add Complex for Selected
- Highlight > Processes of Selected
- View > Collapse / Expand Complexes

**Comment by kinimesi** [comment]
@ugurdogrusoz Should we disable (make unclickable) or just ignore them?

What about our **Uknown** map type? Which operations should be available and which ones shouldn't?

**Comment by ugurdogrusoz** [comment]
just ignore them for now (we haven't been disabling inapplicable operations so far)
good question regarding map type: I think what we want to do is ignore these operations when map type is AF (PD or Unknown)
