### ISSUE TITLE
Hide / unhide in AF

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#96]
Hide seems to work fine in AF but Show Hidden Neighbors won't work for some reason

**Comment by hasanbalci** [comment]
@ugurdogrusoz please, can you check whether it is working as you want?

**Comment by ugurdogrusoz** [comment]
Yes this is the correct behavior; it now works in AF as well. The only problem is with undo. Regardless of the map type, undo cannot be done is a single step just like the "Show Hidden Neighbors" operation. Looks like we're not bundling the operations as a batch.

**Comment by ugurdogrusoz** [comment]
Hide in AF doesn't behave correctly; we shouldn't hide any neighbors of selected on "Hide Selected"
