### ISSUE TITLE
Color scheme update for AF

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#97]
We need to update the color schemes to also include AF. Need to decide whether to use the same schemes or separate ones? Also need to address map type "Unknown".

**Comment by ugurdogrusoz** [comment]
Actually some nodes in AF (those that also exist in PD?) do get changes on color scheme change

**Comment by ugurdogrusoz** [comment]
I suggest we use the same schemes we have for PD and map existing colors to AF nodes

**Comment by ugurdogrusoz** [comment]
Can we also include the new glyph "Submap" (available in both PD and AF) in the color scheme?

**Comment by royludo** [comment]
I used the same scheme as PD for AF. For example colors for PD macromolecule and AF biological activity macromolecule are the same and so on. Submaps have the same colors as compartments.
